/**
 * Letter/digit → TTS audio path mapping for AlphabetMaze TTS playback.
 *
 * Letters (А–Я): dedicated short clips — just the letter sound — generated by
 *   `npm run tts:extras` into public/assets/lesson-00/audio/tts/maze/
 *   (previously used the grammar table rows which include example words)
 * Digits (0–9): generated by `npm run tts:generate-digits` in
 *   public/assets/lesson-00/audio/tts/digits/{n}.mp3
 */

const MAZE_BASE   = '/assets/lesson-00/audio/tts/maze';
const DIGITS_BASE = '/assets/lesson-00/audio/tts/digits';

// Bulgarian alphabet — index mirrors the grammar table row order (А=0, Б=1, … Я=29)
const LETTER_ORDER = [
  'А', 'Б', 'В', 'Г', 'Д', 'Е',
  'Ж', 'З', 'И', 'Й', 'К', 'Л',
  'М', 'Н', 'О', 'П', 'Р', 'С',
  'Т', 'У', 'Ф', 'Х', 'Ц', 'Ч',
  'Ш', 'Щ', 'Ъ', 'Ь', 'Ю', 'Я',
] as const;

const letterAudioMap = new Map<string, string>();

LETTER_ORDER.forEach((letter, index) => {
  const p = `${MAZE_BASE}/l00-maze-letter-${index}.mp3`;
  letterAudioMap.set(letter, p);
  letterAudioMap.set(letter.toLowerCase(), p);
});

// Digits 0–9 → /assets/lesson-00/audio/tts/digits/{n}.mp3
for (let d = 0; d <= 9; d++) {
  letterAudioMap.set(String(d), `${DIGITS_BASE}/${d}.mp3`);
}

/**
 * Returns the TTS audio URL for a given letter (А–Я, case-insensitive) or digit (0–9).
 * Returns null if no audio is mapped.
 */
export function getLetterAudioPath(char: string): string | null {
  const upper = char.toUpperCase();
  return letterAudioMap.get(upper) ?? letterAudioMap.get(char) ?? null;
}
