import type { LessonContent } from '@/content/types';

export const content: LessonContent = {
  introduction:
    'В девети урок ще научите думи за мебели, стаи и предмети в дома. Ще използвате предлози за място (до, над, под, пред, зад, в, между, срещу) и поредни числителни (първи, втори, трети...). Ще се запознаете и с обяви за апартаменти под наем.',

  sections: [],

  dialogues: [
    {
      id: 'l09-dialozi-1',
      speakers: [
        { name: 'Мария', text: 'Имам нов апартамент – голям и хубав.' },
        { name: 'Валя', text: 'Чудесно! Колко стаи има?' },
        { name: 'Мария', text: 'Има 5 стаи – кухня, хол, стая за децата и две спални. Холът има голям балкон.' },
        { name: 'Валя', text: 'Банята голяма ли е?' },
        { name: 'Мария', text: 'Да, много е удобна. Стаята за децата е светла, също има балкон. Апартаментът е на втория етаж. На първия етаж има аптека и малко кафе. Съседите са много мили.' },
        { name: 'Валя', text: 'Млади ли са?' },
        { name: 'Мария', text: 'Да, младо семейство с едно дете. Мъжът работи в банка, а жената е учителка.' },
        { name: 'Валя', text: 'Къде е апартаментът?' },
        { name: 'Мария', text: 'В Борово. Кварталът е тих, наблизо има парк.' },
        { name: 'Валя', text: 'Аз също искам нов апартамент, но нямам пари. Апартаментът ми е малък, няма балкон, не харесвам квартала.' },
      ],
    },
  ],

  vocabulary: [
    { id: 'balkon', bulgarian: 'балкон', translations: { en: 'balcony', fr: 'balcon', ar: 'شرفة', fa: 'بالکن', ru: 'балкон', uk: 'балкон' } },
    { id: 'banya', bulgarian: 'баня', translations: { en: 'bathroom', fr: 'salle de bain', ar: 'حمام', fa: 'حمام', ru: 'ванная', uk: 'ванна кімната' } },
    { id: 'biblioteka', bulgarian: 'библиотека', translations: { en: 'bookcase / library', fr: 'bibliothèque', ar: 'مكتبة', fa: 'کتابخانه', ru: 'библиотека / книжный шкаф', uk: 'бібліотека / книжкова шафа' } },
    { id: 'vana', bulgarian: 'вана', translations: { en: 'bathtub', fr: 'baignoire', ar: 'حوض استحمام', fa: 'وان حمام', ru: 'ванна', uk: 'ванна' } },
    { id: 'vilica', bulgarian: 'вилица', translations: { en: 'fork', fr: 'fourchette', ar: 'شوكة', fa: 'چنگال', ru: 'вилка', uk: 'виделка' } },
    { id: 'vkashti', bulgarian: 'вкъщи', translations: { en: 'at home', fr: 'à la maison', ar: 'في البيت', fa: 'در خانه', ru: 'дома', uk: 'вдома' } },
    { id: 'vrata', bulgarian: 'врата', translations: { en: 'door', fr: 'porte', ar: 'باب', fa: 'در', ru: 'дверь', uk: 'двері' } },
    { id: 'garderob', bulgarian: 'гардероб', translations: { en: 'wardrobe', fr: 'armoire', ar: 'خزانة ملابس', fa: 'کمد لباس', ru: 'гардероб', uk: 'гардероб' } },
    { id: 'dvustaen', bulgarian: 'двустаен апартамент', translations: { en: 'one-bedroom apartment', fr: 'appartement deux pièces', ar: 'شقة غرفتين', fa: 'آپارتمان دو اتاقه', ru: 'двухкомнатная квартира', uk: 'двокімнатна квартира' } },
    { id: 'divan', bulgarian: 'диван', translations: { en: 'sofa / couch', fr: 'canapé', ar: 'أريكة', fa: 'کاناپه', ru: 'диван', uk: 'диван' } },
    { id: 'do', bulgarian: 'до', translations: { en: 'next to / up to', fr: 'à côté de / jusqu\'à', ar: 'بجانب / حتى', fa: 'کنار / تا', ru: 'рядом / до', uk: 'поряд / до' } },
    { id: 'dush', bulgarian: 'душ', translations: { en: 'shower', fr: 'douche', ar: 'دش', fa: 'دوش', ru: 'душ', uk: 'душ' } },
    { id: 'edinostaen', bulgarian: 'едностаен апартамент', translations: { en: 'studio apartment', fr: 'studio', ar: 'شقة غرفة واحدة', fa: 'آپارتمان یک اتاقه', ru: 'однокомнатная квартира', uk: 'однокімнатна квартира' } },
    { id: 'etazh', bulgarian: 'етаж', translations: { en: 'floor / storey', fr: 'étage', ar: 'طابق', fa: 'طبقه', ru: 'этаж', uk: 'поверх' } },
    { id: 'kilim', bulgarian: 'килим', translations: { en: 'carpet / rug', fr: 'tapis', ar: 'سجادة', fa: 'فرش', ru: 'ковёр', uk: 'килим' } },
    { id: 'kniga', bulgarian: 'книга', translations: { en: 'book', fr: 'livre', ar: 'كتاب', fa: 'کتاب', ru: 'книга', uk: 'книга' } },
    { id: 'kompyutar', bulgarian: 'компютър', translations: { en: 'computer', fr: 'ordinateur', ar: 'حاسوب', fa: 'رایانه', ru: 'компьютер', uk: 'комп\'ютер' } },
    { id: 'koridor', bulgarian: 'коридор', translations: { en: 'hallway / corridor', fr: 'couloir', ar: 'ممر / رواق', fa: 'راهرو', ru: 'коридор', uk: 'коридор' } },
    { id: 'kashta', bulgarian: 'къща', translations: { en: 'house', fr: 'maison', ar: 'بيت / منزل', fa: 'خانه', ru: 'дом', uk: 'будинок' } },
    { id: 'kuhnya', bulgarian: 'кухня', translations: { en: 'kitchen', fr: 'cuisine', ar: 'مطبخ', fa: 'آشپزخانه', ru: 'кухня', uk: 'кухня' } },
    { id: 'lampa', bulgarian: 'лампа', translations: { en: 'lamp', fr: 'lampe', ar: 'مصباح', fa: 'لامپ', ru: 'лампа', uk: 'лампа' } },
    { id: 'leglo', bulgarian: 'легло', translations: { en: 'bed', fr: 'lit', ar: 'سرير', fa: 'تخت', ru: 'кровать', uk: 'ліжко' } },
    { id: 'lyzhica', bulgarian: 'лъжица', translations: { en: 'spoon', fr: 'cuillère', ar: 'ملعقة', fa: 'قاشق', ru: 'ложка', uk: 'ложка' } },
    { id: 'masa', bulgarian: 'маса', translations: { en: 'table', fr: 'table', ar: 'طاولة', fa: 'میز', ru: 'стол', uk: 'стіл' } },
    { id: 'mil', bulgarian: 'мил, мила, мило, мили', translations: { en: 'kind / nice', fr: 'gentil / aimable', ar: 'لطيف', fa: 'مهربان', ru: 'милый / добрый', uk: 'милий / добрий' } },
    { id: 'mivka', bulgarian: 'мивка', translations: { en: 'sink', fr: 'évier / lavabo', ar: 'حوض المطبخ / الحوض', fa: 'سینک', ru: 'раковина', uk: 'раковина' } },
    { id: 'modern', bulgarian: 'модерен, модерна, модерно, модерни', translations: { en: 'modern / contemporary', fr: 'moderne', ar: 'عصري / حديث', fa: 'مدرن', ru: 'современный', uk: 'сучасний' } },
    { id: 'nablizzo', bulgarian: 'наблизо', translations: { en: 'nearby', fr: 'à proximité', ar: 'قريب', fa: 'نزدیک', ru: 'поблизости', uk: 'поряд / неподалік' } },
    { id: 'nad', bulgarian: 'над', translations: { en: 'above / over', fr: 'au-dessus de', ar: 'فوق', fa: 'بالای', ru: 'над', uk: 'над' } },
    { id: 'neobzaveden', bulgarian: 'необзаведен, необзаведена, необзаведено, необзаведени', translations: { en: 'unfurnished', fr: 'non meublé', ar: 'غير مفروش', fa: 'بی‌مبله', ru: 'без мебели', uk: 'без меблів' } },
    { id: 'nozh', bulgarian: 'нож', translations: { en: 'knife', fr: 'couteau', ar: 'سكين', fa: 'چاقو', ru: 'нож', uk: 'ніж' } },
    { id: 'obzaveden', bulgarian: 'обзаведен, обзаведена, обзаведено, обзаведени', translations: { en: 'furnished', fr: 'meublé', ar: 'مفروش', fa: 'مبله', ru: 'меблированный', uk: 'мебльований' } },
    { id: 'peralnya', bulgarian: 'пералня', translations: { en: 'washing machine', fr: 'machine à laver', ar: 'غسالة', fa: 'ماشین لباسشویی', ru: 'стиральная машина', uk: 'пральна машина' } },
    { id: 'pechka', bulgarian: 'печка', translations: { en: 'cooker / stove', fr: 'cuisinière', ar: 'موقد / طباخ', fa: 'اجاق', ru: 'плита', uk: 'плита' } },
    { id: 'pod', bulgarian: 'под', translations: { en: 'under / below', fr: 'sous', ar: 'تحت', fa: 'زیر', ru: 'под', uk: 'під' } },
    { id: 'pod-naem', bulgarian: 'под наем', translations: { en: 'for rent / rental', fr: 'en location', ar: 'للإيجار', fa: 'برای اجاره', ru: 'в аренду / для найма', uk: 'в оренду' } },
    { id: 'prozorec', bulgarian: 'прозорец', translations: { en: 'window', fr: 'fenêtre', ar: 'نافذة', fa: 'پنجره', ru: 'окно', uk: 'вікно' } },
    { id: 'sapun', bulgarian: 'сапун', translations: { en: 'soap', fr: 'savon', ar: 'صابون', fa: 'صابون', ru: 'мыло', uk: 'мило' } },
    { id: 'svetal', bulgarian: 'светъл, светла, светло, светли', translations: { en: 'bright / light', fr: 'lumineux / clair', ar: 'مضيء / فاتح', fa: 'روشن', ru: 'светлый', uk: 'світлий' } },
    { id: 'spalnya', bulgarian: 'спалня', translations: { en: 'bedroom', fr: 'chambre à coucher', ar: 'غرفة نوم', fa: 'اتاق خواب', ru: 'спальня', uk: 'спальня' } },
    { id: 'stol', bulgarian: 'стол', translations: { en: 'chair', fr: 'chaise', ar: 'كرسي', fa: 'صندلی', ru: 'стул', uk: 'стілець' } },
    { id: 'studena-voda', bulgarian: 'студена вода', translations: { en: 'cold water', fr: 'eau froide', ar: 'ماء بارد', fa: 'آب سرد', ru: 'холодная вода', uk: 'холодна вода' } },
    { id: 'sased', bulgarian: 'съсед', translations: { en: 'neighbour', fr: 'voisin', ar: 'جار', fa: 'همسایه', ru: 'сосед', uk: 'сусід' } },
    { id: 'televizor', bulgarian: 'телевизор', translations: { en: 'TV set', fr: 'téléviseur', ar: 'تلفاز', fa: 'تلویزیون', ru: 'телевизор', uk: 'телевізор' } },
    { id: 'tih', bulgarian: 'тих, тиха, тихо, тихи', translations: { en: 'quiet', fr: 'calme / silencieux', ar: 'هادئ', fa: 'آرام', ru: 'тихий', uk: 'тихий' } },
    { id: 'toaletna', bulgarian: 'тоалетна', translations: { en: 'toilet', fr: 'toilettes', ar: 'مرحاض', fa: 'توالت', ru: 'туалет', uk: 'туалет' } },
    { id: 'topla-voda', bulgarian: 'топла вода', translations: { en: 'hot water', fr: 'eau chaude', ar: 'ماء ساخن', fa: 'آب گرم', ru: 'горячая вода', uk: 'гаряча вода' } },
    { id: 'tristaen', bulgarian: 'тристаен апартамент', translations: { en: 'two-bedroom apartment', fr: 'appartement trois pièces', ar: 'شقة ثلاث غرف', fa: 'آپارتمان سه اتاقه', ru: 'трёхкомнатная квартира', uk: 'трикімнатна квартира' } },
    { id: 'hladilnik', bulgarian: 'хладилник', translations: { en: 'fridge', fr: 'réfrigérateur', ar: 'ثلاجة', fa: 'یخچال', ru: 'холодильник', uk: 'холодильник' } },
    { id: 'hol', bulgarian: 'хол', translations: { en: 'living room', fr: 'salon', ar: 'غرفة المعيشة', fa: 'هال / نشیمن', ru: 'гостиная', uk: 'вітальня' } },
    { id: 'cvete', bulgarian: 'цвете', translations: { en: 'flower', fr: 'fleur', ar: 'زهرة', fa: 'گل', ru: 'цветок', uk: 'квітка' } },
    { id: 'chasha', bulgarian: 'чаша', translations: { en: 'cup / glass', fr: 'tasse / verre', ar: 'كوب', fa: 'فنجان / لیوان', ru: 'чашка / стакан', uk: 'чашка / склянка' } },
    { id: 'chiniya', bulgarian: 'чиния', translations: { en: 'plate', fr: 'assiette', ar: 'طبق', fa: 'بشقاب', ru: 'тарелка', uk: 'тарілка' } },
    { id: 'shkaf', bulgarian: 'шкаф', translations: { en: 'cupboard / cabinet', fr: 'placard / armoire', ar: 'خزانة', fa: 'کابینت / گنجه', ru: 'шкаф', uk: 'шафа' } },
    { id: 'blok', bulgarian: 'блок', translations: { en: 'apartment building / block of flats', fr: 'immeuble', ar: 'بناية سكنية', fa: 'آپارتمان / ساختمان', ru: 'многоэтажный дом', uk: 'багатоповерхівка' } },
    { id: 'kvartira', bulgarian: 'апартамент', translations: { en: 'apartment / flat', fr: 'appartement', ar: 'شقة', fa: 'آپارتمان', ru: 'квартира', uk: 'квартира' } },
    { id: 'kvartal', bulgarian: 'квартал', translations: { en: 'neighbourhood / district', fr: 'quartier', ar: 'حي', fa: 'محله', ru: 'район / квартал', uk: 'район / квартал' } },
    { id: 'park', bulgarian: 'парк', translations: { en: 'park', fr: 'parc', ar: 'حديقة عامة', fa: 'پارک', ru: 'парк', uk: 'парк' } },
    { id: 'gradina', bulgarian: 'градина', translations: { en: 'garden', fr: 'jardin', ar: 'حديقة', fa: 'باغ', ru: 'сад / огород', uk: 'сад / город' } },
  ],

  culturalNotes: [
    {
      id: 'l09-culture-01',
      title: {
        bg: 'Жилища в България',
        en: 'Housing in Bulgaria',
        fr: 'Le logement en Bulgarie',
        ar: 'المساكن في بلغاريا',
        fa: 'مسکن در بلغارستان',
        ru: 'Жильё в Болгарии',
        uk: 'Житло в Болгарії',
      },
      content: {
        bg: 'Около 97 процента от българите притежават собствено жилище. Това е един от най-високите показатели в Европа.',
        en: 'Around 97 percent of Bulgarians own their own home. This is one of the highest rates in Europe.',
        fr: 'Environ 97 % des Bulgares sont propriétaires de leur logement. C\'est l\'un des taux les plus élevés en Europe.',
        ar: 'يمتلك نحو 97 بالمئة من البلغاريين مساكنهم الخاصة. وهذا يُعدّ من أعلى المعدلات في أوروبا.',
        fa: 'حدود ۹۷ درصد از بلغاری‌ها صاحب خانه هستند. این یکی از بالاترین نرخ‌ها در اروپاست.',
        ru: 'Около 97 процентов болгар владеют собственным жильём. Это один из самых высоких показателей в Европе.',
        uk: 'Близько 97 відсотків болгар мають власне житло. Це один із найвищих показників у Європі.',
      },
    },
    {
      id: 'l09-culture-02',
      title: {
        bg: 'Жилища в селата и градовете',
        en: 'Housing in villages and cities',
        fr: 'Logements dans les villages et les villes',
        ar: 'المساكن في القرى والمدن',
        fa: 'مسکن در روستاها و شهرها',
        ru: 'Жилища в сёлах и городах',
        uk: 'Житло в селах і містах',
      },
      content: {
        bg: 'В селата и малките градове хората живеят в едно- или двуетажни тухлени къщи. В големите градове повечето хора живеят в малки апартаменти с един или два стаи.',
        en: 'In villages and small towns, people live in one- or two-storey brick houses. In cities, most people live in small apartments with one or two bedrooms.',
        fr: 'Dans les villages et les petites villes, les gens vivent dans des maisons en briques d\'un ou deux étages. Dans les grandes villes, la plupart des gens vivent dans de petits appartements d\'une ou deux pièces.',
        ar: 'في القرى والمدن الصغيرة، يعيش الناس في منازل طابق أو طابقين من الطوب. في المدن الكبيرة، يعيش معظم الناس في شقق صغيرة بغرفة أو غرفتين.',
        fa: 'در روستاها و شهرهای کوچک، مردم در خانه‌های آجری یک یا دو طبقه زندگی می‌کنند. در شهرهای بزرگ، اکثر مردم در آپارتمان‌های کوچک با یک یا دو اتاق زندگی می‌کنند.',
        ru: 'В сёлах и маленьких городах люди живут в одно- или двухэтажных кирпичных домах. В больших городах большинство людей живут в небольших квартирах с одной или двумя комнатами.',
        uk: 'У селах і маленьких містах люди живуть у одно- або двоповерхових цегляних будинках. У великих містах більшість людей живуть у маленьких квартирах з однією або двома кімнатами.',
      },
    },
    {
      id: 'l09-culture-03',
      title: {
        bg: 'Наемане на жилище',
        en: 'Renting a home',
        fr: 'Louer un logement',
        ar: 'استئجار مسكن',
        fa: 'اجاره مسکن',
        ru: 'Аренда жилья',
        uk: 'Оренда житла',
      },
      content: {
        bg: 'В България има много апартаменти под наем. Обявите за наем можете да намерите в интернет или на агенции за недвижими имоти. Апартаментите могат да бъдат обзаведени или необзаведени.',
        en: 'There are many apartments for rent in Bulgaria. You can find rental listings on the internet or through real estate agencies. Apartments can be furnished or unfurnished.',
        fr: 'Il y a beaucoup d\'appartements à louer en Bulgarie. Vous pouvez trouver des annonces de location sur Internet ou dans des agences immobilières. Les appartements peuvent être meublés ou non meublés.',
        ar: 'يوجد في بلغاريا كثير من الشقق المعروضة للإيجار. يمكنك العثور على إعلانات الإيجار عبر الإنترنت أو من خلال وكالات العقارات. قد تكون الشقق مفروشة أو غير مفروشة.',
        fa: 'در بلغارستان آپارتمان‌های اجاره‌ای زیادی وجود دارد. می‌توانید آگهی‌های اجاره را در اینترنت یا از طریق بنگاه‌های معاملات ملکی پیدا کنید. آپارتمان‌ها می‌توانند مبله یا بی‌مبله باشند.',
        ru: 'В Болгарии много квартир в аренду. Объявления об аренде можно найти в интернете или через агентства недвижимости. Квартиры бывают меблированные и без мебели.',
        uk: 'У Болгарії є багато квартир в оренду. Оголошення про оренду можна знайти в інтернеті або через агентства нерухомості. Квартири бувають мебльовані та без меблів.',
      },
    },
  ],

  grammarReference: [],
};
