import type { LessonContent } from '@/content/types';

export const content: LessonContent = {
  introduction: `В този урок ще научите как да поздравявате за различни празници на български. Ще се запознаете с минало свършено време — АХ, ЯХ и НАХ групи, минало на глаголите „съм" и „имам", и изразите „исках/трябваше/не можах да". Ще прочетете текстове за Коледа, Великден, 24 май и Кирил и Методий.`,

  sections: [],

  dialogues: [],

  vocabulary: [
    { id: 'l06-bezalkoholni',    bulgarian: 'безалкохолни напитки' },
    { id: 'l06-boyadisvam',      bulgarian: 'боядисвам' },
    { id: 'l06-bukva',           bulgarian: 'буква' },
    { id: 'l06-buket',           bulgarian: 'букет' },
    { id: 'l06-badni-vecher',    bulgarian: 'Бъдни вечер' },
    { id: 'l06-velik',           bulgarian: 'велик' },
    { id: 'l06-velikden',        bulgarian: 'Великден' },
    { id: 'l06-vchera',          bulgarian: 'вчера' },
    { id: 'l06-valnyvam-se',     bulgarian: 'вълнувам се' },
    { id: 'l06-glagolitsa',      bulgarian: 'глаголица' },
    { id: 'l06-gratski',         bulgarian: 'гръцки' },
    { id: 'l06-da-si-zhiv',      bulgarian: 'Да си жив и здрав!' },
    { id: 'l06-deputat',         bulgarian: 'депутат' },
    { id: 'l06-detski',          bulgarian: 'детски' },
    { id: 'l06-drug',            bulgarian: 'друг' },
    { id: 'l06-dyado-koleda',    bulgarian: 'Дядо Коледа' },
    { id: 'l06-zhelaya',         bulgarian: 'желая' },
    { id: 'l06-zhivot',          bulgarian: 'живот' },
    { id: 'l06-zapalen',         bulgarian: 'запален' },
    { id: 'l06-zarya',           bulgarian: 'заря' },
    { id: 'l06-izpolzvam',       bulgarian: 'използвам' },
    { id: 'l06-imen-den',        bulgarian: 'имен ден' },
    { id: 'l06-isus-hristos',    bulgarian: 'Исус Христос' },
    { id: 'l06-kirilitsa',       bulgarian: 'кирилица' },
    { id: 'l06-kmet',            bulgarian: 'кмет' },
    { id: 'l06-knizhka',         bulgarian: 'книжка' },
    { id: 'l06-kozunak',         bulgarian: 'козунак' },
    { id: 'l06-kolega',          bulgarian: 'колега' },
    { id: 'l06-koleda',          bulgarian: 'Коледа' },
    { id: 'l06-kolenden',        bulgarian: 'коледен' },
    { id: 'l06-kultura',         bulgarian: 'култура' },
    { id: 'l06-kusmet',          bulgarian: 'късмет' },
    { id: 'l06-latinitsa',       bulgarian: 'латиница' },
    { id: 'l06-lek-pat',         bulgarian: 'Лек път!' },
    { id: 'l06-lesen',           bulgarian: 'лесен' },
    { id: 'l06-lyubov',          bulgarian: 'любов' },
    { id: 'l06-martenitsa',      bulgarian: 'мартеница' },
    { id: 'l06-minalo',          bulgarian: 'минал' },
    { id: 'l06-ministar',        bulgarian: 'министър' },
    { id: 'l06-mongoliya',       bulgarian: 'Монголия' },
    { id: 'l06-nadezhda',        bulgarian: 'надежда' },
    { id: 'l06-nadyavam-se',     bulgarian: 'надявам се' },
    { id: 'l06-nastroenie',      bulgarian: 'настроение' },
    { id: 'l06-nash',            bulgarian: 'наш' },
    { id: 'l06-necheten-broy',   bulgarian: 'нечетен брой' },
    { id: 'l06-nova-godina',     bulgarian: 'Нова година' },
    { id: 'l06-obikalyam',       bulgarian: 'обикалям' },
    { id: 'l06-onzi-den',        bulgarian: 'онзи ден' },
    { id: 'l06-oshav',           bulgarian: 'ошав' },
    { id: 'l06-oshte',           bulgarian: 'още' },
    { id: 'l06-pesen',           bulgarian: 'песен' },
    { id: 'l06-pozhelyavam',     bulgarian: 'пожелавам' },
    { id: 'l06-posle',           bulgarian: 'после' },
    { id: 'l06-posten',          bulgarian: 'постен' },
    { id: 'l06-praznik',         bulgarian: 'празник' },
    { id: 'l06-praznuva-se',     bulgarian: 'празнува се' },
    { id: 'l06-prezident',       bulgarian: 'президент' },
    { id: 'l06-prekarvam',       bulgarian: 'прекарвам' },
    { id: 'l06-poleten',         bulgarian: 'пролетен' },
    { id: 'l06-pat',             bulgarian: 'път (пъти)' },
    { id: 'l06-radvam-se',       bulgarian: 'радвам се' },
    { id: 'l06-radost',          bulgarian: 'радост' },
    { id: 'l06-razhdane',        bulgarian: 'раждане' },
    { id: 'l06-razgovaryam',     bulgarian: 'разговарям' },
    { id: 'l06-razlichno',       bulgarian: 'различен' },
    { id: 'l06-rodnini',         bulgarian: 'роднини' },
    { id: 'l06-svetlina',        bulgarian: 'светлина' },
    { id: 'l06-sveshch',         bulgarian: 'свещ' },
    { id: 'l06-simvol',          bulgarian: 'символ' },
    { id: 'l06-slavyanobalgarski', bulgarian: 'славянобългарски' },
    { id: 'l06-snoshti',         bulgarian: 'снощи' },
    { id: 'l06-spomnyam-si',     bulgarian: 'спомням си' },
    { id: 'l06-sazden',          bulgarian: 'създаден' },
    { id: 'l06-syadam',          bulgarian: 'сядам' },
    { id: 'l06-tehen',           bulgarian: 'техен' },
    { id: 'l06-tikva',           bulgarian: 'тиква' },
    { id: 'l06-uvazhavam',       bulgarian: 'уважавам' },
    { id: 'l06-ukrayna',         bulgarian: 'Украйна' },
    { id: 'l06-usmivka',         bulgarian: 'усмивка' },
    { id: 'l06-usmihnat',        bulgarian: 'усмихнат' },
    { id: 'l06-hristiyani',      bulgarian: 'християнин / християни' },
    { id: 'l06-chestit-praznik', bulgarian: 'Честит празник!' },
    { id: 'l06-chistota',        bulgarian: 'чистота' },
    { id: 'l06-chukame-se',      bulgarian: 'Чукаме се с яйца.' },
    { id: 'l06-sharen',          bulgarian: 'шарен' },
    { id: 'l06-shtastie',        bulgarian: 'щастие' },
    { id: 'l06-yastie',          bulgarian: 'ястие' },
  ],

  culturalNotes: [
    {
      id: 'l06-baba-marta',
      title: {
        bg: '1 март — Баба Марта',
        en: 'March 1st — Baba Marta',
        fr: '1er mars — Baba Marta',
        ar: '1 مارس — بابا مارتا',
        fa: '۱ مارس — بابا مارتا',
        uk: '1 березня — Баба Марта',
        ru: '1 марта — Баба Марта',
      },
      content: {
        bg: 'На 1 март българите се поздравяват „Честита Баба Марта!" и подаряват мартеници — червено-бели конци, вплетени заедно. Мартениците са символ на здраве и щастие. Те се носят на китката или на ревера до момента, в който се види първата щъркел. После мартеницата се завързва на плодно дърво или се поставя под камък, докато се прави желание.',
        en: 'On March 1st Bulgarians greet each other with „Честита Баба Марта!" (Happy Baba Marta!) and give each other мартеници — red and white woolen threads woven together. Martenitsas symbolize health and happiness. They are worn on the wrist or lapel until the first stork is seen. They are then tied to a fruit tree or placed under a stone while making a wish.',
        fr: 'Le 1er mars, les Bulgares se souhaitent « Честита Баба Марта ! » et s\'offrent des мартеници — des fils de laine rouge et blanc tressés ensemble. Les martenitsa symbolisent la santé et le bonheur. On les porte au poignet ou sur le revers jusqu\'à l\'apparition de la première cigogne. On les attache ensuite à un arbre fruitier ou on les place sous une pierre en formulant un vœu.',
        ar: 'في الأول من مارس، يتبادل البلغار تهنئة «Честита Баба Марта!» ويتهادون بالمرتنيتسا — خيوط صوفية حمراء وبيضاء مضفورة معاً. ترمز المرتنيتسا إلى الصحة والسعادة. تُلبس في المعصم أو على طية الجاكيت حتى رؤية أول لقلق. بعد ذلك تُربط على شجرة مثمرة أو تُوضع تحت حجر مع إبداء أمنية.',
        fa: 'در اول مارس، بلغاری‌ها با «Честита Баба Марта!» به یکدیگر تبریک می‌گویند و مارتنیتسا — نخ‌های قرمز و سفید بافته‌شده — به هم هدیه می‌دهند. مارتنیتسا نماد سلامتی و خوشبختی است. آن را روی مچ یا یقه می‌پوشند تا اولین لک‌لک دیده شود؛ سپس به درخت میوه‌ای می‌بندند یا زیر سنگی می‌گذارند و آرزو می‌کنند.',
        uk: 'Першого березня болгари вітають один одного «Честита Баба Марта!» і дарують мартениці — переплетені червоно-білі нитки. Мартениці символізують здоров\'я та щастя. Їх носять на зап\'ястку або петлиці до появи першого лелеки. Потім мартеницю прив\'язують до фруктового дерева або кладуть під камінь із загаданим бажанням.',
        ru: 'Первого марта болгары поздравляют друг друга «Честита Баба Марта!» и дарят мартеницы — переплетённые красно-белые нити. Мартеницы символизируют здоровье и счастье. Их носят на запястье или петлице до появления первого аиста. Затем мартеницу привязывают к плодовому дереву или кладут под камень, загадав желание.',
      },
    },
    {
      id: 'l06-3-mart',
      title: {
        bg: '3 март — Ден на Освобождението',
        en: 'March 3rd — Liberation Day',
        fr: '3 mars — Jour de la Libération',
        ar: '3 مارس — يوم التحرير',
        fa: '۳ مارس — روز آزادی',
        uk: '3 березня — День звільнення',
        ru: '3 марта — День Освобождения',
      },
      content: {
        bg: '3 март е най-важният национален празник на България. На този ден през 1878 г. е подписан Санстефанският мирен договор, с който завършва Руско-турската война и България е освободена от близо 500-годишно османско владичество. На Шипка се събират хиляди хора — президентът, министри, депутати и кметове — за да отдадат почит пред паметника на свободата.',
        en: 'March 3rd is the most important national holiday of Bulgaria. On this day in 1878 the Treaty of San Stefano was signed, ending the Russo-Turkish War and liberating Bulgaria after nearly 500 years of Ottoman rule. Thousands of people gather at Shipka — including the president, ministers, MPs and mayors — to pay tribute at the Monument of Freedom.',
        fr: 'Le 3 mars est la fête nationale la plus importante de Bulgarie. Ce jour-là, en 1878, le traité de San Stefano fut signé, mettant fin à la guerre russo-turque et libérant la Bulgarie après près de 500 ans de domination ottomane. Des milliers de personnes se réunissent à Chipka — dont le président, des ministres, des députés et des maires — pour rendre hommage au monument de la Liberté.',
        ar: '3 مارس هو أهم عيد وطني في بلغاريا. في هذا اليوم عام 1878 وُقِّعت معاهدة سان ستيفانو، التي أنهت الحرب الروسية-العثمانية وحررت بلغاريا بعد ما يقارب 500 عام من الحكم العثماني. يتجمع الآلاف في شيبكا — من بينهم الرئيس والوزراء والنواب والعمداء — لتأدية التحية أمام نصب الحرية.',
        fa: 'سوم مارس مهم‌ترین جشن ملی بلغارستان است. در این روز در سال ۱۸۷۸ معاهده سان استفانو امضا شد و جنگ روسیه-عثمانی پایان یافت و بلغارستان پس از تقریباً ۵۰۰ سال حکومت عثمانی آزاد شد. هزاران نفر در شیپکا گرد می‌آیند — از جمله رئیس‌جمهور، وزرا، نمایندگان و شهرداران — تا در برابر بنای آزادی ادای احترام کنند.',
        uk: '3 березня — найважливіше національне свято Болгарії. Цього дня 1878 року було підписано Сан-Стефанський мирний договір, що завершив Російсько-турецьку війну і звільнив Болгарію після майже 500 років османського панування. Тисячі людей збираються на Шипці — серед них президент, міністри, депутати та мери — щоб вшанувати пам\'ять біля пам\'ятника Свободи.',
        ru: '3 марта — важнейший национальный праздник Болгарии. В этот день в 1878 году был подписан Сан-Стефанский мирный договор, завершивший Русско-турецкую войну и освободивший Болгарию от почти 500-летнего османского владычества. Тысячи людей собираются на Шипке — президент, министры, депутаты и мэры — чтобы отдать дань уважения у памятника Свободы.',
      },
    },
    {
      id: 'l06-8-mart',
      title: {
        bg: '8 март — Международен ден на жената',
        en: 'March 8th — International Women\'s Day',
        fr: '8 mars — Journée internationale de la femme',
        ar: '8 مارس — اليوم الدولي للمرأة',
        fa: '۸ مارس — روز جهانی زن',
        uk: '8 березня — Міжнародний день жінки',
        ru: '8 марта — Международный день женщины',
      },
      content: {
        bg: 'На 8 март мъжете изразяват своята любов и уважение към жените около тях. Подаряват цветя, шоколади и подаръци. В България денят е изгубил политическото си значение и се е превърнал в приятен повод да се поздравят майки, съпруги, сестри, колежки и приятелки.',
        en: 'On March 8th men express their love and respect for the women around them. They give flowers, chocolates and gifts. In Bulgaria the day has lost its political meaning and has become a pleasant occasion to congratulate mothers, wives, sisters, colleagues and friends.',
        fr: 'Le 8 mars, les hommes expriment leur amour et leur respect envers les femmes qui les entourent. Ils offrent des fleurs, des chocolats et des cadeaux. En Bulgarie, la journée a perdu sa signification politique et est devenue une belle occasion de féliciter mères, épouses, sœurs, collègues et amies.',
        ar: 'في 8 مارس يُعبِّر الرجال عن محبتهم واحترامهم للنساء من حولهم، فيقدمون الزهور والشوكولاتة والهدايا. في بلغاريا فقد اليوم طابعه السياسي وأصبح مناسبة سعيدة للتهنئة بالأمهات والزوجات والأخوات والزميلات والصديقات.',
        fa: 'در ۸ مارس، مردان محبت و احترام خود را به زنان اطرافشان ابراز می‌کنند و گل، شکلات و هدیه می‌دهند. در بلغارستان این روز معنای سیاسی خود را از دست داده و به مناسبتی خوشایند برای تبریک به مادران، همسران، خواهران، همکاران و دوستان زن تبدیل شده است.',
        uk: '8 березня чоловіки висловлюють свою любов і повагу до жінок навколо них. Вони дарують квіти, шоколад і подарунки. У Болгарії день втратив своє політичне значення і став приємним приводом привітати матерів, дружин, сестер, колег і подруг.',
        ru: '8 марта мужчины выражают любовь и уважение к окружающим их женщинам. Они дарят цветы, шоколад и подарки. В Болгарии день утратил политическое значение и превратился в приятный повод поздравить матерей, жён, сестёр, коллег и подруг.',
      },
    },
    {
      id: 'l06-velikden',
      title: {
        bg: 'Великден',
        en: 'Easter',
        fr: 'Pâques',
        ar: 'عيد الفصح',
        fa: 'عید پاک',
        uk: 'Великдень',
        ru: 'Пасха',
      },
      content: {
        bg: 'Великден е един от най-важните православни празници. В четвъртък преди Великден боядисваме яйца, а в събота правим козунаци. В събота в полунощ православните християни обикалят храма три пъти със запалени свещи. В неделя се чукаме с яйца — тов, чието яйце остане цяло, ще има здраве и късмет. Ядем козунаци и печено агнешко.',
        en: 'Easter is one of the most important Orthodox holidays. On Thursday before Easter we dye eggs, and on Saturday we make kozunak (sweet bread). On Saturday at midnight Orthodox Christians walk three times around the church holding lit candles. On Sunday we tap eggs against each other — the person whose egg stays unbroken will have health and luck all year. We eat kozunak and roast lamb.',
        fr: 'Pâques est l\'une des fêtes orthodoxes les plus importantes. Le jeudi avant Pâques, on teint les œufs, et le samedi on prépare le kozunak (pain brioché sucré). Le samedi à minuit, les chrétiens orthodoxes font trois fois le tour de l\'église en tenant des bougies allumées. Le dimanche, on se frappe les œufs — celui dont l\'œuf reste entier aura santé et bonheur. On mange du kozunak et de l\'agneau rôti.',
        ar: 'عيد الفصح من أهم الأعياد الأرثوذكسية. يوم الخميس قبل عيد الفصح نصبغ البيض، وفي السبت نصنع الكوزوناك (خبز حلو). في منتصف الليل يوم السبت يدور المسيحيون الأرثوذكس ثلاث مرات حول الكنيسة وبأيديهم شموع مشتعلة. في يوم الأحد يتقارع الجميع بالبيض — من يبقى بيضه سليماً سينعم بالصحة والحظ طوال العام. يأكلون الكوزوناك والخروف المشوي.',
        fa: 'عید پاک یکی از مهم‌ترین اعیاد ارتدوکس است. پنجشنبه قبل از عید پاک تخم‌مرغ رنگ می‌کنیم و شنبه کوزوناک (نان شیرین) می‌پزیم. شنبه شب نیمه‌شب، مسیحیان ارتدوکس با شمع‌های روشن سه بار دور کلیسا می‌گردند. یکشنبه تخم‌مرغ‌ها را به هم می‌کوبیم — کسی که تخم‌مرغش سالم بماند سال آینده سلامت و خوش‌اقبال خواهد بود. کوزوناک و بره بریان می‌خوریم.',
        uk: 'Великдень — одне з найважливіших православних свят. У четвер перед Великоднем фарбуємо яйця, а в суботу печемо козунак (солодкий хліб). У суботу опівночі православні християни тричі обходять храм зі запаленими свічками. У неділю б\'ємося яйцями — той, чиє яйце залишиться цілим, матиме здоров\'я і щастя. Їмо козунак і смажене ягня.',
        ru: 'Пасха — один из важнейших православных праздников. В четверг перед Пасхой красим яйца, а в субботу готовим козунак (сладкий хлеб). В субботу в полночь православные христиане трижды обходят храм с зажжёнными свечами. В воскресенье бьёмся яйцами — у кого яйцо останется целым, того ждут здоровье и удача. Едим козунак и жареного ягнёнка.',
      },
    },
    {
      id: 'l06-24-may',
      title: {
        bg: '24 май — Ден на буквите',
        en: 'May 24th — Day of the Slavic Alphabet',
        fr: '24 mai — Journée de l\'alphabet slave',
        ar: '24 مايو — يوم الحروف البلغارية',
        fa: '۲۴ مه — روز الفبای اسلاوی',
        uk: '24 травня — День слов\'янської писемності',
        ru: '24 мая — День славянской письменности',
      },
      content: {
        bg: 'На 24 май България чества Деня на българската азбука, просвета и култура и на славянската книжовност. Целият ден е посветен на братята Кирил и Методий, създатели на глаголицата. По-късно е създадена кирилицата, на която пишем днес. В целия град училищата са украсени с цветя и портрети на светите братя. Учениците и учителите пеят песни пред паметниците им.',
        en: 'On May 24th Bulgaria celebrates the Day of Bulgarian Education and Culture and the Slavic Alphabet. The whole day is dedicated to the brothers St Cyril and St Methodius, who created the Glagolitic alphabet. Later the Cyrillic alphabet (which we use today) was created. Throughout the country schools are decorated with flowers and portraits of the holy brothers. Students and teachers sing songs in front of their monuments.',
        fr: 'Le 24 mai, la Bulgarie célèbre la Journée de l\'éducation, de la culture bulgare et de l\'alphabet slave. Toute la journée est dédiée aux frères saints Cyrille et Méthode, créateurs de l\'alphabet glagolitique. Plus tard fut créé l\'alphabet cyrillique, que nous utilisons aujourd\'hui. Dans tout le pays, les écoles sont décorées de fleurs et de portraits des saints frères. Les élèves et les enseignants chantent des chansons devant leurs monuments.',
        ar: 'في 24 مايو، تحتفل بلغاريا بيوم التعليم والثقافة البلغارية والأبجدية السلافية. يُهدى اليوم كله للأخوَين القديسَين كيريل وميتودي، واضعَي الأبجدية الغلاغوليتية. لاحقاً ظهرت الأبجدية السيريلية التي نكتب بها اليوم. في أرجاء البلاد تزين المدارس بالزهور وصور الأخوَين القديسَين، ويُغني الطلاب والمعلمون أمام نُصُبهم.',
        fa: 'در ۲۴ مه بلغارستان روز آموزش، فرهنگ بلغاری و الفبای اسلاوی را جشن می‌گیرد. تمام روز به برادران مقدس کیریل و متودی، سازندگان الفبای گلاگولیتیک، اختصاص دارد. بعداً الفبای سیریلیک که امروز از آن استفاده می‌کنیم ساخته شد. در سراسر کشور مدارس با گل و تصویر برادران مقدس آراسته می‌شوند و دانش‌آموزان و معلمان جلوی بنای یادبودشان آواز می‌خوانند.',
        uk: '24 травня Болгарія відзначає День болгарської освіти і культури та слов\'янської писемності. Весь день присвячений братам свв. Кирилу і Мефодію, творцям глаголиці. Пізніше була створена кирилиця, якою ми пишемо сьогодні. По всій країні школи прикрашені квітами і портретами святих братів. Учні та вчителі співають пісні перед їхніми пам\'ятниками.',
        ru: '24 мая Болгария отмечает День болгарского просвещения, культуры и славянской письменности. Весь день посвящён братьям свв. Кириллу и Мефодию, создателям глаголицы. Позже была создана кириллица, которой мы пишем сегодня. По всей стране школы украшены цветами и портретами святых братьев. Ученики и учителя поют песни у их памятников.',
      },
    },
    {
      id: 'l06-koleda',
      title: {
        bg: 'Коледа',
        en: 'Christmas',
        fr: 'Noël',
        ar: 'عيد الميلاد',
        fa: 'کریسمس',
        uk: 'Різдво',
        ru: 'Рождество',
      },
      content: {
        bg: 'България празнува Коледа на 25 декември. На 24-и вечерта се празнува Бъдни вечер — семейната вечеря с нечетен брой постни ястия (7, 9 или 11): сарми с ориз, боб, ошав, баница с тиква, мед, лук, чесън, орехи. На Бъдни вечер коледарите обикалят из селото с песни. На 25-и сутринта хората ходят на църква, а децата получават подаръци от Дядо Коледа.',
        en: 'Bulgaria celebrates Christmas on December 25th. On Christmas Eve (Бъдни вечер, December 24th) families gather for a festive dinner with an odd number of meatless dishes (7, 9 or 11): stuffed cabbage with rice, beans, dried fruit compote, pumpkin pastry, honey, garlic, onions and walnuts. On Christmas Eve carolers (коледари) go from house to house singing. On Christmas morning people go to church and children receive gifts from Father Christmas.',
        fr: 'La Bulgarie célèbre Noël le 25 décembre. Le réveillon de Noël (Бъдни вечер, 24 décembre) réunit la famille autour d\'un dîner avec un nombre impair de plats végétariens (7, 9 ou 11) : feuilles de chou farcies au riz, haricots, compote de fruits secs, pâtisserie à la citrouille, miel, ail, oignons et noix. Le soir du réveillon, des carolers (коледари) chantent de maison en maison. Le matin de Noël, les gens vont à l\'église et les enfants reçoivent des cadeaux du Père Noël.',
        ar: 'تحتفل بلغاريا بعيد الميلاد في 25 ديسمبر. في ليلة رأس السنة الميلادية (Бъдни вечер، 24 ديسمبر) تجتمع الأسرة على مائدة تضم عدداً فردياً من الأطباق النباتية (7 أو 9 أو 11): سارمي بالأرز، وفول، وكومبوت الفاكهة المجففة، وفطير اليقطين، والعسل، والثوم، والبصل، والجوز. في ليلة عيد الميلاد يجوب المنشدون (коледари) القرى مغنين. في صباح عيد الميلاد يذهب الناس إلى الكنيسة ويتلقى الأطفال هدايا من بابا نويل.',
        fa: 'بلغارستان کریسمس را در ۲۵ دسامبر جشن می‌گیرد. شب کریسمس (Бъдни вечер، ۲۴ دسامبر) خانواده دور هم جمع می‌شوند و شامی با تعداد فرد غذاهای گیاهی (۷، ۹ یا ۱۱) می‌خورند: کلم بلغاری برگی با برنج، لوبیا، کمپوت میوه خشک، شیرینی کدو، عسل، سیر، پیاز و گردو. شب کریسمس گروه‌های سرودخوان (коледари) خانه به خانه آواز می‌خوانند. صبح روز کریسمس مردم به کلیسا می‌روند و بچه‌ها از بابانوئل هدیه می‌گیرند.',
        uk: 'Болгарія святкує Різдво 25 грудня. На Святий вечір (Бъдни вечер, 24 грудня) сім\'я збирається на вечерю з непарною кількістю пісних страв (7, 9 або 11): голубці з рисом, квасоля, компот із сухофруктів, баниця з гарбузом, мед, часник, цибуля, горіхи. У Святий вечір колядники (коледари) ходять від хати до хати зі співами. Різдвяного ранку люди йдуть до церкви, а діти отримують подарунки від Діда Мороза.',
        ru: 'Болгария отмечает Рождество 25 декабря. Рождественским сочельником (Бъдни вечер, 24 декабря) семья собирается на вечернее застолье с нечётным количеством постных блюд (7, 9 или 11): голубцы с рисом, фасоль, компот из сухофруктов, баница с тыквой, мёд, чеснок, лук, орехи. В сочельник колядники (коледари) ходят от дома к дому с песнями. Рождественским утром люди идут в церковь, а дети получают подарки от Деда Мороза.',
      },
    },
  ],
};
