import type { LessonContent } from '@/content/types';

export const content: LessonContent = {
  introduction:
    'В десети урок ще научите думи за транспорт и пътуване. Ще купувате билети, ще четете разписания и ще питате за автобуси и влакове. Ще се запознаете и с центъра на София.',

  sections: [],

  dialogues: [
    {
      id: 'l10-content-dialozi-1',
      speakers: [
        { text: '– Добър ден, колко струва един билет?' },
        { text: '– Хартиен билет за едно пътуване е 1,10 евро.' },
        { text: '– Два билета, моля.' },
      ],
    },
    {
      id: 'l10-content-dialozi-2',
      speakers: [
        { text: '– Един билет за Варна за 12:00 часà. Колко струва?' },
        { text: '– 23 евро.' },
        { text: '– Откъде тръгва автобусът?' },
        { text: '– От сектор 3.' },
        { text: '– Благодаря.' },
      ],
    },
    {
      id: 'l10-content-dialozi-3',
      speakers: [
        { text: '– Как пътуваш от НДК до жк „Люлин"?' },
        { text: '– С метро. На метростанция „Сердика" сменям линия 1 с линия 2.' },
        { text: '– А има ли тролей?' },
        { text: '– Да, има. Но с метрото е по-бързо.' },
      ],
    },
    {
      id: 'l10-content-dialozi-4',
      speakers: [
        { text: '– Добър ден. Може ли до гарата?' },
        { text: '– Да, заповядайте.' },
        { text: '– Колко струва?' },
        { text: '– 5,50 евро.' },
        { text: '– Може ли касова бележка?' },
        { text: '– Да, разбира се.' },
      ],
    },
  ],

  vocabulary: [
    { id: 'avtobus', bulgarian: 'автобус', translations: { en: 'bus', fr: 'bus / autobus', ar: 'حافلة', fa: 'اتوبوس', ru: 'автобус', uk: 'автобус' } },
    { id: 'avtogara', bulgarian: 'автогара', translations: { en: 'bus station', fr: 'gare routière', ar: 'محطة الحافلات', fa: 'پایانه اتوبوس', ru: 'автовокзал', uk: 'автовокзал' } },
    { id: 'bagazh', bulgarian: 'багаж', translations: { en: 'luggage / baggage', fr: 'bagage', ar: 'أمتعة', fa: 'بار / چمدان', ru: 'багаж', uk: 'багаж' } },
    { id: 'bilet', bulgarian: 'билет', translations: { en: 'ticket', fr: 'billet', ar: 'تذكرة', fa: 'بلیط', ru: 'билет', uk: 'квиток' } },
    { id: 'byarz-vlak', bulgarian: 'бърз влак', translations: { en: 'fast train / express', fr: 'train rapide', ar: 'قطار سريع', fa: 'قطار سریع', ru: 'скорый поезд', uk: 'швидкий потяг' } },
    { id: 'vagon', bulgarian: 'вагон', translations: { en: 'train car / carriage', fr: 'wagon', ar: 'عربة قطار', fa: 'واگن', ru: 'вагон', uk: 'вагон' } },
    { id: 'vzimam', bulgarian: 'взимам, -аш', translations: { en: 'to take', fr: 'prendre', ar: 'يأخذ', fa: 'گرفتن', ru: 'брать', uk: 'брати' } },
    { id: 'vlak', bulgarian: 'влак', translations: { en: 'train', fr: 'train', ar: 'قطار', fa: 'قطار', ru: 'поезд', uk: 'потяг' } },
    { id: 'vrashtam-se', bulgarian: 'връщам се, -аш', translations: { en: 'to come back / go back', fr: 'rentrer / revenir', ar: 'يعود', fa: 'برگشتن', ru: 'возвращаться', uk: 'повертатися' } },
    { id: 'gara', bulgarian: 'гара', translations: { en: 'train station', fr: 'gare', ar: 'محطة القطار', fa: 'ایستگاه قطار', ru: 'вокзал', uk: 'вокзал' } },
    { id: 'ekspres', bulgarian: 'експрес', translations: { en: 'express train', fr: 'express', ar: 'قطار إكسبريس', fa: 'قطار اکسپرس', ru: 'экспресс', uk: 'експрес' } },
    { id: 'zakusnenie', bulgarian: 'закъснение', translations: { en: 'delay', fr: 'retard', ar: 'تأخير', fa: 'تأخیر', ru: 'опоздание', uk: 'запізнення' } },
    { id: 'zakusnyavam', bulgarian: 'закъснявам, -аш', translations: { en: 'to be late / delayed', fr: 'être en retard', ar: 'يتأخر', fa: 'تأخیر کردن', ru: 'опаздывать', uk: 'запізнюватися' } },
    { id: 'zaminavam', bulgarian: 'заминавам, -аш', translations: { en: 'to depart / leave', fr: 'partir', ar: 'يغادر', fa: 'عزیمت کردن', ru: 'отправляться', uk: 'від\'їжджати' } },
    { id: 'karta', bulgarian: 'карта', translations: { en: 'travel card / map', fr: 'carte', ar: 'بطاقة تنقل / خريطة', fa: 'بلیط فصلی / نقشه', ru: 'проездной / карта', uk: 'проїзний квиток / карта' } },
    { id: 'kasa-bileti', bulgarian: 'каса за билети', translations: { en: 'ticket office', fr: 'guichet', ar: 'شباك التذاكر', fa: 'باجه بلیط', ru: 'касса', uk: 'каса' } },
    { id: 'kasova-belezhka', bulgarian: 'касова бележка', translations: { en: 'receipt', fr: 'reçu', ar: 'فاتورة / إيصال', fa: 'رسید', ru: 'чек', uk: 'чек' } },
    { id: 'katedrala', bulgarian: 'катедрала', translations: { en: 'cathedral', fr: 'cathédrale', ar: 'كاتدرائية', fa: 'کلیسای جامع', ru: 'собор / кафедральный собор', uk: 'собор / катедральний храм' } },
    { id: 'kola', bulgarian: 'кола', translations: { en: 'car', fr: 'voiture', ar: 'سيارة', fa: 'ماشین / اتومبیل', ru: 'машина / автомобиль', uk: 'машина / автомобіль' } },
    { id: 'kolovoz', bulgarian: 'коловоз', translations: { en: 'platform / track', fr: 'quai / voie', ar: 'رصيف القطار', fa: 'سکوی قطار', ru: 'платформа / путь', uk: 'платформа / колія' } },
    { id: 'korab', bulgarian: 'кораб', translations: { en: 'ship / boat', fr: 'bateau / navire', ar: 'سفينة', fa: 'کشتی', ru: 'корабль', uk: 'корабель' } },
    { id: 'kufar', bulgarian: 'куфар', translations: { en: 'suitcase', fr: 'valise', ar: 'حقيبة سفر', fa: 'چمدان', ru: 'чемодан', uk: 'валіза' } },
    { id: 'liniya', bulgarian: 'линия', translations: { en: 'line (metro/bus)', fr: 'ligne', ar: 'خط', fa: 'خط', ru: 'линия', uk: 'лінія' } },
    { id: 'metro', bulgarian: 'метро', translations: { en: 'metro / underground', fr: 'métro', ar: 'مترو', fa: 'مترو', ru: 'метро', uk: 'метро' } },
    { id: 'metrostanciya', bulgarian: 'метростанция', translations: { en: 'metro station', fr: 'station de métro', ar: 'محطة مترو', fa: 'ایستگاه مترو', ru: 'станция метро', uk: 'станція метро' } },
    { id: 'myasto', bulgarian: 'място', translations: { en: 'seat / place', fr: 'place / siège', ar: 'مقعد / مكان', fa: 'جایگاه / مکان', ru: 'место', uk: 'місце' } },
    { id: 'pristavam', bulgarian: 'пристигам, -аш', translations: { en: 'to arrive', fr: 'arriver', ar: 'يصل', fa: 'رسیدن', ru: 'прибывать', uk: 'прибувати' } },
    { id: 'putnicheski-vlak', bulgarian: 'пътнически влак', translations: { en: 'passenger train', fr: 'train de voyageurs', ar: 'قطار ركاب', fa: 'قطار مسافربری', ru: 'пассажирский поезд', uk: 'пасажирський потяг' } },
    { id: 'patuvam', bulgarian: 'пътувам, -аш', translations: { en: 'to travel', fr: 'voyager', ar: 'يسافر', fa: 'سفر کردن', ru: 'путешествовать / ехать', uk: 'подорожувати / їхати' } },
    { id: 'patuvane', bulgarian: 'пътуване', translations: { en: 'journey / trip', fr: 'voyage / trajet', ar: 'رحلة / سفر', fa: 'سفر / مسافرت', ru: 'путешествие / поездка', uk: 'подорож / поїздка' } },
    { id: 'razpisanie', bulgarian: 'разписание', translations: { en: 'timetable / schedule', fr: 'horaire', ar: 'جدول مواعيد', fa: 'جدول زمانی', ru: 'расписание', uk: 'розклад' } },
    { id: 'ranica', bulgarian: 'раница', translations: { en: 'backpack / rucksack', fr: 'sac à dos', ar: 'حقيبة ظهر', fa: 'کوله پشتی', ru: 'рюкзак', uk: 'рюкзак' } },
    { id: 'samolet', bulgarian: 'самолет', translations: { en: 'plane / aircraft', fr: 'avion', ar: 'طائرة', fa: 'هواپیما', ru: 'самолёт', uk: 'літак' } },
    { id: 'sektor', bulgarian: 'сектор', translations: { en: 'gate / sector (bus station)', fr: 'secteur / quai', ar: 'بوابة / قطاع', fa: 'درگاه / بخش', ru: 'сектор', uk: 'сектор / виїзд' } },
    { id: 'spiram', bulgarian: 'спирам, -аш', translations: { en: 'to stop', fr: 's\'arrêter', ar: 'يتوقف', fa: 'متوقف شدن', ru: 'останавливаться', uk: 'зупинятися' } },
    { id: 'spirka', bulgarian: 'спирка', translations: { en: '(bus/tram) stop', fr: 'arrêt', ar: 'موقف', fa: 'ایستگاه', ru: 'остановка', uk: 'зупинка' } },
    { id: 'taksi', bulgarian: 'такси', translations: { en: 'taxi / cab', fr: 'taxi', ar: 'سيارة أجرة', fa: 'تاکسی', ru: 'такси', uk: 'таксі' } },
    { id: 'tramvay', bulgarian: 'трамвай', translations: { en: 'tram / streetcar', fr: 'tramway', ar: 'ترام', fa: 'تراموا', ru: 'трамвай', uk: 'трамвай' } },
    { id: 'troley', bulgarian: 'тролей', translations: { en: 'trolleybus', fr: 'trolleybus', ar: 'حافلة كهربائية', fa: 'اتوبوس برقی', ru: 'троллейбус', uk: 'тролейбус' } },
    { id: 'trugvam', bulgarian: 'тръгвам, -аш', translations: { en: 'to leave / set off', fr: 'partir / s\'en aller', ar: 'يتحرك / ينطلق', fa: 'حرکت کردن / عزیمت کردن', ru: 'отправляться / уходить', uk: 'вирушати / відправлятися' } },
    { id: 'chakalniya', bulgarian: 'чакалня', translations: { en: 'waiting room', fr: 'salle d\'attente', ar: 'غرفة انتظار', fa: 'اتاق انتظار', ru: 'зал ожидания', uk: 'зал очікування' } },
    { id: 'chakam', bulgarian: 'чакам, -аш', translations: { en: 'to wait', fr: 'attendre', ar: 'ينتظر', fa: 'صبر کردن / منتظر ماندن', ru: 'ждать / ожидать', uk: 'чекати' } },
    { id: 'shofyor', bulgarian: 'шофьор', translations: { en: 'driver', fr: 'chauffeur / conducteur', ar: 'سائق', fa: 'راننده', ru: 'водитель / шофёр', uk: 'водій' } },
    { id: 'ndk', bulgarian: 'НДК', translations: { en: 'National Palace of Culture', fr: 'Palais national de la culture', ar: 'قصر الثقافة الوطني', fa: 'کاخ ملی فرهنگ', ru: 'Национальный дворец культуры', uk: 'Національний палац культури' } },
    { id: 'pametnik', bulgarian: 'паметник', translations: { en: 'monument / memorial', fr: 'monument', ar: 'نصب تذكاري', fa: 'بنای یادبود', ru: 'памятник', uk: 'пам\'ятник' } },
    { id: 'ploshtad', bulgarian: 'площад', translations: { en: 'square / plaza', fr: 'place', ar: 'ميدان', fa: 'میدان', ru: 'площадь', uk: 'площа' } },
  ],

  culturalNotes: [
    {
      id: 'l10-culture-01',
      title: {
        bg: 'Пушенето е забранено!',
        en: 'No smoking!',
        fr: 'Défense de fumer !',
        ar: 'التدخين ممنوع!',
        fa: 'سیگار کشیدن ممنوع!',
        ru: 'Курение запрещено!',
        uk: 'Куріння заборонено!',
      },
      content: {
        bg: 'В обществения транспорт и всички обществени закрити места в България пушенето е строго забранено. Глобите са значителни.',
        en: 'Smoking is strictly forbidden in public transportation and all public indoor areas in Bulgaria. Fines are significant.',
        fr: 'Fumer est strictement interdit dans les transports en commun et tous les lieux publics couverts en Bulgarie. Les amendes sont importantes.',
        ar: 'يُحظر التدخين تمامًا في وسائل النقل العام وجميع الأماكن العامة المغلقة في بلغاريا. والغرامات كبيرة.',
        fa: 'سیگار کشیدن در حمل‌ونقل عمومی و تمام مکان‌های سرپوشیده عمومی در بلغارستان کاملاً ممنوع است. جریمه‌ها قابل توجه هستند.',
        ru: 'Курение в общественном транспорте и всех закрытых общественных местах в Болгарии строго запрещено. Штрафы значительные.',
        uk: 'Куріння в громадському транспорті та всіх закритих громадських місцях Болгарії суворо заборонено. Штрафи значні.',
      },
    },
    {
      id: 'l10-culture-02',
      title: {
        bg: 'Автобусът — най-удобният транспорт',
        en: 'Bus — the most convenient transport',
        fr: 'Le bus — le transport le plus pratique',
        ar: 'الحافلة — وسيلة النقل الأكثر ملاءمة',
        fa: 'اتوبوس — مناسب‌ترین وسیله حمل‌ونقل',
        ru: 'Автобус — самый удобный транспорт',
        uk: 'Автобус — найзручніший транспорт',
      },
      content: {
        bg: 'Автобусът е най-бързият начин за пътуване из страната. Автобуси има до всеки по-голям град. Билетите се купуват от водача или от касата на автогарата. Някои автобуси имат тоалетни, но спират на всеки 3–4 часа на бензиностанция или голяма автогара.',
        en: 'The bus is the fastest way to travel around the country. Buses run to every major city. Tickets are bought from the driver or at the bus station ticket office. Some buses have toilets, but they stop every 3–4 hours at a petrol station or large bus station.',
        fr: 'Le bus est le moyen le plus rapide de voyager dans le pays. Il y a des bus vers toutes les grandes villes. Les billets s\'achètent auprès du conducteur ou à la caisse de la gare routière. Certains bus ont des toilettes, mais s\'arrêtent toutes les 3 à 4 heures dans une station-service ou une grande gare.',
        ar: 'الحافلة هي أسرع وسيلة للسفر عبر البلاد. تصل الحافلات إلى كل مدينة كبيرة. تُشترى التذاكر من السائق أو من شباك التذاكر في المحطة. بعض الحافلات بها مراحيض، لكنها تتوقف كل ثلاث أو أربع ساعات في محطة وقود أو محطة حافلات كبيرة.',
        fa: 'اتوبوس سریع‌ترین راه برای سفر در کشور است. اتوبوس به هر شهر بزرگی می‌رود. بلیط‌ها از راننده یا از باجه فروش بلیط پایانه خریداری می‌شوند. برخی اتوبوس‌ها توالت دارند، اما هر سه تا چهار ساعت در یک پمپ‌بنزین یا پایانه بزرگ توقف می‌کنند.',
        ru: 'Автобус — самый быстрый способ путешествовать по стране. Автобусы ходят до каждого крупного города. Билеты покупают у водителя или в кассе автовокзала. Некоторые автобусы имеют туалеты, но останавливаются каждые 3–4 часа на заправке или крупном автовокзале.',
        uk: 'Автобус — найшвидший спосіб подорожувати країною. Автобуси ходять до кожного великого міста. Квитки купують у водія або в касі автовокзалу. Деякі автобуси мають туалети, але зупиняються кожні 3–4 години на заправці або великому автовокзалі.',
      },
    },
    {
      id: 'l10-culture-03',
      title: {
        bg: 'Такситата в България',
        en: 'Taxis in Bulgaria',
        fr: 'Les taxis en Bulgarie',
        ar: 'سيارات الأجرة في بلغاريا',
        fa: 'تاکسی در بلغارستان',
        ru: 'Такси в Болгарии',
        uk: 'Таксі в Болгарії',
      },
      content: {
        bg: 'Тарифите на таксита са стандартизирани в по-големите градове. Но внимавайте — има измамнически таксита, които имитират лога на известни компании, но таксуват много по-скъпо. По-безопасно е да поръчате такси по телефона или с приложение.',
        en: 'Taxi tariffs are standardised in the major cities. But beware — there are fraudulent taxis that mimic the logos of well-known companies but charge much higher rates. It is safer to order a taxi by phone or via an app.',
        fr: 'Les tarifs des taxis sont normalisés dans les grandes villes. Mais attention — il existe des taxis frauduleux qui imitent les logos de compagnies connues mais facturent bien plus cher. Il est plus sûr de commander un taxi par téléphone ou via une application.',
        ar: 'تعريفات التاكسي موحدة في المدن الكبرى. لكن احذروا — هناك سيارات أجرة احتيالية تقلّد شعارات الشركات المعروفة وتتقاضى أسعارًا أعلى بكثير. الأأمن أن تطلب سيارة الأجرة عبر الهاتف أو التطبيق.',
        fa: 'نرخ‌های تاکسی در شهرهای بزرگ استاندارد است. اما مراقب باشید — تاکسی‌های کلاهبردار وجود دارند که لوگوی شرکت‌های معروف را تقلید می‌کنند اما نرخ‌های بسیار بالاتری می‌گیرند. بهتر است از طریق تلفن یا اپلیکیشن تاکسی سفارش دهید.',
        ru: 'Тарифы на такси стандартизированы в крупных городах. Но будьте осторожны — есть мошеннические такси, которые имитируют логотипы известных компаний, но берут намного дороже. Безопаснее заказывать такси по телефону или через приложение.',
        uk: 'Тарифи на таксі стандартизовані у великих містах. Але будьте обережні — є шахрайські таксі, які імітують логотипи відомих компаній, але беруть набагато дорожче. Безпечніше замовляти таксі телефоном або через додаток.',
      },
    },
    {
      id: 'l10-culture-04',
      title: {
        bg: 'Международни летища в България',
        en: 'International airports in Bulgaria',
        fr: 'Aéroports internationaux en Bulgarie',
        ar: 'المطارات الدولية في بلغاريا',
        fa: 'فرودگاه‌های بین‌المللی بلغارستان',
        ru: 'Международные аэропорты Болгарии',
        uk: 'Міжнародні аеропорти Болгарії',
      },
      content: {
        bg: 'В България има четири международни летища: в София, Варна, Бургас и Пловдив. Летище Варна и летище Бургас работят предимно с чартърни полети. Летище София е най-натовареното.',
        en: 'Bulgaria has four international airports: in Sofia, Varna, Burgas and Plovdiv. Varna and Burgas airports operate mainly charter flights. Sofia airport is the busiest.',
        fr: 'La Bulgarie possède quatre aéroports internationaux : à Sofia, Varna, Bourgas et Plovdiv. Les aéroports de Varna et Bourgas opèrent principalement des vols charters. L\'aéroport de Sofia est le plus fréquenté.',
        ar: 'تمتلك بلغاريا أربعة مطارات دولية: في صوفيا وفارنا وبورغاس وبلوفديف. مطارا فارنا وبورغاس يعملان أساسًا بالرحلات المستأجرة. مطار صوفيا هو الأكثر ازدحامًا.',
        fa: 'بلغارستان چهار فرودگاه بین‌المللی دارد: در سوفیا، وارنا، بورگاس و پلووديو. فرودگاه‌های وارنا و بورگاس عمدتاً با پروازهای چارتری فعالیت می‌کنند. فرودگاه سوفیا پرترافیک‌ترین فرودگاه است.',
        ru: 'В Болгарии четыре международных аэропорта: в Софии, Варне, Бургасе и Пловдиве. Аэропорты Варны и Бургаса работают преимущественно с чартерными рейсами. Аэропорт Софии — самый загруженный.',
        uk: 'У Болгарії чотири міжнародних аеропорти: у Софії, Варні, Бургасі та Пловдиві. Аеропорти Варни та Бургаса працюють переважно з чартерними рейсами. Аеропорт Софії — найзавантаженіший.',
      },
    },
  ],

  grammarReference: [],
};
