import type { LessonContent } from '@/content/types';

export const content: LessonContent = {
  introduction:
    'В петия урок ще научите думи за града и селото: улици, сгради, институции и природа. Ще можете да казвате къде живеете, да четете и давате адрес, да питате за посока и да използвате предлози за място. Ще повторите и разширите членуването на съществителните и големите числа.',

  sections: [],

  dialogues: [
    {
      id: 'l05-dialozi-1',
      speakers: [
        { name: 'А', text: 'Къде живееш?' },
        { name: 'Б', text: 'Аз живея в София, на улица „Гурко“ 25.' },
      ],
    },
    {
      id: 'l05-dialozi-1-b',
      speakers: [
        { name: 'А', text: 'Къде живее Мария?' },
        {
          name: 'Б',
          text: 'Тя живее в София, в квартал „Младост“ 2, блок 243, вход А, етаж 2, апартамент 5.',
        },
      ],
    },
    {
      id: 'l05-dialozi-1-v',
      speakers: [
        { name: 'А', text: 'Къде живее Абдул?' },
        { name: 'Б', text: 'Той живее в жк „Люлин“ 7, бл. 704, вх. Б, ет. 4, ап. 12.' },
      ],
    },
    {
      id: 'l05-dialozi-1-g',
      speakers: [
        { name: 'А', text: 'Къде живеят Петър и Дора?' },
        { name: 'Б', text: 'Те живеят в Перник.' },
        { name: 'А', text: 'В къща или в блок?' },
        { name: 'Б', text: 'В блок, но имат къща на село.' },
      ],
    },
    {
      id: 'l05-dialozi-2-a',
      speakers: [
        { name: 'А', text: 'Извинете, къде е общината?' },
        { name: 'Б', text: 'Вървете направо, след банката завийте наляво.' },
        { name: 'А', text: 'А супермаркет „Била“?' },
        { name: 'Б', text: 'Вървете направо и след 20 метра завийте надясно.' },
      ],
    },
  ],

  vocabulary: [
    { id: 'adres', bulgarian: 'адрес', translations: { en: 'address', fr: 'adresse', ar: 'عنوان', fa: 'نشانی', ru: 'адрес', uk: 'адреса' } },
    { id: 'amfiteatar', bulgarian: 'амфитеатър', translations: { en: 'amphitheatre', fr: 'amphithéâtre', ar: 'مدرج', fa: 'آمفی‌تئاتر', ru: 'амфитеатр', uk: 'амфітеатр' } },
    { id: 'apartament', bulgarian: 'апартамент', translations: { en: 'apartment', fr: 'appartement', ar: 'شقة', fa: 'آپارتمان', ru: 'квартира', uk: 'квартира' } },
    { id: 'apteka', bulgarian: 'аптека', translations: { en: 'pharmacy', fr: 'pharmacie', ar: 'صيدلية', fa: 'داروخانه', ru: 'аптека', uk: 'аптека' } },
    { id: 'baba', bulgarian: 'баба', translations: { en: 'grandmother', fr: 'grand-mère', ar: 'جدة', fa: 'مادربزرگ', ru: 'бабушка', uk: 'бабуся' } },
    { id: 'banka', bulgarian: 'банка', translations: { en: 'bank', fr: 'banque', ar: 'بنك', fa: 'بانک', ru: 'банк', uk: 'банк' } },
    { id: 'blok', bulgarian: 'блок', translations: { en: 'apartment building', fr: 'immeuble', ar: 'عمارة سكنية', fa: 'بلوک', ru: 'дом (блок)', uk: 'будинок (блок)' } },
    { id: 'biblioteka', bulgarian: 'библиотека', translations: { en: 'library', fr: 'bibliothèque', ar: 'مكتبة', fa: 'کتابخانه', ru: 'библиотека', uk: 'бібліотека' } },
    { id: 'bolnitsa', bulgarian: 'болница', translations: { en: 'hospital', fr: 'hôpital', ar: 'مستشفى', fa: 'بیمارستان', ru: 'больница', uk: 'лікарня' } },
    { id: 'bulevard', bulgarian: 'булевард', translations: { en: 'boulevard', fr: 'boulevard', ar: 'شارع رئيسي', fa: 'بلوار', ru: 'бульвар', uk: 'бульвар' } },
    { id: 'blizo-do', bulgarian: 'близо до', translations: { en: 'close to', fr: 'près de', ar: 'قريب من', fa: 'نزدیک', ru: 'близко к', uk: 'близько до' } },
    { id: 'v-uv', bulgarian: 'в, във', translations: { en: 'in', fr: 'dans / en', ar: 'في', fa: 'در', ru: 'в', uk: 'у / в' } },
    { id: 'vhod', bulgarian: 'вход', translations: { en: 'entrance', fr: 'entrée', ar: 'مدخل', fa: 'ورودی', ru: 'подъезд', uk: 'під’їзд' } },
    { id: 'grad', bulgarian: 'град', translations: { en: 'town, city', fr: 'ville', ar: 'مدينة', fa: 'شهر', ru: 'город', uk: 'місто' } },
    { id: 'gora', bulgarian: 'гора', translations: { en: 'forest', fr: 'forêt', ar: 'غابة', fa: 'جنگل', ru: 'лес', uk: 'ліс' } },
    { id: 'daleche-ot', bulgarian: 'далече от', translations: { en: 'far from', fr: 'loin de', ar: 'بعيد عن', fa: 'دور از', ru: 'далеко от', uk: 'далеко від' } },
    { id: 'dete', bulgarian: 'дете, деца', translations: { en: 'child, children', fr: 'enfant, enfants', ar: 'طفل، أطفال', fa: 'بچه، بچه‌ها', ru: 'ребёнок, дети', uk: 'дитина, діти' } },
    { id: 'detska-gradina', bulgarian: 'детска градина', translations: { en: 'kindergarten', fr: 'jardin d’enfants', ar: 'روضة أطفال', fa: 'مهدکود', ru: 'детский сад', uk: 'дитячий садок' } },
    { id: 'detska-ploshtadka', bulgarian: 'детска площадка', translations: { en: 'playground', fr: 'aire de jeux', ar: 'ملعب أطفال', fa: 'زمین بازی', ru: 'детская площадка', uk: 'майданчик' } },
    { id: 'dzhamiya', bulgarian: 'джамия', translations: { en: 'mosque', fr: 'mosquée', ar: 'مسجد', fa: 'مسجد', ru: 'мечеть', uk: 'мечеть' } },
    { id: 'do', bulgarian: 'до', translations: { en: 'next to', fr: 'à côté de', ar: 'بجانب', fa: 'کنار', ru: 'у / возле', uk: 'біля' } },
    { id: 'dyado', bulgarian: 'дядо', translations: { en: 'grandfather', fr: 'grand-père', ar: 'جد', fa: 'پدربزرگ', ru: 'дедушка', uk: 'дідусь' } },
    { id: 'etag', bulgarian: 'етаж', translations: { en: 'floor', fr: 'étage', ar: 'طابق', fa: 'طبقه', ru: 'этаж', uk: 'поверх' } },
    { id: 'zhiveya', bulgarian: 'живея', translations: { en: 'to live', fr: 'vivre / habiter', ar: 'عاش / يعيش', fa: 'زندگی کردن', ru: 'жить', uk: 'жити' } },
    { id: 'zad', bulgarian: 'зад', translations: { en: 'behind', fr: 'derrière', ar: 'خلف', fa: 'پشت', ru: 'за', uk: 'за' } },
    { id: 'zavivam', bulgarian: 'завивам / завий / завийте', translations: { en: 'to turn', fr: 'tourner', ar: 'اتجه', fa: 'پیچیدن', ru: 'повернуть', uk: 'повернути' } },
    { id: 'ime', bulgarian: 'име', translations: { en: 'name', fr: 'nom', ar: 'اسم', fa: 'نام', ru: 'имя', uk: 'ім’я' } },
    { id: 'kafe', bulgarian: 'кафе', translations: { en: 'café', fr: 'café', ar: 'مقهى', fa: 'کافه', ru: 'кафе', uk: 'кафе' } },
    { id: 'kvartal', bulgarian: 'квартал', translations: { en: 'district', fr: 'quartier', ar: 'حي', fa: 'محله', ru: 'район', uk: 'квартал' } },
    { id: 'kino', bulgarian: 'кино', translations: { en: 'cinema', fr: 'cinéma', ar: 'سينما', fa: 'سینما', ru: 'кино', uk: 'кінотеатр' } },
    { id: 'krepost', bulgarian: 'крепост', translations: { en: 'fortress', fr: 'forteresse', ar: 'قلعة', fa: 'دژ', ru: 'крепость', uk: 'фортеця' } },
    { id: 'kashta', bulgarian: 'къща', translations: { en: 'house', fr: 'maison', ar: 'منزل', fa: 'خانه', ru: 'дом', uk: 'будинок' } },
    { id: 'magazin', bulgarian: 'магазин', translations: { en: 'shop', fr: 'magasin', ar: 'متجر', fa: 'مغازه', ru: 'магазин', uk: 'магазин' } },
    { id: 'mezhdu', bulgarian: 'между', translations: { en: 'between', fr: 'entre', ar: 'بين', fa: 'بین', ru: 'между', uk: 'між' } },
    { id: 'metro', bulgarian: 'метро', translations: { en: 'metro', fr: 'métro', ar: 'مترو', fa: 'مترو', ru: 'метро', uk: 'метро' } },
    { id: 'mol', bulgarian: 'мол', translations: { en: 'shopping mall', fr: 'centre commercial', ar: 'مول', fa: 'مرکز خرید', ru: 'торговый центр', uk: 'торговий центр' } },
    { id: 'more', bulgarian: 'море', translations: { en: 'sea', fr: 'mer', ar: 'بحر', fa: 'دریا', ru: 'море', uk: 'море' } },
    { id: 'most', bulgarian: 'мост', translations: { en: 'bridge', fr: 'pont', ar: 'جسر', fa: 'پل', ru: 'мост', uk: 'міст' } },
    { id: 'muzei', bulgarian: 'музей', translations: { en: 'museum', fr: 'musée', ar: 'متحف', fa: 'موزه', ru: 'музей', uk: 'музей' } },
    { id: 'na', bulgarian: 'на', translations: { en: 'on, at', fr: 'sur / à', ar: 'على / في', fa: 'روی / در', ru: 'на', uk: 'на' } },
    { id: 'nadyasno', bulgarian: 'надясно', translations: { en: 'to the right', fr: 'à droite', ar: 'إلى اليمين', fa: 'به راست', ru: 'направо', uk: 'праворуч' } },
    { id: 'nalyavo', bulgarian: 'наляво', translations: { en: 'to the left', fr: 'à gauche', ar: 'إلى اليسار', fa: 'به چپ', ru: 'налево', uk: 'ліворуч' } },
    { id: 'napravo', bulgarian: 'направо', translations: { en: 'straight on', fr: 'tout droit', ar: 'مستقيماً', fa: 'راست مستقیم', ru: 'прямо', uk: 'прямо' } },
    { id: 'nomer', bulgarian: 'номер', translations: { en: 'number', fr: 'numéro', ar: 'رقم', fa: 'شماره', ru: 'номер', uk: 'номер' } },
    { id: 'obshtina', bulgarian: 'община', translations: { en: 'municipality', fr: 'mairie / municipalité', ar: 'بلدية', fa: 'شهرداری', ru: 'община', uk: 'громада' } },
    { id: 'pazar', bulgarian: 'пазар', translations: { en: 'market', fr: 'marché', ar: 'سوق', fa: 'بازار', ru: 'рынок', uk: 'ринок' } },
    { id: 'pametnik', bulgarian: 'паметник', translations: { en: 'monument', fr: 'monument', ar: 'نصب', fa: 'یادمان', ru: 'памятник', uk: 'пам’ятник' } },
    { id: 'park', bulgarian: 'парк', translations: { en: 'park', fr: 'parc', ar: 'حديقة', fa: 'پارک', ru: 'парк', uk: 'парк' } },
    { id: 'plazh', bulgarian: 'плаж', translations: { en: 'beach', fr: 'plage', ar: 'شاطئ', fa: 'ساحل', ru: 'пляж', uk: 'пляж' } },
    { id: 'planina', bulgarian: 'планина', translations: { en: 'mountain', fr: 'montagne', ar: 'جبل', fa: 'کوه', ru: 'гора', uk: 'гора' } },
    { id: 'ploshtad', bulgarian: 'площад', translations: { en: 'square', fr: 'place', ar: 'ساحة', fa: 'میدان', ru: 'площадь', uk: 'площа' } },
    { id: 'pole', bulgarian: 'поле', translations: { en: 'field', fr: 'champ', ar: 'حقل', fa: 'میدان/دشت', ru: 'поле', uk: 'поле' } },
    { id: 'poshta', bulgarian: 'поща', translations: { en: 'post office', fr: 'poste', ar: 'بريد', fa: 'پست', ru: 'почта', uk: 'пошта' } },
    { id: 'pred', bulgarian: 'пред', translations: { en: 'in front of', fr: 'devant', ar: 'أمام', fa: 'جلو', ru: 'перед', uk: 'перед' } },
    { id: 'reka', bulgarian: 'река', translations: { en: 'river', fr: 'rivière', ar: 'نهر', fa: 'رودخانه', ru: 'река', uk: 'річка' } },
    { id: 'restorant', bulgarian: 'ресторант', translations: { en: 'restaurant', fr: 'restaurant', ar: 'مطعم', fa: 'رستوران', ru: 'ресторан', uk: 'ресторан' } },
    { id: 'rumuniya', bulgarian: 'Румъния', translations: { en: 'Romania', fr: 'Roumanie', ar: 'رومانيا', fa: 'رومانی', ru: 'Румыния', uk: 'Румунія' } },
    { id: 'sgrada', bulgarian: 'сграда', translations: { en: 'building', fr: 'bâtiment', ar: 'مبنى', fa: 'ساختمان', ru: 'здание', uk: 'будівля' } },
    { id: 'selo', bulgarian: 'село', translations: { en: 'village', fr: 'village', ar: 'قرية', fa: 'روستا', ru: 'село', uk: 'село' } },
    { id: 'sled', bulgarian: 'след', translations: { en: 'after', fr: 'après', ar: 'بعد', fa: 'بعد از', ru: 'после', uk: 'після' } },
    { id: 'sreshtu', bulgarian: 'срещу', translations: { en: 'opposite', fr: 'en face de', ar: 'مقابل', fa: 'روبرو', ru: 'напротив', uk: 'напроти' } },
    { id: 'star', bulgarian: 'стар, стара, старо, стари', translations: { en: 'old', fr: 'vieux / vieille', ar: 'قديم', fa: 'قدیمی', ru: 'старый', uk: 'старий' } },
    { id: 'stolitsa', bulgarian: 'столица', translations: { en: 'capital', fr: 'capitale', ar: 'عاصمة', fa: 'پایتخت', ru: 'столица', uk: 'столиця' } },
    { id: 'supermarket', bulgarian: 'супермаркет, супер', translations: { en: 'supermarket', fr: 'supermarché', ar: 'سوبرماركت', fa: 'سوپرمارکت', ru: 'супермаркет', uk: 'супермаркет' } },
    { id: 'teatar', bulgarian: 'театър', translations: { en: 'theatre', fr: 'théâtre', ar: 'مسرح', fa: 'تئاتر', ru: 'театр', uk: 'театр' } },
    { id: 'telefon', bulgarian: 'телефон', translations: { en: 'phone', fr: 'téléphone', ar: 'هاتف', fa: 'تلفن', ru: 'телефон', uk: 'телефон' } },
    { id: 'tramvai', bulgarian: 'трамвай', translations: { en: 'tram', fr: 'tramway', ar: 'ترام', fa: 'تراموا', ru: 'трамвай', uk: 'трамвай' } },
    { id: 'turist', bulgarian: 'турист', translations: { en: 'tourist', fr: 'touriste', ar: 'سائح', fa: 'گردشگر', ru: 'турист', uk: 'турист' } },
    { id: 'ulitsa', bulgarian: 'улица', translations: { en: 'street', fr: 'rue', ar: 'شارع', fa: 'خیابان', ru: 'улица', uk: 'вулиця' } },
    { id: 'universitet', bulgarian: 'университет', translations: { en: 'university', fr: 'université', ar: 'جامعة', fa: 'دانشگاه', ru: 'университет', uk: 'університет' } },
    { id: 'uchilishte', bulgarian: 'училище', translations: { en: 'school', fr: 'école', ar: 'مدرسة', fa: 'مدرسه', ru: 'школа', uk: 'школа' } },
    { id: 'uchitel-bg', bulgarian: 'учител по български език', translations: { en: 'Bulgarian language teacher', fr: 'professeur de bulgare', ar: 'معلّم لغة بلغارية', fa: 'معلم زبان بلغاری', ru: 'учитель болгарского языка', uk: 'вчитель болгарської мови' } },
    { id: 'hora', bulgarian: 'хора', translations: { en: 'people', fr: 'gens / personnes', ar: 'ناس', fa: 'مردم', ru: 'люди', uk: 'люди' } },
    { id: 'hotel', bulgarian: 'хотел', translations: { en: 'hotel', fr: 'hôtel', ar: 'فندق', fa: 'هتل', ru: 'отель', uk: 'готель' } },
    { id: 'tsentar', bulgarian: 'център', translations: { en: 'centre', fr: 'centre', ar: 'مركز', fa: 'مرکز', ru: 'центр', uk: 'центр' } },
    { id: 'tsarkva', bulgarian: 'църква', translations: { en: 'church', fr: 'église', ar: 'كنيسة', fa: 'کلیسا', ru: 'церковь', uk: 'церква' } },
    { id: 'dushi', bulgarian: 'души', translations: { en: 'people (with numbers)', fr: 'personnes (avec un nombre)', ar: 'أشخاص (مع عدد)', fa: 'نفر (با عدد)', ru: 'души (с числом)', uk: 'душі (зі числом)' } },
    { id: 'chovek', bulgarian: 'човек', translations: { en: 'person', fr: 'personne', ar: 'شخص', fa: 'شخص', ru: 'человек', uk: 'людина' } },
    { id: 'khilyada', bulgarian: 'хиляда', translations: { en: 'thousand', fr: 'mille', ar: 'ألف', fa: 'هزار', ru: 'тысяча', uk: 'тисяча' } },
    { id: 'milion', bulgarian: 'милион', translations: { en: 'million', fr: 'million', ar: 'مليون', fa: 'میلیون', ru: 'миллион', uk: 'мільйон' } },
  ],

  culturalNotes: [
    {
      id: 'l05-culture-01',
      title: {
        bg: 'Улици, ориентиране, спешни номера',
        en: 'Street names, finding your way, emergency numbers',
        fr: 'Noms de rues, s’orienter, numéros d’urgence',
        ar: 'أسماء الشوارع، الاتجاه، أرقام الطوارئ',
        fa: 'نام خیابان‌ها، پیدا کردن آدرس، شماره‌های اضطراری',
        ru: 'Названия улиц, ориентация, экстренные номера',
        uk: 'Назви вулиць, орієнтування, екстрені номери',
      },
      content: {
        bg: 'След 1989 г. много улици, свързани с комунистическото минало, са преименувани. Хората понякога не знаят новите имена и често използват старите. Табелите на улици понякога липсват — питайте за забележителности, когато ви дават адрес. Най-големите градове в България са София, Пловдив, Варна, Бургас, Русе, Стара Загора, Плевен. Общоевропейският номер 112 за всички спешни обаждания работи навсякъде в страната. Ако по някаква причина не можете да се свържете с 112: 166 — полиция, 150 — линейка, 160 — пожарна.',
        en: 'After 1989, many street names linked to the communist past were changed. People do not always know the new names and often use the old ones. Street signs are sometimes missing — ask for landmarks when given an address. The biggest cities in Bulgaria are Sofia, Plovdiv, Varna, Burgas, Ruse, Stara Zagora, and Pleven. The pan-European emergency number 112 works across the country. If you cannot reach 112: 166 — police, 150 — ambulance, 160 — fire brigade.',
        fr: 'Après 1989, de nombreuses rues liées au passé communiste ont été renommées. Les gens ne connaissent pas toujours les nouveaux noms et utilisent souvent les anciens. Les panneaux de rue manquent parfois — demandez des repères quand on vous donne une adresse. Les plus grandes villes de Bulgarie sont Sofia, Plovdiv, Varna, Burgas, Ruse, Stara Zagora et Pleven. Le numéro d’urgence européen 112 fonctionne partout. Si vous ne pouvez pas joindre le 112 : 166 — police, 150 — ambulance, 160 — pompiers.',
        ar: 'بعد عام 1989، غُيّرت أسماء شوارع كثيرة مرتبطة بالماضي الشيوعي. لا يعرف الناس دائماً الأسماء الجديدة وغالباً ما يستخدمون القديمة. تختفي لافتات الشوارع أحياناً — اسألوا عن معالم عندما يُعطَون عنواناً. أكبر المدن في بلغاريا هي صوفيا، بلوفديف، فارنا، بورغاس، روزه، ستارا زاغورا، بلفن. الرقم الأوروبي الموحّد 112 لكل مكالمات الطوارئ يعمل في كل مكان. إذا تعذّر الاتصال بـ 112: 166 — شرطة، 150 — إسعاف، 160 — إطفاء.',
        fa: 'پس از ۱۹۸۹، نام بسیاری از خیابان‌های مرتبط با گذشتهٔ کمونیستی عوض شد. مردم همیشه نام‌های جدید را نمی‌دانند و اغلب نام قدیمی را به کار می‌برند. تابلوهای خیابان گاهی نیست — هنگام گرفتن آدرس از نشانه‌ها بپرسید. بزرگ‌ترین شهرهای بلغارستان صوفیه، پلوودیف، وارنا، بورگاس، روسه، استارا زاگورا و پلوون هستند. شمارهٔ اضطراری اروپایی ۱۱۲ در همه جا کار می‌کند. اگر به ۱۱۲ وصل نشدید: ۱۶۶ — پلیس، ۱۵۰ — آمبولانس، ۱۶۰ — آتش‌نشانی.',
        ru: 'После 1989 года многие улицы, связанные с коммунистическим прошлым, были переименованы. Люди не всегда знают новые названия и часто используют старые. Указатели иногда отсутствуют — спрашивайте ориентиры, когда вам называют адрес. Крупнейшие города Болгарии — София, Пловдив, Варна, Бургас, Русе, Стара-Загора, Плевен. Общеевропейский номер 112 экстренных служб действует по всей стране. Если не удаётся дозвониться до 112: 166 — полиция, 150 — скорая, 160 — пожарные.',
        uk: 'Після 1989 багато вулиць, пов’язаних із комуністичним минулим, перейменували. Люди не завжди знають нові назви й часто вживають старі. Іноді бракує табличок — питайте про орієнтири, коли вам дають адресу. Найбільші міста Болгарії — Софія, Пловдив, Варна, Бургас, Русе, Стара Загора, Плевен. Європейський номер екстрених викликів 112 працює скрізь. Якщо не вдається додзвонитися до 112: 166 — поліція, 150 — швидка, 160 — пожежна.',
      },
    },
  ],

  grammarReference: [
    {
      id: 'l05-gr-zhiveya',
      title: {
        bg: 'Глагол ЖИВЕЯ (сегашно време)',
        en: 'The verb ЖИВЕЯ (present tense)',
        fr: 'Le verbe ЖИВЕЯ (présent)',
        ar: 'فعل ЖИВЕЯ (المضارع)',
        fa: 'فعل ЖИВЕЯ (زمان حال)',
        ru: 'Глагол ЖИВЕЯ (настоящее время)',
        uk: 'Дієслово ЖИВЕЯ (теперішній час)',
      },
      content: {
        bg: 'Аз живея, ти живееш, той/тя/то живее, ние живеем, вие живеете, те живеят.\nПример: Иван живее в София, на улица „Янтра“ 5.',
        en: 'Аз живея — I live, ти живееш — you live (sg.), той/тя/то живее — he/she/it lives, ние живеем — we live, вие живеете — you live (pl./formal), те живеят — they live.\nExample: Иван живее в София, на улица „Янтра“ 5.',
        fr: 'Аз живея — je vis, ти живееш — tu vis, той/тя/то живее — il/elle vit, ние живеем — nous vivons, вие живеете — vous vivez, те живеят — ils/elles vivent.\nExemple : Иван живее в София, на улица „Янтра“ 5.',
        ar: 'Аз живея — أعيش، ти живееш — تعيش، той/тя/то живее — يعيش/تعيش، ние живеем — نعيش، вие живеете — تعيشون، те живеят — يعيشون.\nمثال: Иван живее в София, на улица „Янтра“ 5.',
        fa: 'Аз живه‌یا — من زندگی می‌کنم، ти живееш — تو زندگی می‌کنی، و غیره.\nمثال: Иван живее в София, на улица „Янтра“ 5.',
        ru: 'Спряжение настоящего времени: аз живея, ты живеешь, он/она/оно живее, мы живеем, вы живеете, они живеют.\nПример: Иван живее в София, на улица „Янтра“ 5.',
        uk: 'Аз живея — я живу, ти живееш — ти живеш, той/тя/то живее — він/вона/воно живе, ние живеем — ми живемо, вие живеете — ви живете, те живеят — вони живуть.\nПриклад: Иван живее в София, на улица „Янтра“ 5.',
      },
    },
    {
      id: 'l05-gr-chlenuvane-ed',
      title: {
        bg: 'Членуване — единствено число',
        en: 'Definite article — singular',
        fr: 'Article défini — singulier',
        ar: 'أداة التعريف — المفرد',
        fa: 'تعریف — مفرد',
        ru: 'Определённый член — единственное число',
        uk: 'Визначеність — однина',
      },
      content: {
        bg: 'М.р. група А: пазар, център, площад, град, парк + -ът / -а. М.р. група Б: учител, ден + -ят / -я. Ж.р.: банка, улица, поща, аптека, учителка + -та. Ср.р.: кафе, училище, яйце, масло, село + -то.\nПример: Площадът е в центъра.',
        en: 'Masculine group A: -ът / -а. Masculine group B (with vowel before ending): -ят / -я. Feminine: -та. Neuter: -то.\nExample: Площадът е в центъра.',
        fr: 'Masculin groupe A : -ът / -a. Masculin groupe B : -ят / -я. Féminin : -та. Neutre : -то.\nExemple : Площадът е в центъра.',
        ar: 'تصريف معرّف المفرد حسب الجنس والمجموعة كما في جداول الدرس.\nمثال: Площадът е в центъра.',
        fa: 'حروف تعریف مفرد در مذکر (دو گروه)، مونث و خنثی مانند جدول درس.\nمثال: Площадът е в центъра.',
        ru: 'Определённый член в единственном числе: мужской (-ът/-а или -ят/-я), женский (-та), средний (-то).\nПример: Площадът е в центъра.',
        uk: 'Означеність в однині: чол. р. (-ът/-а або -ят/-я), жін. р. (-та), сер. р. (-то).\nПриклад: Площадът е в центъра.',
      },
    },
    {
      id: 'l05-gr-chlenuvane-mn',
      title: {
        bg: 'Членуване — множествено число',
        en: 'Definite article — plural',
        fr: 'Article défini — pluriel',
        ar: 'أداة التعريف — الجمع',
        fa: 'تعریف — جمع',
        ru: 'Определённый член — множественное число',
        uk: 'Визначеність — множина',
      },
      content: {
        bg: 'М.р. и ж.р. мн.ч.: -те (пазарите, банките). Ср.р. мн.ч.: -та (кафетата, училищата).\nПример: Магазините са в центъра.',
        en: 'Masculine and feminine plural definite: -те. Neuter plural definite: -та.\nExample: Магазините са в центъра.',
        fr: 'Pluriel masculin et féminin défini : -те. Pluriel neutre défini : -та.\nExemple : Магазините са в центъра.',
        ar: 'الجمع المعرّف: -те للمذكر والمؤنث و -та للجمع المحايد في أسماء مثل الدرس.\nمثال: Магазините са в центъра.',
        fa: 'جمع معرّف: -те برای مذکر و مونث؛ -تا برای خنثی (مثل درس).\nمثال: Магазините са в центъра.',
        ru: 'Множественное число: муж. и жен. р. — -те, ср. р. — -та.\nПример: Магазините са в центъра.',
        uk: 'Множина: чол. і жін. р. — -те, сер. р. — -та.\nПриклад: Магазините са в центъра.',
      },
    },
    {
      id: 'l05-gr-predlozi',
      title: {
        bg: 'Предлози за място',
        en: 'Prepositions of place',
        fr: 'Prépositions de lieu',
        ar: 'حروف الجر للمكان',
        fa: 'حروف اضافه مکان',
        ru: 'Предлоги места',
        uk: 'Прийменники місця',
      },
      content: {
        bg: 'в, на, до, пред, зад, между, срещу, близо до, далече от.\nПримери: в центъра, на площада, до музея, пред университета, зад аптеката, между аптеката и университета, срещу болницата, близо до хотела, далече от библиотеката.\nВнимание: Аз съм на улицата. / Аз съм на улица „Иван Вазов“.',
        en: 'в (in), на (on/at), до (next to), пред (in front of), зад (behind), между (between), срещу (opposite), близо до (close to), далече от (far from).\nNote: definite vs indefinite street name as in the lesson examples.',
        fr: 'в, на, до, пред, зад, между, срещу, близо до, далече от — voir les exemples du manuel (в центъра, на улицата / на улица „…“).',
        ar: 'в = في/داخل، на = على/في (عنوان)، до = بجانب، пред = أمام، зад = خلف، между = بين، срещу = مقابل، близо до = قريب من، далече от = بعيد عن.\nملاحظة: الفرق بين „на улицата“ و „на улица ‚…‘“ كما في الأمثلة.',
        fa: 'в = در، на = روی/در (نشانی)، до = کنار، пред = جلو، зад = پشت، между = بین، срещу = روبرو، بлизо до = نزدیک، далече от = دور.\nتفاوت «на улицата» و «на улица „…"» را در مثال‌های درس ببینید.',
        ru: 'Предлоги в, на, до, пред, зад, между, срещу, близо до, далече от и примеры из урока.',
        uk: 'Прийменники в, на, до, пред, зад, між, срещу, близо до, далече от та приклади з уроку.',
      },
    },
    {
      id: 'l05-gr-imperativ-posoka',
      title: {
        bg: 'Повелително — посока',
        en: 'Imperatives — directions',
        fr: 'Impératif — directions',
        ar: 'صيغة الأمر — الاتجاهات',
        fa: 'امر — جهت‌ها',
        ru: 'Повелительное наклонение — направления',
        uk: 'Наказовий спосіб — напрямки',
      },
      content: {
        bg: 'Вървете направо! / Върви направо! Завийте наляво! / Завий наляво! Завийте надясно! / Завий надясно! (вие, Вие / ти).',
        en: 'Formal/plural Вървете… / Завийте… vs. informal singular Върви… / Завий… for giving directions.',
        fr: 'Вървете / Върви, Завийте / Завий + направо, наляво, надясно — vouvoiement ou tutoiement.',
        ar: 'صيغ الأمر للجمع/الرسمي (Вървете، Завийте) مقابل المفرد (Върви، Завий).',
        fa: 'Вървете/Завийте برای جمع/رسمی؛ Върви/Завий مفرد دوستانه.',
        ru: 'Повелительная форма для «вие» (Вървете, Завийте) и для «ти» (Върви, Завий).',
        uk: 'Форми наказу для «вие» та «ти» з дієсловами руху.',
      },
    },
    {
      id: 'l05-gr-dushi-hora',
      title: {
        bg: 'Човек, души, хора',
        en: 'Person and people — човек, души, хора',
        fr: 'Personne et nombre de personnes',
        ar: 'الشخص وعدد الأشخاص — човек، души، хора',
        fa: 'فرد و تعداد افراد — човек، души، хора',
        ru: 'Человек и количество людей',
        uk: 'Особа та кількість людей',
      },
      content: {
        bg: 'един човек; десет души (с числа); много / малко хора (общо количество).',
        en: 'One person: човек. With numerals: души. General many/few people: хора.',
        fr: 'Une personne : човек. Avec un nombre : души. Beaucoup / peu de monde en général : хора.',
        ar: 'شخص واحد: човек. مع الرقم: души. للعدد الإجمالي (كثير/قليل): хора.',
        fa: 'یک نفر: човек. با عدد: души. برای مقدار کلی (زیاد/کم): хора.',
        ru: 'Один человек: човек. С числительным: души. Общее количество людей: хора.',
        uk: 'Одна особа: човек. Із числівником: души. Загальна кількість людей: хора.',
      },
    },
    {
      id: 'l05-gr-golemi-chisla',
      title: {
        bg: 'Големи числа (хиляда – милиард)',
        en: 'Large numbers (thousand to billion)',
        fr: 'Grands nombres',
        ar: 'أعداد كبيرة',
        fa: 'اعداد بزرگ',
        ru: 'Большие числа',
        uk: 'Великі числа',
      },
      content: {
        bg: 'хиляда, две хиляди, три хиляди, десет хиляди, сто хиляди; един милион, два милиона; един милиард, два милиарда. Внимание: с числа 2–4 — форма на -а (милиона, милиарда), при «много» — милиони, милиарди.',
        en: 'Thousands, millions, billions as in the lesson table; count forms with numerals vs. general plural.',
        fr: 'Mille, millions, milliards — voir le tableau du cours et la note sur милиона / милиони.',
        ar: 'Алاف وملايين ومليارات كما في جدول الدرس.',
        fa: 'هزار تا میلیارد مطابق جدول؛ توجه به милиона در مقابل милиони.',
        ru: 'Тысячи, миллионы, миллиарды по таблице урока и правило про милиона / милиони.',
        uk: 'Тисячі, мільйони, мільярди за таблицею уроку та правило відмінювання.',
      },
    },
  ],
};
