import type {
  Exercise,
  ImageLabelingExercise,
  IllustratedCardsExercise,
  DropdownMatchExercise,
  SyllableBlocksExercise,
  ReadingTextExercise,
  DialoguesExercise,
  GrammarExamplesExercise,
  WorkbookFillBlankExercise,
  GrammarTableExercise,
  MultipleChoiceExercise,
  TrueFalseExercise,
  DragToColumnsExercise,
  TableFillExercise,
  MatchPairsExercise,
} from '@/content/types';

// Урок 5 — по клиент НЕ се дигитализират упр. 7, 8, 20, 31, 39 (само в клас/на лист).
// Упр. 10: дигитален вариант — визитка по модел (Мария от ДИАЛОЗИ 1); личната визитка — на хартия.
// Упр. 18: препроверете В/Г спрямо картата от упр. 2.
// Упр. 29: попълване по текст; аудио — опционално.

export const exercises: Exercise[] = [
  {
    id: 'l05-ex-01',
    type: 'image_labeling',
    instruction: 'Знаете ли тези места? Изберете в кои градове се намират.',
    order: 1,
    points: 5,
    displayType: 'default',
    images: [
      { id: 'sofia', imageUrl: '/assets/lesson-05/01-upr-01-zabelezhitelnosti-gradove/01-aleksandar-nevski-sofia.jpg', correctLabel: 'София', acceptableLabels: ['софия'] },
      { id: 'kairo', imageUrl: '/assets/lesson-05/01-upr-01-zabelezhitelnosti-gradove/02-piramidi-kairo.jpg', correctLabel: 'Кайро', acceptableLabels: ['кайро'] },
      { id: 'london', imageUrl: '/assets/lesson-05/01-upr-01-zabelezhitelnosti-gradove/03-big-ben-london.jpg', correctLabel: 'Лондон', acceptableLabels: ['лондон'] },
      { id: 'istanbul', imageUrl: '/assets/lesson-05/01-upr-01-zabelezhitelnosti-gradove/04-sinyata-dzhamiya-istanbul.jpg', correctLabel: 'Истанбул', acceptableLabels: ['истанбул'] },
      { id: 'parizh', imageUrl: '/assets/lesson-05/01-upr-01-zabelezhitelnosti-gradove/05-ayfelova-kula-parizh.jpg', correctLabel: 'Париж', acceptableLabels: ['париж'] },
    ],
    options: ['Истанбул', 'Кайро', 'Лондон', 'Париж', 'София'],
  } as ImageLabelingExercise,

  {
    id: 'l05-novi-dumi-01',
    type: 'illustrated_cards',
    title: 'НОВИ ДУМИ 1',
    instruction: '',
    order: 2,
    cards: [
      { id: 'apteka', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/01-apteka.jpg', label: 'аптека' },
      { id: 'banka', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/02-banka.jpg', label: 'банка' },
      { id: 'biblioteka', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/03-biblioteka.jpg', label: 'библиотека' },
      { id: 'blok', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/04-blok.jpg', label: 'блок' },
      { id: 'bolnitsa', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/05-bolnitsa.jpg', label: 'болница' },
      { id: 'bulevard', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/06-bulevard.jpg', label: 'булевард' },
      { id: 'kafe', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/07-kafe.jpg', label: 'кафе' },
      { id: 'kino', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/08-kino.jpg', label: 'кино' },
      { id: 'muzei', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/09-muzey.jpg', label: 'музей' },
      { id: 'teatar', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/10-teatar.jpg', label: 'театър' },
      { id: 'ulitsa', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/11-ulitsa.jpg', label: 'улица' },
      { id: 'hotel', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/12-hotel.jpg', label: 'хотел' },
      { id: 'restorant', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/13-restorant.jpg', label: 'ресторант' },
      { id: 'supermarket', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/14-supermarket.jpg', label: 'супермаркет (супер)' },
      { id: 'universitet', imageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/15-universitet.jpg', label: 'университет' },
    ],
  } as IllustratedCardsExercise,

  {
    id: 'l05-ex-02',
    type: 'dropdown_match',
    instruction: 'Вижте картата. За всяка снимка изберете правилната дума.',
    order: 3,
    points: 12,
    imageUrl: '/assets/lesson-05/03-upr-02-karta-grad/01-karta-grad-centar.jpg',
    questions: [
      { id: 'm1',  left: 'блок',        leftImageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/04-blok.jpg',        options: ['блок', 'хотел', 'банка', 'ресторант'],          correctAnswer: 'блок' },
      { id: 'm2',  left: 'ресторант',   leftImageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/13-restorant.jpg',   options: ['ресторант', 'кафе', 'кино', 'супермаркет'],      correctAnswer: 'ресторант' },
      { id: 'm3',  left: 'библиотека',  leftImageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/03-biblioteka.jpg',  options: ['библиотека', 'музей', 'училище', 'поща'],        correctAnswer: 'библиотека' },
      { id: 'm4',  left: 'университет', leftImageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/15-universitet.jpg', options: ['университет', 'училище', 'община', 'театър'],    correctAnswer: 'университет' },
      { id: 'm5',  left: 'музей',       leftImageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/09-muzey.jpg',       options: ['музей', 'банка', 'болница', 'аптека'],           correctAnswer: 'музей' },
      { id: 'm6',  left: 'хотел',       leftImageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/12-hotel.jpg',       options: ['хотел', 'блок', 'кафе', 'кино'],                correctAnswer: 'хотел' },
      { id: 'm7',  left: 'театър',      leftImageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/10-teatar.jpg',      options: ['театър', 'кино', 'музей', 'поща'],               correctAnswer: 'театър' },
      { id: 'm8',  left: 'аптека',      leftImageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/01-apteka.jpg',      options: ['аптека', 'болница', 'банка', 'поща'],            correctAnswer: 'аптека' },
      { id: 'm9',  left: 'болница',     leftImageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/05-bolnitsa.jpg',    options: ['болница', 'аптека', 'полиция', 'поща'],          correctAnswer: 'болница' },
      { id: 'm10', left: 'кино',        leftImageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/08-kino.jpg',        options: ['кино', 'театър', 'кафе', 'ресторант'],           correctAnswer: 'кино' },
      { id: 'm11', left: 'кафе',        leftImageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/07-kafe.jpg',        options: ['кафе', 'ресторант', 'кино', 'банка'],            correctAnswer: 'кафе' },
      { id: 'm12', left: 'супермаркет', leftImageUrl: '/assets/lesson-05/02-novi-dumi-1-mesta-v-grada/14-supermarket.jpg', options: ['супермаркет', 'пазар', 'магазин', 'банка'],      correctAnswer: 'супермаркет' },
    ],
  } as DropdownMatchExercise,

  {
    id: 'l05-novi-dumi-02',
    type: 'illustrated_cards',
    title: 'НОВИ ДУМИ 2',
    instruction: '',
    order: 4,
    cards: [
      { id: 'detska-gradina', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/01-detska-gradina.jpg', label: 'детска градина' },
      { id: 'detska-ploshtadka', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/02-detska-ploshtadka.jpg', label: 'детска площадка' },
      { id: 'dzhamiya', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/03-dzhamiya.jpg', label: 'джамия' },
      { id: 'kashta', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/04-kashta.jpg', label: 'къща' },
      { id: 'magazin', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/05-magazin.jpg', label: 'магазин' },
      { id: 'most', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/06-most.jpg', label: 'мост' },
      { id: 'obshtina', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/07-obshtina.jpg', label: 'община' },
      { id: 'pazar', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/08-pazar.jpg', label: 'пазар' },
      { id: 'pametnik', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/09-pametnik.jpg', label: 'паметник' },
      { id: 'park', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/10-park.jpg', label: 'парк' },
      { id: 'ploshtad', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/11-ploshtad.jpg', label: 'площад' },
      { id: 'poshta', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/12-poshta.jpg', label: 'поща' },
      { id: 'reka', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/13-reka.jpg', label: 'река' },
      { id: 'uchilishte', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/14-uchilishte.jpg', label: 'училище' },
      { id: 'tsarkva', imageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/15-tsarkva.jpg', label: 'църква' },
    ],
  } as IllustratedCardsExercise,

  {
    id: 'l05-ex-03',
    type: 'dropdown_match',
    instruction: 'Вижте картата. За всяка снимка изберете правилната дума.',
    order: 5,
    points: 10,
    imageUrl: '/assets/lesson-05/05-upr-03-karta-selo/01-karta-selo-centar.jpg',
    questions: [
      { id: 's1',  left: 'къща',            leftImageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/04-kashta.jpg',            options: ['къща', 'блок', 'училище', 'църква'],                 correctAnswer: 'къща' },
      { id: 's2',  left: 'детска площадка', leftImageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/02-detska-ploshtadka.jpg', options: ['детска площадка', 'парк', 'пазар', 'детска градина'], correctAnswer: 'детска площадка' },
      { id: 's3',  left: 'паметник',        leftImageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/09-pametnik.jpg',           options: ['паметник', 'площад', 'община', 'църква'],             correctAnswer: 'паметник' },
      { id: 's4',  left: 'джамия',          leftImageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/03-dzhamiya.jpg',           options: ['джамия', 'църква', 'училище', 'община'],             correctAnswer: 'джамия' },
      { id: 's5',  left: 'училище',         leftImageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/14-uchilishte.jpg',         options: ['училище', 'библиотека', 'община', 'поща'],           correctAnswer: 'училище' },
      { id: 's6',  left: 'мост',            leftImageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/06-most.jpg',               options: ['мост', 'улица', 'парк', 'река'],                     correctAnswer: 'мост' },
      { id: 's7',  left: 'река',            leftImageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/13-reka.jpg',               options: ['река', 'мост', 'парк', 'площад'],                    correctAnswer: 'река' },
      { id: 's8',  left: 'църква',          leftImageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/15-tsarkva.jpg',            options: ['църква', 'джамия', 'община', 'пазар'],               correctAnswer: 'църква' },
      { id: 's9',  left: 'поща',            leftImageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/12-poshta.jpg',             options: ['поща', 'магазин', 'пазар', 'община'],               correctAnswer: 'поща' },
      { id: 's10', left: 'община',          leftImageUrl: '/assets/lesson-05/04-novi-dumi-2-mesta/07-obshtina.jpg',           options: ['община', 'училище', 'полиция', 'банка'],            correctAnswer: 'община' },
    ],
  } as DropdownMatchExercise,

  {
    id: 'l05-ex-04',
    type: 'syllable_blocks',
    instruction: 'Влачете сричките и ги подредете, за да съставите думи.',
    order: 6,
    points: 10,
    imageUrl: '', // TODO: зелената таблица от учебника (стр. 46) — липсва като отделно изображение в IMAGE-MAPPING
    puzzles: [
      { id: 'p1',  syllables: ['-РАНТ', 'РЕС-',  '-ТО-'          ], correctWord: 'РЕСТОРАНТ'  },
      { id: 'p2',  syllables: ['-ЦА',   '-НИ-',  'БОЛ-'          ], correctWord: 'БОЛНИЦА'    },
      { id: 'p3',  syllables: ['-МАР-', '-КЕТ',  'СУ-',   '-ПЕР-'], correctWord: 'СУПЕРМАРКЕТ' },
      { id: 'p4',  syllables: ['-ЩЕ',   '-ЛИ-',  'У-',    '-ЧИ-' ], correctWord: 'УЧИЛИЩЕ'   },
      { id: 'p5',  syllables: ['-ЗЕЙ',  'МУ-'                    ], correctWord: 'МУЗЕЙ'      },
      { id: 'p6',  syllables: ['-ЩАД',  'ПЛО-'                   ], correctWord: 'ПЛОЩАД'     },
      { id: 'p7',  syllables: ['-ВАРД', '-ЛЕ-',  'БУ-'           ], correctWord: 'БУЛЕВАРД'   },
      { id: 'p8',  syllables: ['-ЗИН',  'МА-',   '-ГА-'          ], correctWord: 'МАГАЗИН'    },
      { id: 'p9',  syllables: ['-МИЯ',  'ДЖА-'                   ], correctWord: 'ДЖАМИЯ'     },
      { id: 'p10', syllables: ['-ТЕЛ',  'ХО-'                    ], correctWord: 'ХОТЕЛ'      },
    ],
  } as SyllableBlocksExercise,

  {
    id: 'l05-ex-05',
    type: 'true_false',
    title: 'УПРАЖНЕНИЕ 5',
    instruction: 'Вижте картата на центъра на ГРАДА от упр. 2. Кои от следните места има на картата? Вярно или грешно?',
    order: 7,
    imageUrl: '/assets/lesson-05/03-upr-02-karta-grad/01-karta-grad-centar.jpg',
    points: 12,
    sentences: [
      { id: 'l05-ex05-1',  text: 'Има блок.',        isTrue: true },
      { id: 'l05-ex05-2',  text: 'Има ресторант.',    isTrue: true },
      { id: 'l05-ex05-3',  text: 'Има аптека.',       isTrue: true },
      { id: 'l05-ex05-4',  text: 'Има болница.',      isTrue: true },
      { id: 'l05-ex05-5',  text: 'Има театър.',       isTrue: true },
      { id: 'l05-ex05-6',  text: 'Има музей.',        isTrue: true },
      { id: 'l05-ex05-7',  text: 'Има джамия.',       isTrue: false },
      { id: 'l05-ex05-8',  text: 'Има мост.',         isTrue: false },
      { id: 'l05-ex05-9',  text: 'Има река.',         isTrue: false },
      { id: 'l05-ex05-10', text: 'Има поща.',         isTrue: false },
      { id: 'l05-ex05-11', text: 'Има банка.',        isTrue: false },
      { id: 'l05-ex05-12', text: 'Има паметник.',     isTrue: false },
    ],
  } as TrueFalseExercise,

  {
    id: 'l05-dialozi-01',
    type: 'dialogues',
    title: 'ДИАЛОЗИ 1',
    instruction: 'Натиснете всяка реплика, за да чуете произношението. После повторете на глас.',
    order: 9,
    sections: [
      {
        id: 'а', // NOTE: subpoints use Cyrillic letters а,б,в,г as required
        lines: [
          { text: '— Къде живееш?' },
          { text: '— Аз живея в София, на улица „Гурко“ 25.', ttsText: 'Аз живея в София, на улица Гурко двайсет и пет.' },
        ],
      },
      {
        id: 'б',
        lines: [
          { text: '— Къде живее Мария?' },
          { text: '— Мария живее в София, в квартал „Младост“ 2, блок 243, вход А, етаж 2, апартамент 5.', ttsText: 'Мария живее в София, в квартал Младост 2, блок 243, вход А, етаж 2, апартамент 5.' },
        ],
      },
      {
        id: 'в',
        lines: [
          { text: '— Къде живее Абдул?' },
          { text: '— Той живее в жк „Люлин“ 7, бл. 704, вх. Б, ет. 4, ап. 12.', ttsText: 'Той живее в жилищен квартал Люлин 7, блок 704, вход Б, етаж 4, апартамент 12.' },
        ],
      },
      {
        id: 'г',
        lines: [
          { text: '— Къде живеят Петър и Дора?' },
          { text: '— Те живеят в Перник.' },
          { text: '— В къща или в блок?' },
          { text: '— В блок, но имат къща на село.' },
        ],
      },
    ],
  } as DialoguesExercise,

  {
    id: 'l05-info-sakra',
    type: 'grammar_examples',
    title: 'Адресни съкращения',
    instruction: 'Запомнете съкратените форми.',
    order: 10,
    ttsFlash: true,
    examples: [
      { imageUrl: '', text: 'гр. = град', subtext: '', translations: { en: 'city', ar: 'مدينة', fr: 'ville', fa: 'شهر', uk: 'місто', ru: 'город' }, ttsText: 'град' },
      { imageUrl: '', text: 'с. = село', subtext: '', translations: { en: 'village', ar: 'قرية', fr: 'village', fa: 'روستا', uk: 'село', ru: 'село' }, ttsText: 'село' },
      { imageUrl: '', text: 'кв. = квартал', subtext: '', translations: { en: 'neighborhood', ar: 'حي', fr: 'quartier', fa: 'محله', uk: 'район', ru: 'квартал' }, ttsText: 'квартал' },
      { imageUrl: '', text: 'жк = жилищен комплекс', subtext: '', translations: { en: 'residential complex', ar: 'مجمع سكني', fr: 'complexe résidentiel', fa: 'مجتمع مسکونی', uk: 'житловий комплекс', ru: 'жилой комплекс' }, ttsText: 'жилищен комплекс' },
      { imageUrl: '', text: 'ул. = улица', subtext: '', translations: { en: 'street', ar: 'شارع', fr: 'rue', fa: 'خیابان', uk: 'вулиця', ru: 'улица' }, ttsText: 'улица' },
      { imageUrl: '', text: 'бул. = булевард', subtext: '', translations: { en: 'boulevard', ar: 'شارع رئيسي', fr: 'boulevard', fa: 'بلوار', uk: 'бульвар', ru: 'бульвар' }, ttsText: 'булевард' },
      { imageUrl: '', text: '№ = номер', subtext: '', translations: { en: 'number', ar: 'رقم', fr: 'numéro', fa: 'شماره', uk: 'номер', ru: 'номер' }, ttsText: 'номер' },
      { imageUrl: '', text: 'бл. = блок', subtext: '', translations: { en: 'block', ar: 'مبنى', fr: 'bloc', fa: 'بلوک', uk: 'блок', ru: 'блок' }, ttsText: 'блок' },
      { imageUrl: '', text: 'вх. = вход', subtext: '', translations: { en: 'entrance', ar: 'مدخل', fr: 'entrée', fa: 'ورودی', uk: 'під\'їзд', ru: 'подъезд' }, ttsText: 'вход' },
      { imageUrl: '', text: 'ет. = етаж', subtext: '', translations: { en: 'floor', ar: 'طابق', fr: 'étage', fa: 'طبقه', uk: 'поверх', ru: 'этаж' }, ttsText: 'етаж' },
      { imageUrl: '', text: 'ап. = апартамент', subtext: '', translations: { en: 'apartment', ar: 'شقة', fr: 'appartement', fa: 'آپارتمان', uk: 'квартира', ru: 'квартира' }, ttsText: 'апартамент' },
      { imageUrl: '', text: 'тел. = телефон', subtext: '', translations: { en: 'phone', ar: 'هاتف', fr: 'téléphone', fa: 'تلفن', uk: 'телефон', ru: 'телефон' }, ttsText: 'телефон' },
    ],
  } as GrammarExamplesExercise,

  {
    id: 'l05-ex-09',
    type: 'workbook_fill_blank',
    title: 'УПРАЖНЕНИЕ 9',
    instruction: 'Изберете адресите, като използвате съкратените форми.',
    order: 11,
    points: 2,
    layout: 'single',
    sentences: [
      { text: 'Модел: квартал Лозенец → кв. „Лозенец“', blanks: [], correctAnswers: [], isExample: true },
      {
        text: 'квартал „Лозенец“, булевард „Джеймс Баучър“, номер 76 → _______',
        blanks: [0],
        correctAnswers: ['кв. „Лозенец“, бул. „Джеймс Баучър“, № 76'],
        options: ['кв. „Лозенец“, бул. „Джеймс Баучър“, № 76', 'кв. Лозенец, бул. Джеймс Баучър, 76', 'квартал „Лозенец“, булевард „Джеймс Баучър“, номер 76'],
      },
      {
        text: 'жилищен комплекс „Илинден“, блок 55, вход В, етаж 1, апартамент 47 → _______',
        blanks: [0],
        correctAnswers: ['жк „Илинден“, бл. 55, вх. В, ет. 1, ап. 47'],
        options: ['жк „Илинден“, бл. 55, вх. В, ет. 1, ап. 47', 'ж.к. Илинден, блок 55, вход В', 'жилищен комплекс Илинден, бл. 55'],
      },
    ],
  } as WorkbookFillBlankExercise,

  {
    id: 'l05-ex-10',
    type: 'workbook_fill_blank',
    title: 'УПРАЖНЕНИЕ 10',
    instruction: 'Изслушайте диалог (б) и попълнете визитката на Мария Петрова.',
    order: 12,
    layout: 'single',
    points: 3,
    listeningText: 'Мария живее в София, в квартал „Младост“ 2, блок 243, вход А, етаж 2, апартамент 5.',
    sentences: [
      { text: 'Мария Петрова', blanks: [], correctAnswers: [], isExample: true },
      { text: 'Град: _______', blanks: [0], correctAnswers: ['София'] },
      { text: 'кв./жк: _______', blanks: [0], correctAnswers: ['Младост 2'], acceptableAnswers: [['Младост 2', '„Младост“ 2']] },
      { text: 'бл. _______, вх. _______, ет. _______, ап. _______', blanks: [0, 1, 2, 3], correctAnswers: ['243', 'А', '2', '5'] },
    ],
  } as WorkbookFillBlankExercise,

  {
    id: 'l05-ex-11',
    type: 'workbook_fill_blank',
    title: 'УПРАЖНЕНИЕ 11',
    instruction: 'Натиснете текста, за да чуете произношението. Попълнете визитката.',
    order: 13,
    points: 5,
    layout: 'single',
    listeningText: 'Казвам се Иван Колев. Аз съм учител по история. Живея в София, в жилищен комплекс „Люлин“ 3, блок 15, етаж 4, апартамент 16. Телефонът ми е 0888 234 567.',
    sentences: [
      {
        text: 'Иван _______',
        blanks: [0],
        correctAnswers: ['Колев'],
        options: ['Колев', 'Петров', 'Иванов', 'Георгиев'],
      },
      {
        text: 'учител по _______',
        blanks: [0],
        correctAnswers: ['история'],
        options: ['история', 'математика', 'български', 'физика'],
      },
      {
        text: 'жк „Люлин“ _______, бл. 15',
        blanks: [0],
        correctAnswers: ['3'],
        options: ['3', '7', '2', '5'],
      },
      {
        text: 'ет. _______, ап. 16',
        blanks: [0],
        correctAnswers: ['4'],
        options: ['4', '2', '3', '6'],
      },
      {
        text: 'тел. _______',
        blanks: [0],
        correctAnswers: ['0888 234 567'],
        options: ['0888 234 567', '0887 654 321', '0899 111 222', '0878 345 678'],
      },
    ],
  } as WorkbookFillBlankExercise,

  {
    id: 'l05-gramatika-01',
    instructionKey: 'grammar.l05.g1.instruction',
    type: 'grammar_table',
    title: 'ГРАМАТИКА 1',
    subtitle: '→ Граматика – Сегашно време',
    instruction: 'Глагол ЖИВЕЯ в сегашно време — прегледайте таблицата и примера.',
    order: 14,
    tableTitle: 'Живея (живе–)',
    columns: ['Форма'],
    rows: [
      { pronoun: 'аз', cells: ['живея'] },
      { pronoun: 'ти', cells: ['живееш'] },
      { pronoun: 'той / тя / то', cells: ['живее'] },
      { pronoun: 'ние', cells: ['живеем'] },
      { pronoun: 'Вие', cells: ['живеете'] },
      { pronoun: 'те', cells: ['живеят'] },
    ],
    notes: ['Иван живее в София, на улица „Янтра“ 5.'],
  } as GrammarTableExercise,

  {
    id: 'l05-ex-12',
    type: 'dropdown_match',
    instruction: 'Свържете местоимението с правилната глаголна форма.',
    order: 15,
    points: 8,
    questions: [
      { id: 'q1', left: 'аз …', options: ['живея', 'живееш', 'живее', 'живеем'], correctAnswer: 'живея' },
      { id: 'q2', left: 'ти …', options: ['живея', 'живееш', 'живее', 'живеете'], correctAnswer: 'живееш' },
      { id: 'q3', left: 'той …', options: ['живея', 'живее', 'живеем', 'живеят'], correctAnswer: 'живее' },
      { id: 'q4', left: 'тя …', options: ['живееш', 'живее', 'живеете', 'живеят'], correctAnswer: 'живее' },
      { id: 'q5', left: 'то …', options: ['живея', 'живее', 'живеем', 'живеят'], correctAnswer: 'живее' },
      { id: 'q6', left: 'ние …', options: ['живеем', 'живеете', 'живеят', 'живее'], correctAnswer: 'живеем' },
      { id: 'q7', left: 'вие …', options: ['живея', 'живееш', 'живеете', 'живеят'], correctAnswer: 'живеете' },
      { id: 'q8', left: 'те …', options: ['живее', 'живеем', 'живеете', 'живеят'], correctAnswer: 'живеят' },
    ],
  } as DropdownMatchExercise,

  {
    id: 'l05-ex-13',
    type: 'workbook_fill_blank',
    instruction: 'Попълнете окончанията.',
    order: 16,
    points: 6,
    layout: 'single',
    sentences: [
      { text: 'Аз живе_______ в София.', blanks: [0], correctAnswers: ['я'], isExample: true },
      { text: 'Ти къде живе_______?', blanks: [0], correctAnswers: ['еш'], options: ['еш', 'я', 'е', 'ем'] },
      { text: 'Той живе_______ на булевард „България“.', blanks: [0], correctAnswers: ['е'], options: ['е', 'еш', 'ете', 'ят'] },
      { text: 'Ние не живе_______ в Иран.', blanks: [0], correctAnswers: ['ем'], options: ['ем', 'ете', 'ят', 'е'] },
      { text: 'Те живе_______ на село.', blanks: [0], correctAnswers: ['ят'], options: ['ят', 'ете', 'еш', 'я'] },
      { text: 'Вие не живе_______ във Варна.', blanks: [0], correctAnswers: ['ете'], options: ['ете', 'ем', 'ят', 'е'] },
      { text: 'Тя живе_______ в жк „Люлин“.', blanks: [0], correctAnswers: ['е'], options: ['е', 'еш', 'ете', 'ят'] },
    ],
  } as WorkbookFillBlankExercise,

  {
    id: 'l05-gramatika-02',
    instructionKey: 'grammar.l05.g2.instruction',
    type: 'grammar_table',
    title: 'ГРАМАТИКА 2',
    subtitle: 'Членуване на съществителните',
    instruction: 'Членуване — единствено число.',
    order: 17,
    tableTitle: 'Членуване в единствено число',
    columns: ['Основна форма', 'Окончание', 'Примери'],
    rows: [
      { pronoun: 'мъжки род (а)', cells: ['пазар, студент', '-**ът** / -**а**', 'пазар**ът** / в центъра'] },
      { pronoun: 'мъжки род (б)', cells: ['учител, лекар', '-**ят** / -**я**', 'учител**ят** / при учителя'] },
      { pronoun: 'женски род', cells: ['банка, улица', '-**та**', 'банка**та**, улица**та**'] },
      { pronoun: 'среден род', cells: ['кафе, училище', '-**то**', 'кафе**то**, училище**то**'] },
    ],
    notes: ['Площадът е в центъра.'],
  } as GrammarTableExercise,

  {
    id: 'l05-ex-14',
    type: 'multiple_choice',
    instruction: 'Подчертайте определителния член в изреченията. (Изберете думата с член.)',
    order: 18,
    points: 3,
    questions: [
      {
        question: 'Това е хотел. Хотелът се казва „София“. Аз съм в хотела. Коя дума е с определителен член в третото изречение?',
        options: ['Аз', 'съм', 'в', 'хотела'],
        correctIndex: 3,
      },
      {
        question: 'Това е улица. Улицата се казва „Цар Симеон“. Аз съм на улицата. Коя дума е с определителен член в третото изречение?',
        options: ['Аз', 'съм', 'на', 'улицата'],
        correctIndex: 3,
      },
      {
        question: 'Това е училище. Училището се казва „Васил Левски“. Аз съм в училището. Коя дума е с определителен член в третото изречение?',
        options: ['Аз', 'съм', 'в', 'училището'],
        correctIndex: 3,
      },
    ],
  } as MultipleChoiceExercise,

  {
    id: 'l05-ex-15',
    type: 'drag_to_columns',
    instruction: 'Поставете думите в правилната колона.',
    order: 20,
    points: 21,
    imageUrl: '',
    items: [
      'аптека', 'банка', 'болница', 'град', 'капучино', 'кафе', 'кино', 'къща', 'масло', 'мляко',
      'пазар', 'пица', 'поща', 'ресторант', 'сандвич', 'село', 'училище', 'учителка', 'хляб', 'център', 'яйце',
    ],
    columns: [
      { id: 't-a', title: '-ът / -a', correctItems: ['град', 'пазар', 'център', 'ресторант', 'сандвич', 'хляб'] },
      { id: 'ta', title: '-та', correctItems: ['аптека', 'банка', 'болница', 'къща', 'учителка', 'поща', 'пица'] },
      { id: 'to', title: '-то', correctItems: ['кафе', 'капучино', 'кино', 'масло', 'мляко', 'село', 'училище', 'яйце'] },
    ],
  } as DragToColumnsExercise,

  {
    id: 'l05-gramatika-03',
    instructionKey: 'grammar.l05.g3.instruction',
    type: 'grammar_table',
    title: 'ГРАМАТИКА 3',
    subtitle: 'Множествено число — член',
    instruction: 'Членуване в множествено число.',
    order: 19,
    tableTitle: 'Членуване — множествено число',
    columns: ['Основна форма (мн.ч.)', 'Член', 'С член'],
    rows: [
      { pronoun: 'мъжки род', cells: ['пазари, градове', '-**те**', 'пазари**те**, градове**те**'] },
      { pronoun: 'женски род', cells: ['банки, улици', '-**те**', 'банки**те**, улици**те**'] },
      { pronoun: 'среден род', cells: ['кафета, училища', '-**та**', 'кафета**та**, училища**та**'] },
    ],
    notes: ['Магазините са в центъра.'],
  } as GrammarTableExercise,

  {
    id: 'l05-ex-16',
    type: 'drag_to_columns',
    title: 'УПРАЖНЕНИЕ 16',
    instruction: 'Поставете думите в правилната колона според определителния член.',
    order: 21,
    points: 14,
    items: [
      'булеварди', 'градове', 'джамии', 'кафета',
      'кина', 'кюфтета', 'млека', 'мостове',
      'площади', 'села', 'улици', 'училища',
      'църкви', 'яйца',
    ],
    columns: [
      {
        id: 'te',
        title: '-те',
        correctItems: ['булеварди', 'градове', 'джамии', 'мостове', 'площади', 'улици', 'църкви'],
      },
      {
        id: 'ta',
        title: '-та',
        correctItems: ['кафета', 'кина', 'кюфтета', 'млека', 'села', 'училища', 'яйца'],
      },
    ],
  } as DragToColumnsExercise,

  {
    id: 'l05-ex-17',
    type: 'workbook_fill_blank',
    instruction: 'Попълнете окончанията.',
    order: 22,
    points: 4,
    layout: 'single',
    sentences: [
      { text: 'Банките са в центъра.', blanks: [], correctAnswers: [], isExample: true },
      { text: 'Учителки_______ по български език са в училището.', blanks: [0], correctAnswers: ['те'], options: ['те', 'та', 'то', 'ят'] },
      { text: 'Кафета_______ са със захар.', blanks: [0], correctAnswers: ['та'], options: ['та', 'те', 'то', 'ят'] },
      { text: 'Зеленчуци_______ са евтини.', blanks: [0], correctAnswers: ['те'], options: ['те', 'та', 'то', 'ят'] },
      { text: 'Плодове_______ са скъпи.', blanks: [0], correctAnswers: ['те'], options: ['те', 'та', 'то', 'ят'] },
    ],
  } as WorkbookFillBlankExercise,

  {
    id: 'l05-gramatika-04',
    instructionKey: 'grammar.l05.g4.instruction',
    type: 'grammar_examples',
    title: 'ГРАМАТИКА 4',
    subtitle: 'Предлози за място',
    instruction: 'Запознайте се с предлозите и примерите.',
    order: 23,
    examples: [
      { imageUrl: '/assets/lesson-05/25-gramatika-4-predlozi-myasto/01-v.jpg',         text: 'в — в кутията, в центъра',    subtext: '', ttsText: 'в. в кутията, в центъра.' },
      { imageUrl: '/assets/lesson-05/25-gramatika-4-predlozi-myasto/02-na.jpg',         text: 'на — на масата',              subtext: '', ttsText: 'на. на масата.' },
      { imageUrl: '/assets/lesson-05/25-gramatika-4-predlozi-myasto/03-do.jpg',         text: 'до — до кутията',             subtext: '', ttsText: 'до. до кутията.' },
      { imageUrl: '/assets/lesson-05/25-gramatika-4-predlozi-myasto/04-pred.jpg',       text: 'пред — пред кутията',         subtext: '', ttsText: 'пред. пред кутията.' },
      { imageUrl: '/assets/lesson-05/25-gramatika-4-predlozi-myasto/05-zad.jpg',        text: 'зад — зад кутията',           subtext: '', ttsText: 'зад. зад кутията.' },
      { imageUrl: '/assets/lesson-05/25-gramatika-4-predlozi-myasto/06-mezhdu.jpg',     text: 'между — между две кутии',     subtext: '', ttsText: 'между. между две кутии.' },
      { imageUrl: '/assets/lesson-05/25-gramatika-4-predlozi-myasto/07-sreshtu.jpg',    text: 'срещу — срещу кутията',      subtext: '', ttsText: 'срещу. срещу кутията.' },
      { imageUrl: '/assets/lesson-05/25-gramatika-4-predlozi-myasto/08-blizo-do.jpg',   text: 'близо до — близо до кутията', subtext: '', ttsText: 'близо до. близо до кутията.' },
      { imageUrl: '/assets/lesson-05/25-gramatika-4-predlozi-myasto/09-daleche-ot.jpg', text: 'далече от — далече от кутията', subtext: '', ttsText: 'далече от. далече от кутията.' },
      {
        imageUrl: '',
        text: 'Театърът е:',
        lines: [
          '**в** центъра',
          '**до** музея',
          '**пред** университета',
          '**зад** аптеката',
          '**близо до** хотела',
          '**между** аптеката и университета',
          '**срещу** болницата',
          '**далече от** библиотеката',
        ],
        subtext: 'Внимание: Аз съм на улицата. Аз съм на улица „Иван Вазов“.',
      },
    ],
  } as GrammarExamplesExercise,

  {
    id: 'l05-ex-18',
    type: 'true_false',
    instruction: 'Вижте картата на ГРАДА от упр. 2 и отбележете с „Вярно" или „Грешно".',
    order: 24,
    imageUrl: '/assets/lesson-05/03-upr-02-karta-grad/01-karta-grad-centar.jpg',
    points: 9,
    sentences: [
      { id: 'l05-ex18-1', text: 'Университетът е зад театъра.', isTrue: true },
      { id: 'l05-ex18-2', text: 'Библиотеката е до хотела.', isTrue: false },
      { id: 'l05-ex18-3', text: 'Хотелът е близо до музея.', isTrue: true },
      { id: 'l05-ex18-4', text: 'Банката е на булеварда.', isTrue: false },
      { id: 'l05-ex18-5', text: 'Кафето е далече от супермаркета.', isTrue: false },
      { id: 'l05-ex18-6', text: 'Киното е между кафето и банката.', isTrue: false },
      { id: 'l05-ex18-7', text: 'Ресторантът е срещу хотела.', isTrue: true },
      { id: 'l05-ex18-8', text: 'Аптеката е пред театъра.', isTrue: true },
      { id: 'l05-ex18-9', text: 'Зад хотела има блок.', isTrue: true },
    ],
  } as TrueFalseExercise,

  {
    id: 'l05-ex-19',
    type: 'workbook_fill_blank',
    instruction:
      'Вижте картата на селото от упр. 3 и отговорете на въпросите по модела.',
    order: 25,
    points: 6,
    layout: 'qa-split',
    imageUrl: '/assets/lesson-05/05-upr-03-karta-selo/01-karta-selo-centar.jpg',
    sentences: [
      {
        text: 'Модел: — Къде е паметникът? | — Паметникът е на площада близо до църквата.',
        blanks: [],
        correctAnswers: [],
        isExample: true,
      },
      {
        text: '— Къде е джамията? | — Джамията е _______ до площада.',
        blanks: [0],
        correctAnswers: ['близо'],
        options: ['близо', 'далече', 'срещу', 'между'],
      },
      {
        text: '— Къде е общината? | — Общината е _______ площада.',
        blanks: [0],
        correctAnswers: ['на'],
        options: ['на', 'в', 'до', 'под'],
      },
      {
        text: '— Къде е пазарът? | — Пазарът е _______ центъра.',
        blanks: [0],
        correctAnswers: ['в'],
        options: ['в', 'на', 'до', 'зад'],
      },
      {
        text: '— Къде е паркът? | — Паркът е _______ селото.',
        blanks: [0],
        correctAnswers: ['в'],
        options: ['в', 'на', 'под', 'над'],
      },
      {
        text: '— Къде е магазинът? | — Магазинът е _______ пътя.',
        blanks: [0],
        correctAnswers: ['до'],
        options: ['до', 'в', 'на', 'под'],
      },
      {
        text: '— Къде е пощата? | — Пощата е _______ центъра.',
        blanks: [0],
        correctAnswers: ['в'],
        options: ['в', 'на', 'между', 'срещу'],
      },
    ],
  } as WorkbookFillBlankExercise,

  {
    id: 'l05-dialozi-02',
    type: 'dialogues',
    title: 'ДИАЛОЗИ 2',
    instruction: 'Натиснете всяка реплика, за да чуете произношението. После повторете на глас.',
    order: 26,
    imageUrl: '/assets/lesson-05/28-dialozi-2-posoka-karta/01-turisti-s-karta.jpg',
    sections: [
      {
        id: 'a',
        lines: [
          { text: '— Извинете, къде е общината?' },
          { text: '— Вървете направо, след банката завийте наляво.' },
          { text: '— А супермаркет „Била“?', ttsText: '- А супермаркет Билла?' },
          { text: '— Вървете направо и след 20 метра завийте надясно.' },
        ],
      },
    ],
  } as DialoguesExercise,

  {
    id: 'l05-gramatika-05',
    instructionKey: 'grammar.l05.g5.instruction',
    type: 'grammar_examples',
    title: 'ГРАМАТИКА 5',
    subtitle: 'Повелително наклонение — посока',
    instruction: 'Форми за указване на посока (вие/Вие или ти).',
    order: 27,
    examples: [
      { imageUrl: '', text: '', lines: ['Вие: Вървете направо.', 'Ти: Върви направо.'], subtext: '' },
      { imageUrl: '', text: '', lines: ['Вие: Завийте наляво.', 'Ти: Завий наляво.'], subtext: '' },
      { imageUrl: '', text: '', lines: ['Вие: Завийте надясно.', 'Ти: Завий надясно.'], subtext: '' },
    ],
    grammarHighlight: {
      text: 'Използваме „вие", когато има няколко човека или когато говорим в учтива форма на един човек. Във втория случай „Вие" се пише с главна буква.',
    },
  } as GrammarExamplesExercise,

  {
    id: 'l05-ex-21',
    type: 'match_pairs',
    instruction: 'Свържете всяка команда с правилния знак (стрелка).',
    order: 28,
    points: 3,
    pairs: [
      {
        id: 'p1',
        left: 'Вървете направо!',
        correctRight: '/assets/lesson-05/31-upr-21-strelki-posoka/03-varvete-napravo.jpg',
      },
      {
        id: 'p2',
        left: 'Завийте наляво!',
        correctRight: '/assets/lesson-05/31-upr-21-strelki-posoka/02-zaviy-nalyavo.jpg',
      },
      {
        id: 'p3',
        left: 'Завийте надясно!',
        correctRight: '/assets/lesson-05/31-upr-21-strelki-posoka/01-zaviy-nadyasno.jpg',
      },
    ],
    shuffledRights: [
      '/assets/lesson-05/31-upr-21-strelki-posoka/01-zaviy-nadyasno.jpg',
      '/assets/lesson-05/31-upr-21-strelki-posoka/03-varvete-napravo.jpg',
      '/assets/lesson-05/31-upr-21-strelki-posoka/02-zaviy-nalyavo.jpg',
    ],
  } as MatchPairsExercise,

  {
    id: 'l05-ex-22',
    type: 'workbook_fill_blank',
    instruction: 'Попълнете правилните форми.',
    order: 29,
    points: 5,
    layout: 'single',
    sentences: [
      { text: 'Вървете направо. (Вие)', blanks: [], correctAnswers: [], isExample: true },
      {
        text: 'Вървете _______ и след кафето _______ наляво. (Вие)',
        blanks: [0, 1],
        correctAnswers: ['направо', 'завийте'],
        options: [['направо', 'наляво', 'назад'], ['завийте', 'Завий', 'Вървете']],
      },
      {
        text: '_______ надясно и след пазара върви _______. (ти)',
        blanks: [0, 1],
        correctAnswers: ['Завий', 'направо'],
        options: [['Завий', 'завийте', 'Вървете'], ['направо', 'наляво']],
      },
      {
        text: 'Вървете _______ и след 100 метра _______ наляво. (вие)',
        blanks: [0, 1],
        correctAnswers: ['направо', 'завийте'],
        options: [['направо', 'наляво'], ['завийте', 'Завий']],
      },
      {
        text: 'Върви _______ и след моста _______ надясно. (ти)',
        blanks: [0, 1],
        correctAnswers: ['направо', 'завий'],
        options: [['направо', 'наляво'], ['завий', 'завийте']],
      },
      {
        text: '_______ направо и след пощата _______ наляво. (Вие)',
        blanks: [0, 1],
        correctAnswers: ['Вървете', 'завийте'],
        options: [['Вървете', 'Върви'], ['завийте', 'Завий']],
      },
    ],
  } as WorkbookFillBlankExercise,

  
  {
    id: 'l05-gramatika-06',
    instructionKey: 'grammar.l05.g6.instruction',
    type: 'grammar_table',
    title: 'ГРАМАТИКА 6',
    subtitle: 'Човек, души, хора',
    instruction: 'Бройни форми за хора.',
    order: 31,
    tableTitle: 'Число на съществителните (3)',
    columns: ['Форма', 'Изречения'],
    rows: [
      { pronoun: 'Единствено число', cells: ['един човек', 'Тук има един човек.'] },
      { pronoun: 'Множествено число', cells: ['десет души', 'Колко души има тук?'] },
      { pronoun: 'Общо', cells: ['много, малко хора', 'Тук няма много хора.'] },
    ],
  } as GrammarTableExercise,

  {
    id: 'l05-ex-24',
    type: 'workbook_fill_blank',
    instruction: 'Попълнете с думите: човек, души, хора.',
    order: 32,
    points: 5,
    layout: 'single',
    sentences: [
      { text: 'На улицата има много хора.', blanks: [], correctAnswers: [], isExample: true },
      { text: 'Колко _______ има в ресторанта?', blanks: [0], correctAnswers: ['души'], options: ['души', 'хора', 'човек'] },
      { text: 'В киното има десет _______.', blanks: [0], correctAnswers: ['души'], options: ['души', 'хора', 'човек'] },
      { text: 'В кафето има само един _______.', blanks: [0], correctAnswers: ['човек'], options: ['човек', 'души', 'хора'] },
      { text: 'Колко _______ има в селото?', blanks: [0], correctAnswers: ['души'], options: ['души', 'човек', 'хора'] },
      { text: 'В България живеят малко _______.', blanks: [0], correctAnswers: ['хора'], options: ['хора', 'души', 'човек'] },
    ],
  } as WorkbookFillBlankExercise,

  {
    id: 'l05-gramatika-07',
    instructionKey: 'grammar.l05.g7.instruction',
    type: 'grammar_table',
    title: 'ГРАМАТИКА 7',
    subtitle: 'Големи числа',
    instruction: 'Числата от 1000 до 1 000 000 000.',
    order: 33,
    grammarHighlight: {
      text: 'След две, три, четири или друга цифра и след думата „колко" казваме „милиона" или „милиарда". Когато говорим общо, без пояснения, казваме „милиони" или „милиарди".',
      examples: [
        'два милиона, шест милиарда',
        'Милиони хора живеят в Европа.',
      ],
    },
    tableTitle: 'Числата от 1000 до 1 000 000 000',
    columns: ['Дума'],
    rows: [
      { pronoun: '1 000', cells: ['хиляда'] },
      { pronoun: '2 000', cells: ['две хиляди'] },
      { pronoun: '1 000 000', cells: ['един милион'] },
      { pronoun: '2 000 000', cells: ['два милиона'] },
      { pronoun: '1 000 000 000', cells: ['един милиард'] },
    ],
    notes: ['След 2–4 използвайте „милиона/милиарда“; за много нещо — „милиони/милиарди“.'],
  } as GrammarTableExercise,

  {
    id: 'l05-ex-25',
    type: 'reading_text',
    title: 'УПРАЖНЕНИЕ 25',
    instruction: 'Прочетете числата.',
    order: 34,
    paragraphs: [
      'Модел: 173 268 — сто седемдесет и три хиляди двеста шестдесет и осем.',
      '1230. 2800. 86493. 370480.',
      '2970. 18490567. 12964098. 4500.',
      '987435000. 345. 12359. 933.',
      '284590. 706409. 54030.',
    ],
    ttsParagraphs: [
      'Модел. сто седемдесет и три хиляди двеста шестдесет и осем.',
      'хиляда двеста и тридесет. две хиляди осемстотин. осемдесет и шест хиляди четиристотин деветдесет и три. триста и седемдесет хиляди четиристотин и осемдесет.',
      'две хиляди деветстотин и седемдесет. осемнадесет милиона четиристотин деветдесет хиляди петстотин шестдесет и седем. дванадесет милиона деветстотин шестдесет и четири хиляди деветдесет и осем. четири хиляди и петстотин.',
      'деветстотин осемдесет и седем милиона четиристотин тридесет и пет хиляди. триста четиридесет и пет. дванадесет хиляди триста петдесет и девет. деветстотин тридесет и три.',
      'двеста осемдесет и четири хиляди петстотин и деветдесет. седемстотин и шест хиляди четиристотин и девет. петдесет и четири хиляди и тридесет.',
    ],
  } as ReadingTextExercise,

  {
    id: 'l05-ex-26',
    type: 'workbook_fill_blank',
    instruction: 'Изберете правилната форма на милион.',
    order: 35,
    points: 4,
    layout: 'single',
    sentences: [
      { text: 'Колко милиона души живеят в София?', blanks: [], correctAnswers: [], isExample: true },
      { text: 'В България живеят осем _______ души.', blanks: [0], correctAnswers: ['милиона'], options: ['милиона', 'милион', 'милиони'] },
      { text: 'Аз имам един _______ евро.', blanks: [0], correctAnswers: ['милион'], options: ['милион', 'милиона', 'милиони'] },
      { text: 'Колко _______ живеят в Дамаск?', blanks: [0], correctAnswers: ['милиона'], options: ['милиона', 'милион', 'милиони'] },
      { text: 'Има _______ бежанци.', blanks: [0], correctAnswers: ['милиони'], options: ['милиони', 'милиона', 'милион'] },
    ],
  } as WorkbookFillBlankExercise,

  {
    id: 'l05-ex-27',
    type: 'workbook_fill_blank',
    title: 'ДОПЪЛНИТЕЛНИ УПРАЖНЕНИЯ',
    instruction: 'Попълнете празните места в диалозите.',
    order: 36,
    points: 5,
    layout: 'qa-split',
    sentences: [
      {
        text: '— _______ живеете? | — Аз _______ в София, на „Шипка“, _______ 2.',
        blanks: [0, 1, 2],
        correctAnswers: ['Къде', 'живея', 'номер'],
        options: [
          ['Къде', 'Как'],
          ['живея', 'живеете'],
          ['номер', 'бул'],
        ],
      },
      {
        text: '— _______, къде е кафе „Малина“? | — Вървете _______, след хотела _______ надясно.',
        blanks: [0, 1, 2],
        correctAnswers: ['Извинете', 'направо', 'завийте'],
        options: [
          ['Извинете', 'Къде'],
          ['направо', 'наляво'],
          ['завийте', 'Завий'],
        ],
      },
    ],
  } as WorkbookFillBlankExercise,

  {
    id: 'l05-ex-28',
    type: 'reading_text',
    title: 'УПРАЖНЕНИЕ 28',
    instruction: 'Изслушайте текста и след това го прочетете сами.',
    order: 37,
    audioUrl: '/assets/lesson-05/audio/tts/texts/l05-ex-28-full.mp3',
    images: [{ imageUrl: '/assets/lesson-05/40-upr-28-varna-plazh/01-plazh-more-varna.jpg', label: 'Плаж във Варна' }],
    paragraphs: [
      'Град Варна е на морето, близо до Румъния. Във Варна живеят 336 000 души. Има също много туристи. Във Варна има плажове, много ресторанти, кафета и молове.',
    ],
    showDictionary: true,
  } as ReadingTextExercise,

  {
    id: 'l05-ex-29',
    type: 'workbook_fill_blank',
    instruction: 'Натиснете текста, за да чуете произношението. Попълнете празните места.',
    order: 38,
    points: 5,
    layout: 'single',
    listeningText:
      'Град Пловдив е в южната част на България. В Пловдив живеят триста четиридесет и осем хиляди души. В Пловдив има стар град, много университети и музеи, има античен театър и амфитеатър.',
    imageUrl: '/assets/lesson-05/41-upr-29-plovdiv-stari-grad/01-ulitsa-stariya-plovdiv.jpg',
    sentences: [
      {
        text: 'Град Пловдив е в _______ на България. В Пловдив живеят _______ души. В Пловдив има _______, много университети и _______, има _______ и амфитеатър.',
        blanks: [0, 1, 2, 3, 4],
        correctAnswers: ['южната част', '348 000', 'стар град', 'музеи', 'античен театър'],
        options: [
          ['южната част', 'центъра', 'северната част', 'планината'],
          ['348 000', '336 000', '250 000', '1 200 000'],
          ['стар град', 'новия град', 'летището', 'вокзала'],
          ['музеи', 'плажове', 'фабрики', 'болници'],
          ['античен театър', 'метро', 'летище', 'зоопарк'],
        ] as string[][],
      },
    ],
  } as WorkbookFillBlankExercise,

  {
    id: 'l05-ex-30',
    type: 'workbook_fill_blank',
    instruction: 'Отговорете на въпросите за Варна и Пловдив.',
    order: 39,
    points: 4,
    layout: 'qa-split',
    sentences: [
      { text: 'Колко души живеят във Варна? | _______', blanks: [0], correctAnswers: ['336 000 души.'], options: ['336 000 души.', '348 000 души.', '2500 души.', '300 души.'] },
      { text: 'Какво има във Варна? | _______', blanks: [0], correctAnswers: ['Плажове, ресторанти, кафета, молове.'], options: ['Плажове, ресторанти, кафета, молове.', 'Само планина.', 'Няма училище.', 'Само села.'] },
      { text: 'Колко души живеят в Пловдив? | _______', blanks: [0], correctAnswers: ['348 000 души.'], options: ['348 000 души.', '336 000 души.', '300 души.', '2500 души.'] },
      { text: 'Какво има в Пловдив? | _______', blanks: [0], correctAnswers: ['Старият град, университети, музеи, античен театър, амфитеатър.'], options: ['Старият град, университети, музеи, античен театър, амфитеатър.', 'Само море.', 'Няма църкви.', 'Само летище.'] },
    ],
  } as WorkbookFillBlankExercise,

  {
    id: 'l05-ex-32',
    type: 'reading_text',
    title: 'УПРАЖНЕНИЕ 32',
    instruction: 'Изслушайте текста и след това го прочетете сами.',
    order: 40,
    audioUrl: '/assets/lesson-05/audio/tts/texts/l05-ex-32-full.mp3',
    images: [{ imageUrl: '/assets/lesson-05/44-tekstove-shtarkel-darvo/01-shtarkel-v-gnezdo.jpg', label: '' }],
    paragraphs: [
      'Село Нови извор е в полето, близо до Турция. В селото живеят 300 души – баби и дядовци. В селото няма деца, няма и училище. Няма магазин, кафе и ресторант. Има една църква и река с мост. В реката има много риба.',
    ],
    showDictionary: true,
  } as ReadingTextExercise,

  {
    id: 'l05-ex-33',
    type: 'reading_text',
    title: 'УПРАЖНЕНИЕ 33',
    instruction: 'Изслушайте текста и след това го прочетете сами.',
    order: 41,
    audioUrl: '/assets/lesson-05/audio/tts/texts/l05-ex-33-full.mp3',
    images: [{ imageUrl: '/assets/lesson-05/44-tekstove-shtarkel-darvo/02-darvo-akvarel.jpg', label: '' }],
    paragraphs: [
      'Село Рибново е в планината, близо до Гърция. В селото живеят 2500 души. В Рибново има едно училище с много ученици и учители и една детска градина. В Рибново има община, джамия, един ресторант и много кафета. В планината над селото има гора с много дървета. Под дърветата има гъби и ягоди.',
    ],
    showDictionary: true,
  } as ReadingTextExercise,

  {
    id: 'l05-ex-34',
    type: 'true_false',
    instruction: 'Прочетете текста и определете дали твърденията са верни (✓) или неверни (✗).',
    order: 42,
    points: 8,
    sentences: [
      { id: 'tf34-1', text: 'Рибново е в планината.', isTrue: true },
      { id: 'tf34-2', text: 'Нови извор е в полето.', isTrue: true },
      { id: 'tf34-3', text: 'В Рибново няма училище.', isTrue: false },
      { id: 'tf34-4', text: 'В Нови извор има река.', isTrue: true },
      { id: 'tf34-5', text: 'Рибново е близо до Турция.', isTrue: false },
      { id: 'tf34-6', text: 'В Нови извор няма кафе.', isTrue: true },
      { id: 'tf34-7', text: 'В реката няма много риба.', isTrue: false },
      { id: 'tf34-8', text: 'В гората има малко дървета.', isTrue: false },
    ],
  } as TrueFalseExercise,

  {
    id: 'l05-ex-35',
    type: 'workbook_fill_blank',
    instruction: 'Отговорете на въпросите.',
    order: 43,
    points: 5,
    layout: 'qa-stacked',
    sentences: [
      {
        text: 'Колко души живеят в Рибново и в Нови извор? | В Рибново _______, в Нови извор _______.',
        blanks: [0, 1],
        correctAnswers: ['живеят 2500 души', '300 души'],
        options: [
          ['живеят 2500 души', '300 души', '336 000 души'],
          ['300 души', '2500 души', '348 000 души'],
        ],
      },
      { text: 'Какво има в селата? | _______', blanks: [0], correctAnswers: ['В Рибново: училище, детска градина, община, джамия, ресторант, кафета, гора; в Нови извор: църква, река, мост, риба.'], options: ['В Рибново: училище, детска градина, община, джамия, ресторант, кафета, гора; в Нови извор: църква, река, мост, риба.', 'Само хотели.', 'Нищо.', 'Само море.'] },
      { text: 'Какво има в планината? | _______', blanks: [0], correctAnswers: ['Гора с много дървета, гъби и ягоди под дърветата.'], options: ['Гора с много дървета, гъби и ягоди под дърветата.', 'Само плаж.', 'Няма нищо.', 'Само риба.'] },
      { text: 'Къде има гора с много дървета? | _______', blanks: [0], correctAnswers: ['В планината над Рибново.'], options: ['В планината над Рибново.', 'Във Варна.', 'В Нови извор.', 'В София.'] },
      { text: 'Какво има под дърветата? | _______', blanks: [0], correctAnswers: ['Гъби и ягоди.'], options: ['Гъби и ягоди.', 'Риба.', 'Плаж.', 'Метро.'] },
    ],
  } as WorkbookFillBlankExercise,

  {
    id: 'l05-ex-36',
    type: 'reading_text',
    title: 'ПРЕГОВОР',
    subtitle: 'Упражнения за затвърждаване на наученото',
    instruction: 'Изслушайте текста и след това го прочетете сами. Попълнете празните места.',
    order: 44,
    voiceGender: 'male',
    images: [{ imageUrl: '/assets/lesson-05/45-ot-parvo-litse-krepost-haleb/01-krepost-haleb-zalez.jpg', label: '' }],
    paragraphs: [
      'Аз съм Мохамед. Аз съм от Алепо. Сега живея в София.',
      'София е в България, Алепо е в Сирия. София и Алепо са големи градове: в София живеят около 1 200 000 души, в Алепо – 2 098 000. София е столица, Алепо – не е. Столицата на Сирия е Дамаск.',
      'В София и Алепо има големи улици. В София има метро, а в Алепо – няма.',
      'В Алепо има стара крепост и много стари къщи.',
      'В София има много паркове.',
    ],
    ttsParagraphs: [
      'Аз съм Мохамед. Аз съм от Алепо. Сега живея в София.',
      'София е в България, Алепо е в Сирия. София и Алепо са големи градове: в София живеят около един милион двеста хиляди души, в Алепо два милиона деветдесет и осем хиляди. София е столица, Алепо не е. Столицата на Сирия е Дамаск.',
      'В София и Алепо има големи улици. В София има метро, а в Алепо няма.',
      'В Алепо има стара крепост и много стари къщи.',
      'В София има много паркове.',
    ],
    showDictionary: true,
  } as ReadingTextExercise,

  {
    id: 'l05-ex-37',
    type: 'true_false',
    instruction: 'Прочетете текста и определете дали твърденията са верни (✓) или неверни (✗).',
    order: 45,
    points: 4,
    sentences: [
      { id: 'tf37-1', text: 'Мохамед живее в Алепо.', isTrue: false },
      { id: 'tf37-2', text: 'Алепо е столица на Сирия.', isTrue: false },
      { id: 'tf37-3', text: 'В Алепо има стара крепост.', isTrue: true },
      { id: 'tf37-4', text: 'В София няма много паркове.', isTrue: false },
    ],
  } as TrueFalseExercise,

  {
    id: 'l05-ex-38',
    type: 'workbook_fill_blank',
    instruction: 'Отговорете на въпросите.',
    order: 46,
    points: 4,
    layout: 'qa-stacked',
    sentences: [
      { text: 'Кои са столиците на България и Сирия? | _______', blanks: [0], correctAnswers: ['София и Дамаск.'], options: ['София и Дамаск.', 'Пловдив и Алепо.', 'Варна и Дамаск.', 'Алепо и Варна.'] },
      { text: 'Колко души живеят в София и в Алепо? | _______', blanks: [0], correctAnswers: ['В София около 1 200 000, в Алепо 2 098 000.'], options: ['В София около 1 200 000, в Алепо 2 098 000.', '336 000 и 348 000.', '300 и 2500.', 'Никой.'] },
      { text: 'Къде има метро? | _______', blanks: [0], correctAnswers: ['В София.'], options: ['В София.', 'В Алепо.', 'И в двата града.', 'Никъде.'] },
      { text: 'Къде има стара крепост? | _______', blanks: [0], correctAnswers: ['В Алепо.'], options: ['В Алепо.', 'В София.', 'Във Варна.', 'В Рибново.'] },
    ],
  } as WorkbookFillBlankExercise,

];