import type { LessonContent } from '@/content/types';

export const content: LessonContent = {
  introduction:
    'В единадесети урок ще научите как да разкажете за ежедневния си режим. Ще спрегнете глаголи от трите групи, ще използвате наречия за честота и ще прочетете текстове за живота на обикновените хора.',

  sections: [],

  dialogues: [
    // ДИАЛОЗИ 1 (стр. 102)
    {
      id: 'l11-content-dialozi-1a',
      speakers: [
        { text: '– Здравей, Абдул. Хайде на кафе.' },
        { text: '– Съжалявам, нямам време. След малко имам курс по български език.' },
        { text: '– О, чудесно! Приятен урок!' },
      ],
    },
    {
      id: 'l11-content-dialozi-1b',
      speakers: [
        { text: '– Здравей, Максим. Свободен ли си?' },
        { text: '– Да, свободен съм.' },
        { text: '– Хайде на разходка.' },
        { text: '– Добре, сега идвам.' },
      ],
    },
    {
      id: 'l11-content-dialozi-1c',
      speakers: [
        { text: '– Ало, Лейла! Какво правиш?' },
        { text: '– Готвя мусака.' },
        { text: '– Мъжът ти какво прави?' },
        { text: '– Добре е. Той работи от два месеца. Прави дюнери в един ресторант.' },
        { text: '– А децата какво правят?' },
        { text: '– Играят навън.' },
      ],
    },
    {
      id: 'l11-content-dialozi-1g',
      speakers: [
        { text: '– Добър ден, Ана. Къде отиваш?' },
        { text: '– Отивам на рожден ден.' },
        { text: '– Какво правят българите на този ден?' },
        { text: '– Канят гости, слушат музика, танцуват, ядат вкусна храна, говорят.' },
        { text: '– Така ли? Приятна вечер!' },
      ],
    },
    // ДИАЛОГ 2 (стр. 104)
    {
      id: 'l11-content-dialozi-2a',
      speakers: [
        { text: '– Здравей! Къде отиваш?' },
        { text: '– Отивам в супера.' },
        { text: '– Ходиш ли често в супера?' },
        { text: '– Да, обикновено ходя четири пъти в седмицата. А ти?' },
        { text: '– Аз ходя рядко – във вторник и петък.' },
      ],
    },
  ],

  vocabulary: [
    { id: 'bavno',       bulgarian: 'бавно',               translations: { en: 'slowly',             fr: 'lentement',           ar: 'ببطء',              fa: 'به آرامی',            ru: 'медленно',                uk: 'повільно'            } },
    { id: 'burzo',       bulgarian: 'бързо',               translations: { en: 'quickly, fast',      fr: 'vite, rapidement',    ar: 'بسرعة',             fa: 'سریع',                ru: 'быстро',                  uk: 'швидко'              } },
    { id: 'veднага',     bulgarian: 'веднага',             translations: { en: 'immediately',        fr: 'immédiatement',       ar: 'فوراً',             fa: 'فوری',                ru: 'немедленно',              uk: 'негайно'             } },
    { id: 'vzimam',      bulgarian: 'взимам (вземам), -аш',translations: { en: 'to take',            fr: 'prendre',             ar: 'يأخذ',              fa: 'گرفتن',               ru: 'брать',                   uk: 'брати'               } },
    { id: 'vizhdam',     bulgarian: 'виждам, -аш',         translations: { en: 'to see',             fr: 'voir',                ar: 'يرى',               fa: 'دیدن',                ru: 'видеть',                  uk: 'бачити'              } },
    { id: 'vinagi',      bulgarian: 'винаги',              translations: { en: 'always',             fr: 'toujours',            ar: 'دائماً',            fa: 'همیشه',               ru: 'всегда',                  uk: 'завжди'              } },
    { id: 'vlizam',      bulgarian: 'влизам, -аш',         translations: { en: 'to enter',           fr: 'entrer',              ar: 'يدخل',              fa: 'وارد شدن',            ru: 'входить',                 uk: 'входити'             } },
    { id: 'vsi4ki',      bulgarian: 'всички',              translations: { en: 'everyone, all',      fr: 'tout le monde, tous', ar: 'الجميع',            fa: 'همه',                 ru: 'все',                     uk: 'всі'                 } },
    { id: 'vseki',       bulgarian: 'всеки, всяка, всяко', translations: { en: 'every',              fr: 'chaque',              ar: 'كل',                fa: 'هر',                  ru: 'каждый',                  uk: 'кожен'               } },
    { id: 'gladan',      bulgarian: 'гладен, -дна, -о, -и', translations: { en: 'hungry',            fr: 'affamé',              ar: 'جائع',              fa: 'گرسنه',               ru: 'голодный',                uk: 'голодний'            } },
    { id: 'gledam',      bulgarian: 'гледам, -аш',         translations: { en: 'to watch, to look',  fr: 'regarder',            ar: 'ينظر، يشاهد',       fa: 'نگاه کردن',           ru: 'смотреть',                uk: 'дивитися'            } },
    { id: 'gost',        bulgarian: 'гост, -и',            translations: { en: 'guest',              fr: 'invité',              ar: 'ضيف',               fa: 'مهمان',               ru: 'гость',                   uk: 'гість'               } },
    { id: 'gotvya',      bulgarian: 'готвя, -иш',          translations: { en: 'to cook',            fr: 'cuisiner',            ar: 'يطبخ',              fa: 'پختن',                ru: 'готовить',                uk: 'готувати'            } },
    { id: 'dobre',       bulgarian: 'добре',               translations: { en: 'well',               fr: 'bien',                ar: 'بشكل جيد',          fa: 'خوب',                 ru: 'хорошо',                  uk: 'добре'               } },
    { id: 'dovolen',     bulgarian: 'доволен, -лна, -о, -и', translations: { en: 'satisfied, pleased', fr: 'satisfait',         ar: 'راضٍ',              fa: 'راضی',                ru: 'довольный',               uk: 'задоволений'         } },
    { id: 'zaedno',      bulgarian: 'заедно',              translations: { en: 'together',           fr: 'ensemble',            ar: 'معاً',              fa: 'با هم',               ru: 'вместе',                  uk: 'разом'               } },
    { id: 'zapochwam',   bulgarian: 'започвам, -аш',       translations: { en: 'to start, to begin', fr: 'commencer',           ar: 'يبدأ',              fa: 'شروع کردن',           ru: 'начинать',                uk: 'починати'            } },
    { id: 'zatvarqm',    bulgarian: 'затварям, -аш',       translations: { en: 'to close',           fr: 'fermer',              ar: 'يغلق',              fa: 'بستن',                ru: 'закрывать',               uk: 'закривати'           } },
    { id: 'zle',         bulgarian: 'зле',                 translations: { en: 'badly, poorly',      fr: 'mal',                 ar: 'بشكل سيء',          fa: 'بد',                  ru: 'плохо',                   uk: 'погано'              } },
    { id: 'igraya',      bulgarian: 'играя, -еш',          translations: { en: 'to play',            fr: 'jouer',               ar: 'يلعب',              fa: 'بازی کردن',           ru: 'играть',                  uk: 'грати'               } },
    { id: 'idvam',       bulgarian: 'идвам, -аш',          translations: { en: 'to come',            fr: 'venir',               ar: 'يأتي',              fa: 'آمدن',                ru: 'приходить',               uk: 'приходити'           } },
    { id: 'izlizam',     bulgarian: 'излизам, -аш',        translations: { en: 'to go out',          fr: 'sortir',              ar: 'يخرج',              fa: 'بیرون رفتن',          ru: 'выходить',                uk: 'виходити'            } },
    { id: 'imejl',       bulgarian: 'имейл',               translations: { en: 'email',              fr: 'courriel, e-mail',    ar: 'بريد إلكتروني',     fa: 'ایمیل',               ru: 'электронное письмо',      uk: 'електронний лист'    } },
    { id: 'kazwam-se',   bulgarian: 'казвам се, -аш',      translations: { en: 'to be called',       fr: "s'appeler",           ar: 'يُدعى',             fa: 'نام داشتن',           ru: 'называться',              uk: "називатися"          } },
    { id: 'kazwam',      bulgarian: 'казвам, -аш',         translations: { en: 'to say, to tell',    fr: 'dire',                ar: 'يقول',              fa: 'گفتن',                ru: 'говорить, сказать',       uk: 'казати'              } },
    { id: 'kanya',       bulgarian: 'каня, -иш',           translations: { en: 'to invite',          fr: 'inviter',             ar: 'يدعو',              fa: 'دعوت کردن',           ru: 'приглашать',              uk: 'запрошувати'         } },
    { id: 'kniga',       bulgarian: 'книга',               translations: { en: 'book',               fr: 'livre',               ar: 'كتاب',              fa: 'کتاب',                ru: 'книга',                   uk: 'книга'               } },
    { id: 'kolko-chesto', bulgarian: 'Колко често?',       translations: { en: 'How often?',         fr: 'Combien de fois ?',   ar: 'كم مرة؟',           fa: 'چند بار؟',            ru: 'Как часто?',              uk: 'Як часто?'           } },
    { id: 'kusno',       bulgarian: 'късно',               translations: { en: 'late',               fr: 'tard',                ar: 'متأخراً',           fa: 'دیر',                 ru: 'поздно',                  uk: 'пізно'               } },
    { id: 'lyagam-si',   bulgarian: 'лягам си, -аш',       translations: { en: 'to go to bed',       fr: 'se coucher',          ar: 'يذهب للنوم',        fa: 'خوابیدن',             ru: 'ложиться спать',          uk: 'лягати спати'        } },
    { id: 'miya-se',     bulgarian: 'мия (се), -еш',       translations: { en: 'to wash (oneself)',   fr: 'se laver',            ar: 'يغسل (نفسه)',       fa: 'شستن (خود)',          ru: 'мыться',                  uk: 'митися'              } },
    { id: 'muzika',      bulgarian: 'музика',              translations: { en: 'music',              fr: 'musique',             ar: 'موسيقى',            fa: 'موسیقی',              ru: 'музыка',                  uk: 'музика'              } },
    { id: 'navun',       bulgarian: 'навън',               translations: { en: 'outside',            fr: 'dehors',              ar: 'في الخارج',         fa: 'بیرون',               ru: 'снаружи',                 uk: 'надворі'             } },
    { id: 'nikoga',      bulgarian: 'никога',              translations: { en: 'never',              fr: 'jamais',              ar: 'أبداً',             fa: 'هرگز',                ru: 'никогда',                 uk: 'ніколи'              } },
    { id: 'obiknoveno',  bulgarian: 'обикновено',          translations: { en: 'usually',            fr: 'généralement',        ar: 'عادةً',             fa: 'معمولاً',             ru: 'обычно',                  uk: 'зазвичай'            } },
    { id: 'oblicham-se', bulgarian: 'обличам (се), -аш',   translations: { en: 'to get dressed',     fr: "s'habiller",          ar: 'يلبس (نفسه)',       fa: 'پوشیدن',              ru: 'одеваться',               uk: 'одягатися'           } },
    { id: 'obuvam-se',   bulgarian: 'обувам (се), -аш',    translations: { en: 'to put on shoes',    fr: 'mettre ses chaussures', ar: 'يلبس الحذاء',     fa: 'کفش پوشیدن',          ru: 'обуваться',               uk: 'взуватися'           } },
    { id: 'otivam',      bulgarian: 'отивам, -аш',         translations: { en: 'to go',              fr: 'aller',               ar: 'يذهب',              fa: 'رفتن',                ru: 'идти / ехать',            uk: 'іти / їхати'         } },
    { id: 'pisha',       bulgarian: 'пиша, -еш',           translations: { en: 'to write',           fr: 'écrire',              ar: 'يكتب',              fa: 'نوشتن',               ru: 'писать',                  uk: 'писати'              } },
    { id: 'ponqkoga',    bulgarian: 'понякога',            translations: { en: 'sometimes',          fr: 'parfois',             ar: 'أحياناً',           fa: 'گاهی',                ru: 'иногда',                  uk: 'іноді'               } },
    { id: 'pravya',      bulgarian: 'правя, -иш',          translations: { en: 'to do, to make',     fr: 'faire',               ar: 'يفعل، يصنع',        fa: 'کردن، ساختن',         ru: 'делать',                  uk: 'робити'              } },
    { id: 'prikaska',    bulgarian: 'приказка',            translations: { en: 'fairytale, story',   fr: 'conte',               ar: 'قصة خيالية',        fa: 'افسانه',              ru: 'сказка',                  uk: 'казка'               } },
    { id: 'rano',        bulgarian: 'рано',                translations: { en: 'early',              fr: 'tôt',                 ar: 'مبكراً',            fa: 'زود',                 ru: 'рано',                    uk: 'рано'                } },
    { id: 'ryadko',      bulgarian: 'рядко',               translations: { en: 'rarely',             fr: 'rarement',            ar: 'نادراً',            fa: 'به ندرت',             ru: 'редко',                   uk: 'рідко'               } },
    { id: 'svaтba',      bulgarian: 'сватба',              translations: { en: 'wedding',            fr: 'mariage',             ar: 'حفل زفاف',          fa: 'عروسی',               ru: 'свадьба',                 uk: 'весілля'             } },
    { id: 'svurshvam',   bulgarian: 'свършвам, -аш',       translations: { en: 'to finish',          fr: 'terminer',            ar: 'ينهي',              fa: 'تمام کردن',           ru: 'заканчивать',             uk: 'закінчувати'         } },
    { id: 'slushram',    bulgarian: 'слушам, -аш',         translations: { en: 'to listen to',       fr: 'écouter',             ar: 'يستمع إلى',         fa: 'گوش دادن به',         ru: 'слушать',                 uk: 'слухати'             } },
    { id: 'spya',        bulgarian: 'спя, -иш',            translations: { en: 'to sleep',           fr: 'dormir',              ar: 'ينام',              fa: 'خوابیدن',             ru: 'спать',                   uk: 'спати'               } },
    { id: 'sreshtam-se', bulgarian: 'срещам се, -аш',      translations: { en: 'to meet',            fr: 'se rencontrer',       ar: 'يلتقي',             fa: 'ملاقات کردن',         ru: 'встречаться',             uk: 'зустрічатися'        } },
    { id: 'stavom',      bulgarian: 'ставам, -аш',         translations: { en: 'to get up',          fr: 'se lever',            ar: 'يستيقظ',            fa: 'بلند شدن',            ru: 'вставать',                uk: 'вставати'            } },
    { id: 'subtlicham-se', bulgarian: 'събличам (се), -аш', translations: { en: 'to undress',        fr: 'se déshabiller',      ar: 'يخلع ملابسه',       fa: 'لباس کندن',           ru: 'раздеваться',             uk: 'роздягатися'         } },
    { id: 'subtuvam-se', bulgarian: 'събувам (се), -аш',   translations: { en: 'to take off shoes',  fr: 'enlever ses chaussures', ar: 'يخلع حذاءه',      fa: 'کفش درآوردن',         ru: 'разуваться',              uk: 'роззуватися'         } },
    { id: 'televiziya',  bulgarian: 'телевизия',           translations: { en: 'television, TV',     fr: 'télévision',          ar: 'تلفزيون',           fa: 'تلویزیون',            ru: 'телевидение',             uk: 'телебачення'         } },
    { id: 'tancuvam',    bulgarian: 'танцувам, -аш',       translations: { en: 'to dance',           fr: 'danser',              ar: 'يرقص',              fa: 'رقصیدن',              ru: 'танцевать',               uk: 'танцювати'           } },
    { id: 'ticham',      bulgarian: 'тичам, -аш',          translations: { en: 'to run',             fr: 'courir',              ar: 'يجري',              fa: 'دویدن',               ru: 'бегать',                  uk: 'бігати'              } },
    { id: 'traditsiya',  bulgarian: 'традиция',            translations: { en: 'tradition',          fr: 'tradition',           ar: 'تقليد',             fa: 'سنت',                 ru: 'традиция',                uk: 'традиція'            } },
    { id: 'tryabva',     bulgarian: 'трябва',              translations: { en: 'should, must, need to', fr: 'devoir, falloir',  ar: 'يجب',               fa: 'باید',                ru: 'нужно, надо',             uk: 'треба, потрібно'     } },
    { id: 'hodya',       bulgarian: 'ходя, -иш',           translations: { en: 'to walk, to go',     fr: 'aller (habituellement)', ar: 'يمشي، يذهب',     fa: 'رفتن (معمول)',        ru: 'ходить (регулярно)',       uk: 'ходити'              } },
    { id: 'chesto',      bulgarian: 'често',               translations: { en: 'often',              fr: 'souvent',             ar: 'كثيراً',            fa: 'اغلب',                ru: 'часто',                   uk: 'часто'               } },
    { id: 'cheta',       bulgarian: 'чета, -еш',           translations: { en: 'to read',            fr: 'lire',                ar: 'يقرأ',              fa: 'خواندن',              ru: 'читать',                  uk: 'читати'              } },
    { id: 'chistya',     bulgarian: 'чистя, -иш',          translations: { en: 'to clean',           fr: 'nettoyer',            ar: 'ينظف',              fa: 'تمیز کردن',           ru: 'убирать',                 uk: 'прибирати'           } },
    { id: 'shастлив',    bulgarian: 'щастлив, -а, -о, -и', translations: { en: 'happy',              fr: 'heureux',             ar: 'سعيد',              fa: 'خوشحال',              ru: 'счастливый',              uk: 'щасливий'            } },
    { id: 'vrushтam-se', bulgarian: 'връщам се, -аш',      translations: { en: 'to come back',       fr: 'rentrer, revenir',    ar: 'يعود',              fa: 'برگشتن',              ru: 'возвращаться',            uk: 'повертатися'         } },
    { id: 'vrushтam',    bulgarian: 'връщам, -аш',         translations: { en: 'to give back, return', fr: 'rendre, rapporter', ar: 'يُعيد',             fa: 'پس دادن',             ru: 'возвращать',              uk: 'повертати'           } },
  ],

  culturalNotes: [
    {
      id: 'l11-culture-01',
      title: {
        bg: 'Вечерята — семейно събиране',
        en: 'Dinner — a family gathering',
        fr: 'Le dîner — un rassemblement familial',
        ar: 'العشاء — تجمّع عائلي',
        fa: 'شام — گردهمایی خانوادگی',
        ru: 'Ужин — семейное собрание',
        uk: 'Вечеря — сімейне зібрання',
      },
      content: {
        bg: 'Вечерта цялото семейство се събира, за да яде заедно. Вечерята е основното хранене на деня. Семейната трапеза е важна традиция в България.',
        en: 'In the evenings, the whole family gathers to eat together. Dinner is the main meal of the day. The family table is an important tradition in Bulgaria.',
        fr: 'Le soir, toute la famille se réunit pour manger ensemble. Le dîner est le repas principal de la journée. La table familiale est une tradition importante en Bulgarie.',
        ar: 'في المساء، تجتمع العائلة بأكملها لتناول الطعام معاً. العشاء هو الوجبة الرئيسية في اليوم. طاولة الأسرة تقليد مهم في بلغاريا.',
        fa: 'عصرها تمام خانواده برای خوردن غذا با هم جمع می‌شوند. شام وعده اصلی روز است. سفره خانوادگی یک سنت مهم در بلغارستان است.',
        ru: 'Вечером вся семья собирается, чтобы поесть вместе. Ужин — главный приём пищи за день. Семейный стол — важная традиция в Болгарии.',
        uk: 'Ввечері вся сім\'я збирається, щоб поїсти разом. Вечеря — головний прийом їжі дня. Сімейний стіл — важлива традиція в Болгарії.',
      },
    },
    {
      id: 'l11-culture-02',
      title: {
        bg: 'Кафе с приятели',
        en: 'Coffee with friends',
        fr: 'Un café entre amis',
        ar: 'القهوة مع الأصدقاء',
        fa: 'قهوه با دوستان',
        ru: 'Кофе с друзьями',
        uk: 'Кава з друзями',
      },
      content: {
        bg: 'Типично за българите е да прекарват дълго в кафенетата (2–3 часа), да разговарят и да пият кафе с приятели. Кафенетата са важно място за социален живот.',
        en: 'It is typical for Bulgarians to stay at cafes for a long time (2–3 hours), to chat and have coffee with friends. Cafes are an important place for social life.',
        fr: 'Il est typique chez les Bulgares de rester longtemps dans les cafés (2–3 heures), de discuter et de prendre un café entre amis. Les cafés sont un lieu important de la vie sociale.',
        ar: 'من المعتاد للبلغاريين البقاء طويلاً في المقاهي (من ساعتين إلى ثلاث ساعات)، والتحدث وشرب القهوة مع الأصدقاء. المقاهي مكان مهم للحياة الاجتماعية.',
        fa: 'برای بلغاری‌ها معمول است که مدت طولانی (۲ تا ۳ ساعت) در کافه‌ها بنشینند، صحبت کنند و با دوستان قهوه بنوشند. کافه‌ها جای مهمی برای زندگی اجتماعی هستند.',
        ru: 'Для болгар характерно подолгу сидеть в кафе (2–3 часа), общаться и пить кофе с друзьями. Кафе — важное место для социальной жизни.',
        uk: 'Для болгар типово довго сидіти в кав\'ярнях (2–3 години), спілкуватися і пити каву з друзями. Кав\'ярні — важливе місце соціального життя.',
      },
    },
    {
      id: 'l11-culture-03',
      title: {
        bg: 'Уикендът в селото',
        en: 'Weekends in the village',
        fr: 'Le week-end à la campagne',
        ar: 'عطلة نهاية الأسبوع في القرية',
        fa: 'آخر هفته در روستا',
        ru: 'Выходные в деревне',
        uk: 'Вихідні у селі',
      },
      content: {
        bg: 'В събота и неделя много българи отиват на село, където посещават роднините си и почиват. Много хора имат ниви в селата и отглеждат собствени плодове и зеленчуци.',
        en: 'On Saturdays and Sundays, many Bulgarians go to the countryside or to a village where they visit their relatives and relax. Many people also have fields in their villages and grow their own fruits and vegetables.',
        fr: 'Le samedi et le dimanche, beaucoup de Bulgares vont à la campagne ou au village pour rendre visite à leurs proches et se reposer. Beaucoup ont aussi des champs dans leur village et cultivent leurs propres fruits et légumes.',
        ar: 'في السبت والأحد، يذهب كثير من البلغاريين إلى الريف أو القرية لزيارة أقاربهم والاسترخاء. كثيرون منهم لديهم حقول في القرى ويزرعون فاكهتهم وخضارهم.',
        fa: 'در روزهای شنبه و یکشنبه، بسیاری از بلغاری‌ها به روستا می‌روند تا از بستگان خود دیدن کنند و استراحت کنند. بسیاری از مردم هم مزارعی در روستاها دارند و میوه و سبزیجات خود را می‌کارند.',
        ru: 'В субботу и воскресенье многие болгары едут в деревню, где навещают родственников и отдыхают. У многих есть поля в деревнях, и они выращивают свои фрукты и овощи.',
        uk: 'В суботу та неділю багато болгар їдуть у село, де навідують родичів та відпочивають. Багато людей мають поля в селах і вирощують власні фрукти та овочі.',
      },
    },
    {
      id: 'l11-culture-04',
      title: {
        bg: 'Сватбите в България',
        en: 'Weddings in Bulgaria',
        fr: 'Les mariages en Bulgarie',
        ar: 'حفلات الزفاف في بلغاريا',
        fa: 'عروسی‌ها در بلغارستان',
        ru: 'Свадьбы в Болгарии',
        uk: 'Весілля в Болгарії',
      },
      content: {
        bg: 'Сватбите в България са голямо събитие за цялото семейство. Те продължават обикновено два дни — събота и неделя. На сватбата хората канят много гости, слушат музика, танцуват и ядат вкусна храна. Родителите дават сватба на децата си с много радост и традиции.',
        en: 'Weddings in Bulgaria are a big event for the whole family. They usually last two days — Saturday and Sunday. At weddings, people invite many guests, listen to music, dance and eat delicious food. Parents hold weddings for their children with great joy and traditions.',
        fr: 'Les mariages en Bulgarie sont un grand événement pour toute la famille. Ils durent généralement deux jours — le samedi et le dimanche. Lors des mariages, on invite de nombreux invités, on écoute de la musique, on danse et on mange de la bonne nourriture. Les parents organisent les mariages de leurs enfants avec beaucoup de joie et de tradition.',
        ar: 'حفلات الزفاف في بلغاريا حدث كبير لكل الأسرة. وعادةً ما تمتد يومين — السبت والأحد. في حفل الزفاف، يدعو الناس كثيراً من الضيوف، ويستمعون إلى الموسيقى، ويرقصون ويتناولون الطعام اللذيذ.',
        fa: 'عروسی‌ها در بلغارستان رویداد بزرگی برای تمام خانواده هستند. معمولاً دو روز طول می‌کشند — شنبه و یکشنبه. در عروسی، مردم مهمانان زیادی دعوت می‌کنند، موسیقی گوش می‌دهند، می‌رقصند و غذای خوشمزه می‌خورند.',
        ru: 'Свадьбы в Болгарии — большое событие для всей семьи. Они, как правило, длятся два дня — в субботу и воскресенье. На свадьбах приглашают много гостей, слушают музыку, танцуют и едят вкусную еду.',
        uk: 'Весілля в Болгарії — велика подія для всієї сім\'ї. Зазвичай тривають два дні — в суботу та неділю. На весіллі люди запрошують багато гостей, слухають музику, танцюють і їдять смачну їжу.',
      },
    },
  ],

  grammarReference: [],
};
