import type { LessonContent } from '@/content/types';

export const content: LessonContent = {
  introduction:
    'В осмия урок ще научите думи за цветовете и дрехите. Ще можете да описвате какво носите, да разговаряте в магазин за дрехи, да използвате показателни местоимения (този, тази, това, тези) и да членувате прилагателните.',

  sections: [],

  dialogues: [
    {
      id: 'l08-dialozi-1-a',
      speakers: [
        { name: 'Клиент', text: 'Имате ли размер M от синята тениска?' },
        { name: 'Продавач', text: 'Съжалявам, нямаме. Искате ли L?' },
        { name: 'Клиент', text: 'Не, благодаря.' },
      ],
    },
    {
      id: 'l08-dialozi-1-b',
      speakers: [
        { name: 'Клиент', text: 'Имате ли обувки номер 38?' },
        { name: 'Продавач', text: 'Да, имаме, но само черни. Искате ли?' },
        { name: 'Клиент', text: 'Да, благодаря.' },
      ],
    },
    {
      id: 'l08-dialozi-2-a',
      speakers: [
        { name: 'Клиент', text: 'Извинете, може ли тази тениска?' },
        { name: 'Продавач', text: 'Бялата?' },
        { name: 'Клиент', text: 'Не, червената.' },
        { name: 'Продавач', text: 'Заповядайте!' },
        { name: 'Клиент', text: 'Благодаря!' },
      ],
    },
    {
      id: 'l08-dialozi-2-b',
      speakers: [
        { name: 'Клиент', text: 'Може ли зеленото яке?' },
        { name: 'Продавач', text: 'Да, разбира се. Кой номер искате?' },
        { name: 'Клиент', text: 'Номер 46.' },
      ],
    },
    {
      id: 'l08-dialozi-2-v',
      speakers: [
        { name: 'Продавач', text: 'Как е якето?' },
        { name: 'Клиент', text: 'Малко е. Може ли номер 48?' },
        { name: 'Продавач', text: 'Да, разбира се.' },
      ],
    },
  ],

  vocabulary: [
    { id: 'byal', bulgarian: 'бял, бяла, бяло, бели', translations: { en: 'white', fr: 'blanc', ar: 'أبيض', fa: 'سفید', ru: 'белый', uk: 'білий' } },
    { id: 'bluza', bulgarian: 'блуза', translations: { en: 'blouse', fr: 'blouse / chemisier', ar: 'بلوزة', fa: 'بلوز', ru: 'блуза', uk: 'блузка' } },
    { id: 'boti', bulgarian: 'боти', translations: { en: 'low boots', fr: 'bottines', ar: 'أحذية قصيرة', fa: 'نیم‌بوت', ru: 'полуботинки', uk: 'черевики' } },
    { id: 'botushi', bulgarian: 'ботуши', translations: { en: 'high boots', fr: 'bottes', ar: 'أحذية طويلة', fa: 'بوت بلند', ru: 'сапоги', uk: 'чоботи' } },
    { id: 'valnen', bulgarian: 'вълнен, вълнена, вълнено, вълнени', translations: { en: 'wool (adj.)', fr: 'en laine', ar: 'صوف (صفة)', fa: 'پشمی', ru: 'шерстяной', uk: 'вовняний' } },
    { id: 'dechitsa', bulgarian: 'дечица', translations: { en: 'kids', fr: 'gamins', ar: 'أطفال صغار', fa: 'بچه‌ها', ru: 'детишки', uk: 'дітки' } },
    { id: 'dzhapanki', bulgarian: 'джапанки', translations: { en: 'flip flops', fr: 'tongs', ar: 'شبشب', fa: 'دمپایی', ru: 'шлёпанцы', uk: 'в\'єтнамки' } },
    { id: 'dreha', bulgarian: 'дреха', translations: { en: 'garment', fr: 'vêtement', ar: 'ملابس', fa: 'لباس', ru: 'одежда', uk: 'одяг' } },
    { id: 'danki', bulgarian: 'дънки', translations: { en: 'jeans', fr: 'jean', ar: 'جينز', fa: 'شلوار جین', ru: 'джинсы', uk: 'джинси' } },
    { id: 'zhalt', bulgarian: 'жълт, жълта, жълто, жълти', translations: { en: 'yellow', fr: 'jaune', ar: 'أصفر', fa: 'زرد', ru: 'жёлтый', uk: 'жовтий' } },
    { id: 'zapalka', bulgarian: 'запалка', translations: { en: 'lighter', fr: 'briquet', ar: 'ولاعة', fa: 'فندک', ru: 'зажигалка', uk: 'запальничка' } },
    { id: 'zelen', bulgarian: 'зелен, зелена, зелено, зелени', translations: { en: 'green', fr: 'vert', ar: 'أخضر', fa: 'سبز', ru: 'зелёный', uk: 'зелений' } },
    { id: 'zname', bulgarian: 'знаме', translations: { en: 'flag', fr: 'drapeau', ar: 'علم', fa: 'پرچم', ru: 'флаг', uk: 'прапор' } },
    { id: 'kafyav', bulgarian: 'кафяв, кафява, кафяво, кафяви', translations: { en: 'brown', fr: 'marron / brun', ar: 'بني', fa: 'قهوه‌ای', ru: 'коричневый', uk: 'коричневий' } },
    { id: 'kitara', bulgarian: 'китара', translations: { en: 'guitar', fr: 'guitare', ar: 'غيتار', fa: 'گیتار', ru: 'гитара', uk: 'гітара' } },
    { id: 'klyuch', bulgarian: 'ключ, ключове', translations: { en: 'key, keys', fr: 'clé, clés', ar: 'مفتاح، مفاتيح', fa: 'کلید، کلیدها', ru: 'ключ, ключи', uk: 'ключ, ключі' } },
    { id: 'kolan', bulgarian: 'колан', translations: { en: 'belt', fr: 'ceinture', ar: 'حزام', fa: 'کمربند', ru: 'ремень', uk: 'ремінь' } },
    { id: 'kostyum', bulgarian: 'костюм', translations: { en: 'suit', fr: 'costume', ar: 'بدلة', fa: 'کت و شلوار', ru: 'костюм', uk: 'костюм' } },
    { id: 'kreditna-karta', bulgarian: 'кредитна карта', translations: { en: 'credit card', fr: 'carte de crédit', ar: 'بطاقة ائتمان', fa: 'کارت اعتباری', ru: 'кредитная карта', uk: 'кредитна картка' } },
    { id: 'debitna-karta', bulgarian: 'дебитна карта', translations: { en: 'debit card', fr: 'carte de débit', ar: 'بطاقة خصم', fa: 'کارت نقدی', ru: 'дебетовая карта', uk: 'дебетна картка' } },
    { id: 'kasi-pantaloni', bulgarian: 'къси панталони', translations: { en: 'shorts', fr: 'short', ar: 'شورت', fa: 'شلوارک', ru: 'шорты', uk: 'шорти' } },
    { id: 'lek', bulgarian: 'лек, лека, леко, леки', translations: { en: 'light', fr: 'léger', ar: 'خفيف', fa: 'سبک', ru: 'лёгкий', uk: 'легкий' } },
    { id: 'lilav', bulgarian: 'лилав, лилава, лилаво, лилави', translations: { en: 'purple', fr: 'violet', ar: 'بنفسجي', fa: 'بنفش', ru: 'фиолетовый', uk: 'фіолетовий' } },
    { id: 'lichna-karta', bulgarian: 'лична карта', translations: { en: 'ID card', fr: 'carte d\'identité', ar: 'بطاقة هوية', fa: 'کارت شناسایی', ru: 'удостоверение личности', uk: 'посвідчення особи' } },
    { id: 'maratonki', bulgarian: 'маратонки', translations: { en: 'sneakers', fr: 'baskets', ar: 'حذاء رياضي', fa: 'کتانی', ru: 'кроссовки', uk: 'кросівки' } },
    { id: 'nay-mnogo', bulgarian: 'най-много (обичам)', translations: { en: 'the most / the best (like)', fr: 'le plus (aimer)', ar: 'الأكثر (أحب)', fa: 'بیشترین (دوست داشتن)', ru: 'больше всего (любить)', uk: 'найбільше (любити)' } },
    { id: 'no', bulgarian: 'но', translations: { en: 'but', fr: 'mais', ar: 'لكن', fa: 'اما', ru: 'но', uk: 'але' } },
    { id: 'nomer', bulgarian: 'номер', translations: { en: 'size (number)', fr: 'taille (pointure)', ar: 'مقاس', fa: 'سایز', ru: 'размер (номер)', uk: 'розмір (номер)' } },
    { id: 'nosya', bulgarian: 'нося, носиш', translations: { en: 'to wear', fr: 'porter (un vêtement)', ar: 'أرتدي', fa: 'پوشیدن', ru: 'носить (одежду)', uk: 'носити (одяг)' } },
    { id: 'obuvka', bulgarian: 'обувка, обувки', translations: { en: 'shoe, shoes', fr: 'chaussure, chaussures', ar: 'حذاء، أحذية', fa: 'کفش، کفش‌ها', ru: 'туфля, туфли', uk: 'туфля, туфлі' } },
    { id: 'ogledalo', bulgarian: 'огледало', translations: { en: 'mirror', fr: 'miroir', ar: 'مرآة', fa: 'آینه', ru: 'зеркало', uk: 'дзеркало' } },
    { id: 'oranzhev', bulgarian: 'оранжев, оранжева, оранжево, оранжеви', translations: { en: 'orange', fr: 'orange', ar: 'برتقالي', fa: 'نارنجی', ru: 'оранжевый', uk: 'помаранчевий' } },
    { id: 'ofitsialen', bulgarian: 'официален, официална, официално, официални', translations: { en: 'official, formal', fr: 'officiel, formel', ar: 'رسمي', fa: 'رسمی', ru: 'официальный, формальный', uk: 'офіційний, формальний' } },
    { id: 'ochila', bulgarian: 'очила', translations: { en: 'glasses', fr: 'lunettes', ar: 'نظارات', fa: 'عینک', ru: 'очки', uk: 'окуляри' } },
    { id: 'palto', bulgarian: 'палто', translations: { en: 'coat', fr: 'manteau', ar: 'معطف', fa: 'پالتو', ru: 'пальто', uk: 'пальто' } },
    { id: 'pamuchen', bulgarian: 'памучен, памучна, памучно, памучни', translations: { en: 'cotton (adj.)', fr: 'en coton', ar: 'قطني', fa: 'نخی', ru: 'хлопковый', uk: 'бавовняний' } },
    { id: 'pantalon', bulgarian: 'панталон', translations: { en: 'trousers', fr: 'pantalon', ar: 'بنطلون', fa: 'شلوار', ru: 'брюки', uk: 'штани' } },
    { id: 'pari', bulgarian: 'пари', translations: { en: 'money', fr: 'argent', ar: 'مال', fa: 'پول', ru: 'деньги', uk: 'гроші' } },
    { id: 'pasport', bulgarian: 'паспорт', translations: { en: 'passport', fr: 'passeport', ar: 'جواز سفر', fa: 'پاسپورت', ru: 'паспорт', uk: 'паспорт' } },
    { id: 'pola', bulgarian: 'пола', translations: { en: 'skirt', fr: 'jupe', ar: 'تنورة', fa: 'دامن', ru: 'юбка', uk: 'спідниця' } },
    { id: 'portmone', bulgarian: 'портмоне', translations: { en: 'wallet', fr: 'portefeuille', ar: 'محفظة', fa: 'کیف پول', ru: 'кошелёк', uk: 'гаманець' } },
    { id: 'predpochitam', bulgarian: 'предпочитам, предпочиташ', translations: { en: 'to prefer', fr: 'préférer', ar: 'أفضّل', fa: 'ترجیح دادن', ru: 'предпочитать', uk: 'надавати перевагу' } },
    { id: 'pulover', bulgarian: 'пуловер', translations: { en: 'pullover', fr: 'pull', ar: 'بلوفر', fa: 'ژاکت / پلیور', ru: 'пуловер', uk: 'пуловер' } },
    { id: 'razmer', bulgarian: 'размер', translations: { en: 'size', fr: 'taille', ar: 'مقاس', fa: 'اندازه', ru: 'размер', uk: 'розмір' } },
    { id: 'riza', bulgarian: 'риза', translations: { en: 'shirt', fr: 'chemise', ar: 'قميص', fa: 'پیراهن', ru: 'рубашка', uk: 'сорочка' } },
    { id: 'rozov', bulgarian: 'розов, розова, розово, розови', translations: { en: 'pink', fr: 'rose', ar: 'زهري', fa: 'صورتی', ru: 'розовый', uk: 'рожевий' } },
    { id: 'roklya', bulgarian: 'рокля', translations: { en: 'dress', fr: 'robe', ar: 'فستان', fa: 'لباس مجلسی', ru: 'платье', uk: 'сукня' } },
    { id: 'rakavitsa', bulgarian: 'ръкавица, ръкавици', translations: { en: 'glove, gloves / mitten, mittens', fr: 'gant, gants / moufle, moufles', ar: 'قفاز، قفازات', fa: 'دستکش، دستکش‌ها', ru: 'перчатка, перчатки', uk: 'рукавиця, рукавиці' } },
    { id: 'sako', bulgarian: 'сако', translations: { en: 'jacket', fr: 'veste', ar: 'جاكيت', fa: 'کت', ru: 'пиджак', uk: 'піджак' } },
    { id: 'sandali', bulgarian: 'сандали', translations: { en: 'sandals', fr: 'sandales', ar: 'صندل', fa: 'صندل', ru: 'сандалии', uk: 'сандалі' } },
    { id: 'siv', bulgarian: 'сив, сива, сиво, сиви', translations: { en: 'grey', fr: 'gris', ar: 'رمادي', fa: 'خاکستری', ru: 'серый', uk: 'сірий' } },
    { id: 'sin', bulgarian: 'син, синя, синьо, сини', translations: { en: 'blue', fr: 'bleu', ar: 'أزرق', fa: 'آبی', ru: 'синий', uk: 'синій' } },
    { id: 'slanchevi-ochila', bulgarian: 'слънчеви очила', translations: { en: 'sunglasses', fr: 'lunettes de soleil', ar: 'نظارات شمسية', fa: 'عینک آفتابی', ru: 'солнечные очки', uk: 'сонцезахисні окуляри' } },
    { id: 'sporten', bulgarian: 'спортен, спортна, спортно, спортни', translations: { en: 'sports (adj.)', fr: 'sportif', ar: 'رياضي (صفة)', fa: 'ورزشی', ru: 'спортивный', uk: 'спортивний' } },
    { id: 'tam', bulgarian: 'там', translations: { en: 'there', fr: 'là', ar: 'هناك', fa: 'آنجا', ru: 'там', uk: 'там' } },
    { id: 'telefon-gsm', bulgarian: 'телефон (GSM)', translations: { en: 'telephone (mobile phone)', fr: 'téléphone (portable)', ar: 'هاتف (جوال)', fa: 'تلفن (موبایل)', ru: 'телефон (мобильный)', uk: 'телефон (мобільний)' } },
    { id: 'teniska', bulgarian: 'тениска', translations: { en: 't-shirt', fr: 't-shirt', ar: 'تي شيرت', fa: 'تی‌شرت', ru: 'футболка', uk: 'футболка' } },
    { id: 'tozi', bulgarian: 'този, тази, това, тези', translations: { en: 'this, these', fr: 'ce / cette / ces', ar: 'هذا، هذه، هؤلاء', fa: 'این، این‌ها', ru: 'этот, эта, это, эти', uk: 'цей, ця, це, ці' } },
    { id: 'treva', bulgarian: 'трева', translations: { en: 'grass', fr: 'herbe', ar: 'عشب', fa: 'چمن', ru: 'трава', uk: 'трава' } },
    { id: 'udoben', bulgarian: 'удобен, удобна, удобно, удобни', translations: { en: 'comfortable', fr: 'confortable', ar: 'مريح', fa: 'راحت', ru: 'удобный', uk: 'зручний' } },
    { id: 'himikalka', bulgarian: 'химикалка', translations: { en: 'pen', fr: 'stylo', ar: 'قلم', fa: 'خودکار', ru: 'ручка (шариковая)', uk: 'ручка (кулькова)' } },
    { id: 'tsvyat', bulgarian: 'цвят, цветове', translations: { en: 'colour, colours', fr: 'couleur, couleurs', ar: 'لون، ألوان', fa: 'رنگ، رنگ‌ها', ru: 'цвет, цвета', uk: 'колір, кольори' } },
    { id: 'chadar', bulgarian: 'чадър', translations: { en: 'umbrella', fr: 'parapluie', ar: 'مظلة', fa: 'چتر', ru: 'зонт', uk: 'парасоля' } },
    { id: 'chanta', bulgarian: 'чанта', translations: { en: 'bag', fr: 'sac', ar: 'حقيبة', fa: 'کیف', ru: 'сумка', uk: 'сумка' } },
    { id: 'cherven', bulgarian: 'червен, червена, червено, червени', translations: { en: 'red', fr: 'rouge', ar: 'أحمر', fa: 'قرمز', ru: 'красный', uk: 'червоний' } },
    { id: 'cheren', bulgarian: 'черен, черна, черно, черни', translations: { en: 'black', fr: 'noir', ar: 'أسود', fa: 'سیاه', ru: 'чёрный', uk: 'чорний' } },
    { id: 'chorapi', bulgarian: 'чорапи', translations: { en: 'socks', fr: 'chaussettes', ar: 'جوارب', fa: 'جوراب', ru: 'носки', uk: 'шкарпетки' } },
    { id: 'shal', bulgarian: 'шал', translations: { en: 'shawl / scarf', fr: 'écharpe / foulard', ar: 'شال / وشاح', fa: 'شال', ru: 'шарф', uk: 'шарф' } },
    { id: 'shapka', bulgarian: 'шапка', translations: { en: 'hat, cap', fr: 'bonnet / chapeau', ar: 'قبعة', fa: 'کلاه', ru: 'шапка', uk: 'шапка' } },
    { id: 'shofyorska-knizhka', bulgarian: 'шофьорска книжка', translations: { en: 'driving licence', fr: 'permis de conduire', ar: 'رخصة قيادة', fa: 'گواهینامه رانندگی', ru: 'водительское удостоверение', uk: 'водійське посвідчення' } },
    { id: 'yake', bulgarian: 'яке', translations: { en: 'jacket (casual)', fr: 'blouson', ar: 'جاكيت (غير رسمي)', fa: 'کاپشن', ru: 'куртка', uk: 'куртка' } },
    { id: 'zvanya', bulgarian: 'звъня, звъниш', translations: { en: 'to ring, to chime', fr: 'sonner', ar: 'يرنّ', fa: 'زنگ زدن', ru: 'звонить, звенеть', uk: 'дзвонити' } },
  ],

  culturalNotes: [
    {
      id: 'l08-culture-01',
      title: {
        bg: 'Облеклото в България',
        en: 'Clothing in Bulgaria',
        fr: 'Les vêtements en Bulgarie',
        ar: 'الملابس في بلغاريا',
        fa: 'لباس در بلغارستان',
        ru: 'Одежда в Болгарии',
        uk: 'Одяг у Болгарії',
      },
      content: {
        bg: 'Българите носят модерни западни дрехи. Обличат се внимателно дори за неофициални поводи.',
        en: 'Bulgarians wear modern Western-style clothing. They dress with care, even for informal occasions.',
        fr: "Les Bulgares portent des vêtements modernes de style occidental. Ils s'habillent avec soin, même pour des occasions informelles.",
        ar: 'يرتدي البلغاريون ملابس حديثة بالنمط الغربي. يهتمون بمظهرهم حتى في المناسبات غير الرسمية.',
        fa: 'بلغاری‌ها لباس‌های مدرن به سبک غربی می‌پوشند. آن‌ها حتی برای مناسبت‌های غیررسمی با دقت لباس می‌پوشند.',
        ru: 'Болгары носят современную одежду западного стиля. Одеваются аккуратно даже для неформальных случаев.',
        uk: 'Болгари носять сучасний одяг у западному стилі. Одягаються охайно навіть на неофіційні заходи.',
      },
    },
    {
      id: 'l08-culture-02',
      title: {
        bg: 'Народни носии',
        en: 'Traditional Costumes',
        fr: 'Costumes traditionnels',
        ar: 'الأزياء الشعبية التقليدية',
        fa: 'لباس‌های سنتی',
        ru: 'Народные костюмы',
        uk: 'Народні костюми',
      },
      content: {
        bg: 'Традиционните български носии се носят само на фестивали и при изпълнение на народни танци.',
        en: 'Traditional Bulgarian costumes are worn only at festivals and for dance performances.',
        fr: 'Les costumes traditionnels bulgares sont portés uniquement lors de festivals et de spectacles de danse.',
        ar: 'تُرتدى الأزياء الشعبية البلغارية التقليدية فقط في المهرجانات وعروض الرقص الشعبي.',
        fa: 'لباس‌های سنتی بلغاری فقط در جشنواره‌ها و اجراهای رقص پوشیده می‌شوند.',
        ru: 'Традиционные болгарские костюмы надевают только на фестивалях и при исполнении народных танцев.',
        uk: 'Традиційні болгарські костюми носять лише на фестивалях та народних танцях.',
      },
    },
  ],

  grammarReference: [],
};
