import type { LessonContent } from '@/content/types';

export const content: LessonContent = {
  introduction: `В този урок ще се научите да описвате физическото и емоционалното си състояние на български. Ще научите имената на частите на тялото, болестите и симптомите, ще се запознаете с поликлиниката и аптеката.

Граматиката в урока покрива дателните (кратки) форми на личните местоимения — ми, ти, му, й, ни, ви, им — и безличните изречения (Боли ме, Трябва ми, Топло ми е). Ще видите как да питате „Как се чувстваш?" и как да отговаряте.`,

  sections: [],

  dialogues: [
    {
      id: 'dialozi-1',
      speakers: [
        { name: 'А', text: 'Какво те боли?' },
        { name: 'Б', text: 'Боли ме окото.' },
        { name: 'А', text: 'Как си?' },
        { name: 'Б', text: 'Не съм добре. Болят ме очите.' },
      ],
    },
    {
      id: 'dialozi-2',
      speakers: [
        { name: 'А', text: 'Имате ли високо кръвно?' },
        { name: 'Б', text: 'Не, кръвното ми е нормално – 120 на 80.' },
        { name: 'А', text: 'Имам температура и кашлица и ме боли главата.' },
        { name: 'Б', text: 'Може би е грип.' },
        { name: 'А', text: 'Как сте?' },
        { name: 'Б', text: 'Имам хрема, кихам, но нямам температура.' },
        { name: 'А', text: 'Това е алергия.' },
      ],
    },
    {
      id: 'dialozi-3',
      speakers: [
        { name: 'А', text: 'Добър ден. Как си?' },
        { name: 'Б', text: 'Благодаря, добре. А ти?' },
        { name: 'А', text: 'Чувствам се чудесно. Имам нова работа и съм много доволен.' },
        { name: 'Б', text: 'Честито! А жена ти и децата как са?' },
        { name: 'А', text: 'И те са добре. Всички сме здрави.' },
        { name: 'А', text: 'Здравей, Мария! Как е Сашо?' },
        { name: 'Б', text: 'Не е добре.' },
        { name: 'А', text: 'Какво му е?' },
        { name: 'Б', text: 'Болен е. Има температура и го боли гърлото.' },
        { name: 'А', text: 'А ти как се чувстваш?' },
        { name: 'Б', text: 'Горе-долу, благодаря. Малко съм уморена.' },
      ],
    },
    {
      id: 'dialozi-4',
      speakers: [
        { name: 'Пациент', text: 'Добър ден. Какво Ви е?' },
        { name: 'Лекар',   text: 'Лошо ми е. Кашлям много, болят ме гърдите.' },
        { name: 'Пациент', text: 'Имате бронхит. Ето рецепта за лекарства. В поликлиниката има аптека.' },
        { name: 'Лекар',   text: 'Добър ден, д-р Димитров.' },
        { name: 'Пациент', text: 'Добър ден. Как е детето?' },
        { name: 'Лекар',   text: 'Боли го гърлото, главата, има температура.' },
        { name: 'Пациент', text: 'Трябва изследване на кръв и урина.' },
      ],
    },
  ],

  vocabulary: [
    { id: 'alergiya',           bulgarian: 'алергия'              },
    { id: 'antibiotik',         bulgarian: 'антибиотик'           },
    { id: 'aparat-za-kravno',   bulgarian: 'апарат за кръвно'     },
    { id: 'aspirin',            bulgarian: 'аспирин'              },
    { id: 'bint',               bulgarian: 'бинт'                 },
    { id: 'blagodarya',         bulgarian: 'благодаря'            },
    { id: 'bolen',              bulgarian: 'болен'                },
    { id: 'boli-me',            bulgarian: 'Боли ме.'             },
    { id: 'bolyat-me',          bulgarian: 'Болят ме.'            },
    { id: 'bolka',              bulgarian: 'болка'                },
    { id: 'bronhit',            bulgarian: 'бронхит'              },
    { id: 'barza-pomosht',      bulgarian: 'Бърза помощ'          },
    { id: 'vesel',              bulgarian: 'весел'                },
    { id: 'vie-mi-se-svyat',    bulgarian: 'Вие ми се свят.'      },
    { id: 'visoko-kravno',      bulgarian: 'високо кръвно'        },
    { id: 'vrat',               bulgarian: 'врат'                 },
    { id: 'gadi-mi-se',         bulgarian: 'Гади ми се.'          },
    { id: 'gimnastika',         bulgarian: 'гимнастика'           },
    { id: 'glava',              bulgarian: 'глава'                },
    { id: 'gladen',             bulgarian: 'гладен'               },
    { id: 'govoryа',            bulgarian: 'говоря'               },
    { id: 'gore-dolu',          bulgarian: 'горе-долу'            },
    { id: 'grip',               bulgarian: 'грип'                 },
    { id: 'grdi',               bulgarian: 'гърди'                },
    { id: 'grlo',               bulgarian: 'гърло'                },
    { id: 'detski-lekar',       bulgarian: 'детски лекар'         },
    { id: 'dovolen',            bulgarian: 'доволен'              },
    { id: 'zhaден',             bulgarian: 'жаден'                },
    { id: 'zatvoren',           bulgarian: 'затворен'             },
    { id: 'zdrav',              bulgarian: 'здрав'                },
    { id: 'zab',                bulgarian: 'зъб'                  },
    { id: 'zabolakar',          bulgarian: 'зъболекар'            },
    { id: 'izsledvane-krav',    bulgarian: 'изследване на кръв и урина' },
    { id: 'imunizatsiya',       bulgarian: 'имунизация'           },
    { id: 'kakvo-vi-e',         bulgarian: 'Какво Ви е?'          },
    { id: 'kanela',             bulgarian: 'канела'               },
    { id: 'kapki-za-nos',       bulgarian: 'капки за нос'         },
    { id: 'kapki-za-ochi',      bulgarian: 'капки за очи'         },
    { id: 'kapki-za-ushi',      bulgarian: 'капки за уши'         },
    { id: 'kardiolog',          bulgarian: 'кардиолог'            },
    { id: 'kashlitsa',          bulgarian: 'кашлица'              },
    { id: 'kiham',              bulgarian: 'кихам'                },
    { id: 'korem',              bulgarian: 'корем'                },
    { id: 'krak',               bulgarian: 'крак'                 },
    { id: 'kravna-kartina',     bulgarian: 'кръвна картина'       },
    { id: 'karst',              bulgarian: 'кръст'                },
    { id: 'lekar',              bulgarian: 'лекар'                },
    { id: 'lekarski-kabinet',   bulgarian: 'лекарски кабинет'     },
    { id: 'lekarstvo',          bulgarian: 'лекарство'            },
    { id: 'lichen-lekar',       bulgarian: 'личен лекар (джипи)'  },
    { id: 'losho-mi-e',         bulgarian: 'Лошо ми е.'           },
    { id: 'marlya',             bulgarian: 'марля'                },
    { id: 'matematika',         bulgarian: 'математика'           },
    { id: 'napravlenie',        bulgarian: 'направление'          },
    { id: 'nevrolog',           bulgarian: 'невролог'             },
    { id: 'nisko-kravno',       bulgarian: 'ниско кръвно'         },
    { id: 'nos',                bulgarian: 'нос'                  },
    { id: 'nuzhda',             bulgarian: 'нужда'                },
    { id: 'oko',                bulgarian: 'oko'                  },
    { id: 'opakоvka',           bulgarian: 'опаковка'             },
    { id: 'operatsiya',         bulgarian: 'операция'             },
    { id: 'pamuk',              bulgarian: 'памук'                },
    { id: 'pediatar',           bulgarian: 'педиатър'             },
    { id: 'poliklinika',        bulgarian: 'поликлиника'          },
    { id: 'politsay',           bulgarian: 'полицай'              },
    { id: 'prahche',            bulgarian: 'прахче'               },
    { id: 'priyatno',           bulgarian: 'приятно'              },
    { id: 'prst',               bulgarian: 'пръст'                },
    { id: 'registratura',       bulgarian: 'регистратура'         },
    { id: 'recepta',            bulgarian: 'рецепта'              },
    { id: 'raka',               bulgarian: 'ръка'                 },
    { id: 'sirop-kashlitsa',    bulgarian: 'сироп за кашлица'     },
    { id: 'spokoystvie',        bulgarian: 'спокойствие'          },
    { id: 'stomah',             bulgarian: 'стомах'               },
    { id: 'stres',              bulgarian: 'стрес'                },
    { id: 'studeno',            bulgarian: 'студено'              },
    { id: 'sartse',             bulgarian: 'сърце'                },
    { id: 'temperatura',        bulgarian: 'температура'          },
    { id: 'termometar',         bulgarian: 'термометър'           },
    { id: 'toplo',              bulgarian: 'топло'                },
    { id: 'trudno',             bulgarian: 'трудно'               },
    { id: 'tryabva-mi',         bulgarian: 'трябва ми'            },
    { id: 'tazhen',             bulgarian: 'тъжен'                },
    { id: 'tyalo',              bulgarian: 'тяло'                 },
    { id: 'umoren',             bulgarian: 'уморен'               },
    { id: 'usta',               bulgarian: 'уста'                 },
    { id: 'uho',                bulgarian: 'ухо'                  },
    { id: 'ung',                bulgarian: 'уши-нос-гърло (УНГ)'  },
    { id: 'hirurg',             bulgarian: 'хирург'               },
    { id: 'hrema',              bulgarian: 'хрема'                },
    { id: 'chast',              bulgarian: 'част'                 },
    { id: 'chuvstvam-se',       bulgarian: 'чувствам се'          },
  ],

  culturalNotes: [
    {
      id: 'how-are-you',
      title: {
        bg: 'Как сте? — не е само формалност',
        en: '"How are you?" is not just a formality',
        fr: "« Comment allez-vous\u00a0? » n'est pas seulement une formalité",
        ar: '«كيف حالك؟» ليست مجرد مجاملة',
        fa: '«حالتان چطور است؟» صرفاً تعارف نیست',
        ru: '«Как дела?» — это не просто формальность',
        uk: '«Як справи?» — це не просто ввічливість',
      },
      content: {
        bg: 'В България, когато питате „Как сте?", хората понякога отговарят подробно — за здравето, семейството, работата. Не е учтиво да се запитате мимоходом и да продължите, без да изчакате отговора. Бъдете готови за кратък разговор.',
        en: 'In Bulgaria, when you ask "How are you?", people sometimes give a detailed answer — about their health, family, work. It is not polite to ask in passing and move on without waiting for a reply. Be ready for a short conversation.',
        fr: "En Bulgarie, lorsque vous demandez « Comment allez-vous\u00a0? », les gens répondent parfois en détail — sur leur santé, leur famille, leur travail. Il n'est pas poli de poser la question en passant et de partir sans attendre la réponse. Soyez prêt pour une courte conversation.",
        ar: 'في بلغاريا، عندما تسأل «كيف حالك؟»، يُجيب الناس أحياناً بتفصيل — عن صحتهم وعائلتهم وعملهم. ليس من الأدب أن تسأل عابراً وتمضي دون انتظار الإجابة. كن مستعداً لمحادثة قصيرة.',
        fa: 'در بلغارستان وقتی می‌پرسید «حالتان چطور است؟»، مردم گاهی پاسخ مفصلی می‌دهند — درباره سلامتی، خانواده، کار. بی‌ادبانه است که این سؤال را در حین عبور بپرسید و بدون انتظار پاسخ ادامه دهید. آماده یک مکالمه کوتاه باشید.',
        ru: 'В Болгарии на вопрос «Как вы?» люди иногда отвечают подробно — о здоровье, семье, работе. Невежливо спрашивать мимоходом и уходить, не дождавшись ответа. Будьте готовы к короткому разговору.',
        uk: "У Болгарії на запитання «Як справи?» люди іноді відповідають докладно — про здоров\u2019я, сім\u2019ю, роботу. Нечемно питати мимохідь і йти, не чекаючи відповіді. Будьте готові до короткої розмови.",
      },
    },
    {
      id: 'healthcare-system',
      title: {
        bg: 'Здравната система в България',
        en: 'The healthcare system in Bulgaria',
        fr: 'Le système de santé en Bulgarie',
        ar: 'نظام الرعاية الصحية في بلغاريا',
        fa: 'سیستم بهداشت و درمان در بلغارستان',
        ru: 'Система здравоохранения в Болгарии',
        uk: "Система охорони здоров\u2019я в Болгарії",
      },
      content: {
        bg: 'Здравеопазването в България се осигурява от Националната здравноосигурителна каса (НЗОК). Всеки осигурен гражданин избира личен лекар (джипи). При нужда от специалист личният лекар дава направление. Съществуват и частни клиники — там се заплаща независимо от здравната осигуровка. Неосигурените лица заплащат пълния размер на лечението.',
        en: 'Healthcare in Bulgaria is provided by the National Health Insurance Fund. Every insured person chooses a general practitioner (GP). For a specialist, the GP gives a referral. There are also private clinics — payment is required there regardless of insurance. Uninsured people pay the full cost of treatment.',
        fr: "Les soins de santé en Bulgarie sont assurés par la Caisse nationale d'assurance maladie. Chaque assuré choisit un médecin généraliste (GP). Pour un spécialiste, le généraliste délivre une ordonnance de référence. Il existe aussi des cliniques privées — le paiement y est requis quelle que soit l'assurance. Les non-assurés paient le plein tarif.",
        ar: 'تُقدَّم الرعاية الصحية في بلغاريا عبر صندوق التأمين الصحي الوطني. يختار كل مؤمَّن طبيباً عاماً (جي بي). للحصول على استشارة متخصص، يُصدر الطبيب العام إحالة. توجد أيضاً عيادات خاصة — يُدفع فيها بغض النظر عن التأمين. أما غير المؤمَّنين فيدفعون التكلفة الكاملة للعلاج.',
        fa: 'خدمات درمانی در بلغارستان توسط صندوق بیمه درمانی ملی ارائه می‌شود. هر بیمه‌شده پزشک عمومی (GP) انتخاب می‌کند. برای مراجعه به متخصص، پزشک عمومی ارجاع می‌دهد. کلینیک‌های خصوصی هم وجود دارند که در آن‌ها صرف‌نظر از بیمه باید پرداخت کرد. افراد بیمه‌نشده هزینه کامل درمان را می‌پردازند.',
        ru: 'Здравоохранение в Болгарии обеспечивается Национальной кассой здравного страхования (НЗОК). Каждый застрахованный выбирает личного врача (GP). Для посещения специалиста личный врач выдаёт направление. Существуют и частные клиники — там оплата требуется независимо от страховки. Незастрахованные лица платят полную стоимость лечения.',
        uk: "Охорона здоров\u2019я в Болгарії забезпечується Національною касою медичного страхування. Кожен застрахований вибирає сімейного лікаря (GP). Для відвідування спеціаліста сімейний лікар видає направлення. Є також приватні клініки — там оплата потрібна незалежно від страховки. Незастраховані особи сплачують повну вартість лікування.",
      },
    },
    {
      id: 'emergency-112',
      title: {
        bg: 'Спешна помощ: тел. 112',
        en: 'Emergency services: 112',
        fr: "Services d'urgence : le 112",
        ar: 'خدمات الطوارئ: الرقم 112',
        fa: 'خدمات اورژانس: شماره ۱۱۲',
        ru: 'Экстренные службы: 112',
        uk: 'Служби екстреної допомоги: 112',
      },
      content: {
        bg: 'Номер 112 е за медицинска, пожарна и полицейска помощ в цяла Европа. Обаждането е безплатно от всеки телефон. Операторите говорят на различни езици.',
        en: 'The number 112 is for medical, fire and police emergency services across Europe. Calls are free from any phone. Operators speak various languages.',
        fr: "Le 112 est le numéro des services d'urgence médicale, des pompiers et de la police dans toute l'Europe. L'appel est gratuit depuis n'importe quel téléphone. Les opérateurs parlent plusieurs langues.",
        ar: 'الرقم 112 مخصص لخدمات الطوارئ الطبية والإطفاء والشرطة في جميع أنحاء أوروبا. الاتصال مجاني من أي هاتف. يتحدث المشغلون لغات متعددة.',
        fa: 'شماره ۱۱۲ برای خدمات اورژانس پزشکی، آتش‌نشانی و پلیس در سراسر اروپا است. تماس از هر تلفنی رایگان است. اپراتورها به زبان‌های مختلف صحبت می‌کنند.',
        ru: 'Номер 112 предназначен для экстренной медицинской, пожарной и полицейской помощи по всей Европе. Звонок бесплатен с любого телефона. Операторы говорят на разных языках.',
        uk: 'Номер 112 — для екстреної медичної, пожежної та поліцейської допомоги по всій Європі. Дзвінок безкоштовний з будь-якого телефону. Оператори розмовляють різними мовами.',
      },
    },
    {
      id: 'pharmacies',
      title: {
        bg: 'Аптеки в България',
        en: 'Pharmacies in Bulgaria',
        fr: 'Les pharmacies en Bulgarie',
        ar: 'الصيدليات في بلغاريا',
        fa: 'داروخانه‌ها در بلغارستان',
        ru: 'Аптеки в Болгарии',
        uk: 'Аптеки в Болгарії',
      },
      content: {
        bg: 'Аптеките в България обикновено работят от понеделник до събота от 8:00 до 20:00. Поне една аптека в района работи денонощно. Работното им време се изписва на витрината. Много лекарства се продават само с рецепта.',
        en: 'Pharmacies in Bulgaria are generally open Monday to Saturday from 8:00 am to 8:00 pm. At least one pharmacy in each area is open 24 hours. Their working hours are posted in the window. Many medicines are available only on prescription.',
        fr: 'Les pharmacies en Bulgarie sont généralement ouvertes du lundi au samedi de 8h00 à 20h00. Au moins une pharmacie dans chaque quartier est ouverte 24h/24. Leurs horaires sont affichés en vitrine. De nombreux médicaments ne sont disponibles que sur ordonnance.',
        ar: 'تعمل الصيدليات في بلغاريا عادةً من الاثنين إلى السبت من الساعة الثامنة صباحاً حتى الثامنة مساءً. صيدلية واحدة على الأقل في كل منطقة مفتوحة على مدار الساعة. تُعرض ساعات عملها على الواجهة. كثير من الأدوية لا تُصرف إلا بوصفة طبية.',
        fa: 'داروخانه‌ها در بلغارستان معمولاً دوشنبه تا شنبه از ساعت ۸ صبح تا ۸ شب باز هستند. حداقل یک داروخانه در هر منطقه ۲۴ ساعته باز است. ساعات کاری آن‌ها در ویترین نوشته شده است. بسیاری از داروها فقط با نسخه پزشک فروخته می‌شوند.',
        ru: 'Аптеки в Болгарии обычно работают с понедельника по субботу с 8:00 до 20:00. Как минимум одна аптека в районе работает круглосуточно. Часы работы указаны на витрине. Многие лекарства отпускаются только по рецепту.',
        uk: 'Аптеки в Болгарії зазвичай працюють з понеділка по суботу з 8:00 до 20:00. Принаймні одна аптека в районі працює цілодобово. Їхній робочий час зазначено у вітрині. Багато ліків відпускаються лише за рецептом.',
      },
    },
    {
      id: 'herbs-and-remedies',
      title: {
        bg: 'Билки и домашни лекове в България',
        en: 'Herbs and home remedies in Bulgaria',
        fr: 'Herbes et remèdes maison en Bulgarie',
        ar: 'الأعشاب والعلاجات المنزلية في بلغاريا',
        fa: 'گیاهان و داروهای خانگی در بلغارستان',
        ru: 'Травы и домашние средства в Болгарии',
        uk: 'Трави і народні засоби в Болгарії',
      },
      content: {
        bg: 'Българите обичат билките. При хрема и кашлица пият чай от лайка или мента с мед и лимон. При болно гърло правят гаргара или пият топло мляко с мед. При висока температура пият много вода и сок. Популярни билки са: лайка, мента, липа, розмарин, жълт кантарион, лапа. Продават се в аптеките и на пазара.',
        en: "Bulgarians love herbs. For a cold or cough they drink chamomile or mint tea with honey and lemon. For a sore throat they gargle or drink warm milk with honey. For high temperature they drink plenty of water and juice. Popular herbs include chamomile, mint, linden, rosemary, St John's wort, and burdock. They are sold in pharmacies and at the market.",
        fr: "Les Bulgares adorent les herbes médicinales. Pour un rhume ou une toux, ils boivent une infusion de camomille ou de menthe avec du miel et du citron. Pour un mal de gorge, ils font des gargarismes ou boivent du lait chaud avec du miel. Pour la fièvre, ils boivent beaucoup d'eau et de jus. Les herbes populaires comprennent la camomille, la menthe, le tilleul, le romarin, le millepertuis et la bardane. Elles se vendent en pharmacie et au marché.",
        ar: 'يُحبّ البلغاريون الأعشاب الطبية. عند الإصابة بنزلة برد أو سعال يشربون شاي البابونج أو النعناع مع العسل والليمون. لالتهاب الحلق يتغرغرون أو يشربون الحليب الدافئ مع العسل. عند ارتفاع الحرارة يشربون كميات كبيرة من الماء والعصير. من أشهر الأعشاب: البابونج والنعناع والزيزفون وإكليل الجبل ونبتة سانت جون وبقلة الجمل. تُباع في الصيدليات وفي السوق.',
        fa: 'بلغاری‌ها گیاهان دارویی را دوست دارند. برای سرماخوردگی یا سرفه چای بابونه یا نعناع با عسل و لیمو می‌نوشند. برای گلودرد غرغره می‌کنند یا شیر گرم با عسل می‌نوشند. برای تب زیاد آب و آبمیوه می‌نوشند. گیاهان محبوب شامل بابونه، نعناع، گل زنبق، رزماری، مریم‌گلی و گل‌گاو‌چشم می‌شوند. در داروخانه‌ها و بازار فروخته می‌شوند.',
        ru: 'Болгары любят травы. При простуде или кашле они пьют чай из ромашки или мяты с мёдом и лимоном. При боли в горле полощут горло или пьют тёплое молоко с мёдом. При высокой температуре пьют много воды и сока. Популярные травы: ромашка, мята, липа, розмарин, зверобой, лопух. Продаются в аптеках и на рынке.',
        uk: "Болгари люблять трави. При застуді або кашлі вони п\u2019ють чай з ромашки або м\u2019яти з медом і лимоном. При болю в горлі полощуть горло або п\u2019ють тепле молоко з медом. При високій температурі п\u2019ють багато води та соку. Популярні трави: ромашка, м\u2019ята, липа, розмарин, звіробій, лопух. Продаються в аптеках і на ринку.",
      },
    },
  ],
};
