import type { LessonContent } from '@/content/types';

export const content: LessonContent = {
  introduction: `В този урок ще се научите да говорите за бъдещи планове на български. Ще научите бъдеще време на глаголите (ще работя, ще уча…) и на глагола „съм" (ще бъда / ще съм).

Лексиката покрива думите за описание на външен вид — ръст, тегло, цвят на очите и косата. Ще слушате диалози за бъдещи планове и ще четете текстове за гостуване в България.`,

  sections: [],

  dialogues: [
    {
      id: 'dialozi-1',
      speakers: [
        { name: 'А', text: 'Хайде на купон довечера!' },
        { name: 'Б', text: 'Съжалявам, заета съм. Ще помагам на майка ми.' },
        { name: 'А', text: 'Какво ще правиш тази вечер?' },
        { name: 'Б', text: 'Ще ходя на кино, ще гледам интересен филм и след това ще ходя на ресторант. А ти?' },
        { name: 'А', text: 'Аз съм много уморен. Ще спя.' },
        { name: 'А', text: 'Какво ще правите довечера?' },
        { name: 'Б', text: 'Ще имаме гости. А вие?' },
        { name: 'А', text: 'Ние ще ходим на разходка в парка. Децата ще играят футбол и ще карат колело. После ще ядем пица и ще пазаруваме в супермаркета.' },
        { name: 'А', text: 'Какво ще правиш през уикенда?' },
        { name: 'Б', text: 'Ще пътувам до Пловдив с приятелката ми. Родителите ѝ живеят там. Майка ѝ има рожден ден. Ще празнуваме заедно. А ти?' },
        { name: 'А', text: 'Аз ще ходя в Гърция с приятели. Времето ще е много топло, ще плуваме в морето, ще се разхождаме, а вечерта ще танцуваме.' },
        { name: 'Б', text: 'Приятно прекарване!' },
        { name: 'А', text: 'Благодаря, подобно!' },
      ],
    },
    {
      id: 'dialozi-2',
      speakers: [
        { name: 'А', text: 'Здравей, къде отиваш?' },
        { name: 'Б', text: 'Имам среща с едно момиче.' },
        { name: 'А', text: 'Познавам ли я?' },
        { name: 'Б', text: 'Не, не я познаваш.' },
        { name: 'А', text: 'Как изглежда?' },
        { name: 'Б', text: 'Много красива, висока, с дълга черна коса и сини очи. Довиждане, много бързам.' },
        { name: 'А', text: 'Познаваш ли новия приятел на Катя?' },
        { name: 'Б', text: 'Не, как изглежда?' },
        { name: 'А', text: 'Супер – висок, с руса коса и тъмни очи.' },
        { name: 'Б', text: 'Не харесвам мъже с руса коса. Предпочитам с тъмна коса и светли очи. А ти?' },
        { name: 'А', text: 'Не знам. За мен е важен характерът.' },
      ],
    },
  ],

  vocabulary: [
    { id: 'blagodarya-podobno',   bulgarian: 'Благодаря, подобно!'  },
    { id: 'bliznak',              bulgarian: 'близнак'               },
    { id: 'blizak',              bulgarian: 'близък'                },
    { id: 'barzam',              bulgarian: 'бързам'                },
    { id: 'vazhen',              bulgarian: 'важен'                 },
    { id: 'vestnik',             bulgarian: 'вестник'               },
    { id: 'visoko',              bulgarian: 'високо'                },
    { id: 'dovechera',           bulgarian: 'довечера'              },
    { id: 'dori',                bulgarian: 'дори'                  },
    { id: 'izglejdam',           bulgarian: 'изглеждам'             },
    { id: 'karam',               bulgarian: 'карам'                 },
    { id: 'kestenyav',           bulgarian: 'кестеняв'              },
    { id: 'klas',                bulgarian: 'клас'                  },
    { id: 'kolega',              bulgarian: 'колега'                },
    { id: 'kolelo',              bulgarian: 'колело'                },
    { id: 'kompyutaren-spetsialist', bulgarian: 'компютърен специалист' },
    { id: 'kotka',               bulgarian: 'котка'                 },
    { id: 'kupon',               bulgarian: 'купон'                 },
    { id: 'kuche',               bulgarian: 'куче'                  },
    { id: 'kadrav',              bulgarian: 'къдрав'                },
    { id: 'lyubim',              bulgarian: 'любим'                 },
    { id: 'mislya',              bulgarian: 'мисля'                 },
    { id: 'mozhe-bi',            bulgarian: 'може би'               },
    { id: 'oreh',                bulgarian: 'орех'                  },
    { id: 'pazaruvam',           bulgarian: 'пазарувам'             },
    { id: 'plan',                bulgarian: 'план'                  },
    { id: 'pluvam',              bulgarian: 'плувам'                },
    { id: 'podarak',             bulgarian: 'подарък'               },
    { id: 'prav',                bulgarian: 'прав'                  },
    { id: 'priyatno-prekarvan',  bulgarian: 'Приятно прекарване!'   },
    { id: 'proekt',              bulgarian: 'проект'                },
    { id: 'promyana',            bulgarian: 'промяна'               },
    { id: 'rodopite',            bulgarian: 'Родопите'              },
    { id: 'rus',                 bulgarian: 'рус'                   },
    { id: 'rast',                bulgarian: 'ръст'                  },
    { id: 'svetal',              bulgarian: 'светъл'                },
    { id: 'skoro',               bulgarian: 'скоро'                 },
    { id: 'sledvasht',           bulgarian: 'следващ'               },
    { id: 'sreden',              bulgarian: 'среден'                },
    { id: 'stroen',              bulgarian: 'строен'                },
    { id: 'super',               bulgarian: 'супер'                 },
    { id: 'teglo',               bulgarian: 'тегло'                 },
    { id: 'tochno',              bulgarian: 'точно'                 },
    { id: 'tamen',               bulgarian: 'тъмен'                 },
    { id: 'udobno',              bulgarian: 'удобно'                },
    { id: 'uchenik',             bulgarian: 'ученик'                },
    { id: 'harakter',            bulgarian: 'характер'              },
    { id: 'chuzhbina',           bulgarian: 'чужбина'               },
  ],

  culturalNotes: [
    {
      id: 'name-days-birthdays',
      title: {
        bg: 'Именни дни и рождени дни',
        en: 'Name days and birthdays',
        fr: 'Fêtes et anniversaires',
        ar: 'أعياد الأسماء وأعياد الميلاد',
        fa: 'روز اسم و تولد',
        uk: 'Іменини та дні народження',
        ru: 'Именины и дни рождения',
      },
      content: {
        bg: 'Именните дни и рождените дни са важни поводи в България. Когато имат именен ден, рожден ден или добра новина, българите обикновено черпят колегите си с кутия бонбони, бисквити или безалкохолни напитки.',
        en: 'Name days and birthdays are important occasions in Bulgaria. When Bulgarians have a name day, a birthday, or some good news, they usually treat their colleagues to a box of chocolates, cookies or soft drinks.',
        fr: "Les fêtes et les anniversaires sont des occasions importantes en Bulgarie. Lorsque les Bulgares fêtent leur prénom, leur anniversaire ou ont de bonnes nouvelles, ils offrent généralement à leurs collègues une boîte de chocolats, des biscuits ou des boissons non alcoolisées.",
        ar: 'أعياد الأسماء وأعياد الميلاد مناسبات مهمة في بلغاريا. عندما يحتفل البلغاريون بعيد اسمهم أو ميلادهم أو تأتيهم أخبار سارة، يدعون زملاءهم عادةً إلى علبة شوكولاتة أو بسكويت أو مشروبات غازية.',
        fa: 'روز اسم و تولد در بلغارستان مناسبت‌های مهمی هستند. وقتی بلغاری‌ها روز اسم یا تولد دارند یا خبر خوشی دارند، معمولاً با یک جعبه شکلات، بیسکویت یا نوشابه از همکاران خود پذیرایی می‌کنند.',
        uk: 'Іменини та дні народження — важливі приводи в Болгарії. Коли болгари відзначають іменини, день народження або мають радісну новину, вони зазвичай пригощають колег коробкою цукерок, печивом або безалкогольними напоями.',
        ru: 'Именины и дни рождения — важные поводы в Болгарии. Когда у болгар именины, день рождения или хорошая новость, они обычно угощают коллег коробкой конфет, печеньем или безалкогольными напитками.',
      },
    },
    {
      id: 'birthday-presents',
      title: {
        bg: 'Подаръци за рожден ден',
        en: 'Birthday presents',
        fr: "Cadeaux d'anniversaire",
        ar: 'هدايا عيد الميلاد',
        fa: 'هدایای تولد',
        uk: 'Подарунки на день народження',
        ru: 'Подарки на день рождения',
      },
      content: {
        bg: 'Когато сте поканени на рожден ден, очаква се да донесете подарък. Обикновено е нещо с лична стойност за рождения. Очаква се именникът да черпи гостите.',
        en: 'When you are invited to a birthday party, you are expected to bring a birthday present. Usually it is something of personal value to the person celebrating. The birthday person is expected to treat everyone.',
        fr: "Lorsque vous êtes invité à une fête d'anniversaire, on s'attend à ce que vous apportiez un cadeau. En général, c'est quelque chose qui a une valeur personnelle pour la personne qui fête son anniversaire. Il est attendu que l'anniversaire offre quelque chose à ses invités.",
        ar: 'عندما تُدعى إلى حفلة عيد ميلاد، يُتوقع منك إحضار هدية. عادةً ما تكون شيئاً ذا قيمة شخصية للمحتفل. ويُتوقع من صاحب عيد الميلاد أن يضيّف الحاضرين.',
        fa: 'وقتی به جشن تولدی دعوت می‌شوید، انتظار می‌رود هدیه‌ای بیاورید. معمولاً چیزی است که برای متولد ارزش شخصی دارد. انتظار می‌رود که متولد از همه مهمانان پذیرایی کند.',
        uk: 'Коли вас запрошують на день народження, очікується, що ви принесете подарунок. Зазвичай це щось особисто цінне для іменинника. Очікується, що іменинник пригощає гостей.',
        ru: 'Когда вас приглашают на день рождения, ожидается, что вы принесёте подарок. Обычно это что-то лично значимое для именинника. Ожидается, что именинник угощает гостей.',
      },
    },
    {
      id: 'visiting',
      title: {
        bg: 'Гостуване в България',
        en: 'Visiting in Bulgaria',
        fr: 'Les visites en Bulgarie',
        ar: 'زيارة المنازل في بلغاريا',
        fa: 'مهمان‌رفتن در بلغارستان',
        uk: 'Відвідування в Болгарії',
        ru: 'Гостевание в Болгарии',
      },
      content: {
        bg: 'Българите, особено в малките градове и селата, често се ходят на гости без покана. Времето за гостуване не е фиксирано, нито ограничено. Понякога гостите могат да останат много часове. Ако имате друг ангажимент или искате да си тръгнете по-рано, информирайте домакините при пристигане — не е прието да си тръгнете внезапно. Обичаят е да донесете нещо: бутилка вино, кутия бонбони, цветя за домакинята или нещо за децата.',
        en: 'Bulgarians, especially in small towns and villages, often visit each other with or without an invitation. The time for a visit is not fixed or limited. Sometimes guests may stay for many hours. If you have other engagements or want to leave earlier, inform your hosts upon arrival — it is not considered polite to leave quite suddenly. It is a custom to bring something: a bottle of wine, a box of chocolates, flowers for the hostess, or something for the children.',
        fr: "Les Bulgares, surtout dans les petites villes et les villages, se rendent souvent visite avec ou sans invitation. La durée d'une visite n'est pas fixée ni limitée. Les invités peuvent parfois rester de nombreuses heures. Si vous avez d'autres engagements ou souhaitez partir plus tôt, prévenez vos hôtes à l'arrivée — partir brusquement est considéré comme impoli. Il est de coutume d'apporter quelque chose : une bouteille de vin, une boîte de chocolats, des fleurs pour la maîtresse de maison ou quelque chose pour les enfants.",
        ar: 'يزور البلغاريون بعضهم بعضاً في كثير من الأحيان، وخاصةً في المدن الصغيرة والقرى، بدعوة أو بدونها. لا يوجد وقت محدد أو محدود للزيارة، وقد يمكث الضيوف لساعات طويلة. إذا كان لديك ارتباط آخر أو تريد المغادرة مبكراً، فأخبر مضيفيك عند الوصول، إذ لا يُعدّ المغادرة المفاجئة من الأدب. ومن العادة أن تُحضر شيئاً معك: زجاجة نبيذ، أو علبة شوكولاتة، أو زهوراً للمضيفة، أو شيئاً للأطفال.',
        fa: 'بلغاری‌ها، به‌ویژه در شهرها و روستاهای کوچک، اغلب با یا بدون دعوت به مهمانی می‌روند. زمان مهمانی ثابت یا محدود نیست و گاهی مهمانان چندین ساعت می‌مانند. اگر برنامه دیگری دارید یا می‌خواهید زودتر بروید، هنگام ورود به میزبانان اطلاع دهید — رفتن ناگهانی ادبانه نیست. عادت است که چیزی بیاورید: یک بطری شراب، یک جعبه شکلات، گل برای خانم خانه، یا چیزی برای بچه‌ها.',
        uk: 'Болгари, особливо у невеликих містах і селах, часто відвідують один одного з запрошенням або без нього. Час для візиту не фіксований і не обмежений. Іноді гості можуть залишатися багато годин. Якщо у вас є інші справи або ви хочете піти раніше, повідомте господарів при прибутті — йти раптово вважається неввічливим. Прийнято приносити щось: пляшку вина, коробку цукерок, квіти для господині або щось для дітей.',
        ru: 'Болгары, особенно в небольших городах и сёлах, часто ходят друг к другу в гости с приглашением или без. Время визита не фиксировано и не ограничено. Иногда гости могут оставаться на много часов. Если у вас другие планы или вы хотите уйти раньше, предупредите хозяев при приходе — уходить внезапно считается невежливым. Принято приносить что-нибудь: бутылку вина, коробку конфет, цветы для хозяйки или что-то для детей.',
      },
    },
    {
      id: 'treating-guests',
      title: {
        bg: 'Черпене на гости',
        en: 'Treating guests',
        fr: 'Offrir à ses invités',
        ar: 'التضييف والكرم',
        fa: 'پذیرایی از مهمانان',
        uk: 'Пригощання гостей',
        ru: 'Угощение гостей',
      },
      content: {
        bg: 'За българите е въпрос на добри маниери да предлагат храна и напитки многократно по време на хранене, дори ако гостите отказват. Отказът от първото предложение е нормален — домакините ще предложат отново.',
        en: 'For Bulgarians, it is a matter of good manners to offer food and drinks repeatedly in the course of a meal, even if guests refuse. Declining the first offer is normal — hosts will offer again.',
        fr: "Pour les Bulgares, c'est une question de bonnes manières que d'offrir de la nourriture et des boissons à plusieurs reprises au cours d'un repas, même si les invités refusent. Décliner la première offre est normal — les hôtes proposeront à nouveau.",
        ar: 'من الأدب البلغاري أن يُعرض الطعام والشراب مراراً خلال الوجبة، حتى لو رفض الضيوف. رفض العرض الأول أمر طبيعي — إذ سيُعيد المضيفون الطرح مجدداً.',
        fa: 'برای بلغاری‌ها، ادب اقتضا می‌کند که غذا و نوشیدنی را بارها در طول وعده غذایی پیشنهاد دهند، حتی اگر مهمانان رد کنند. رد کردن پیشنهاد اول طبیعی است — میزبانان دوباره پیشنهاد می‌دهند.',
        uk: 'Для болгар — це питання хороших манер — пропонувати їжу та напої неодноразово під час трапези, навіть якщо гості відмовляються. Відмова від першої пропозиції є нормою — господарі запропонують знову.',
        ru: 'Для болгар это вопрос хорошего тона — предлагать еду и напитки неоднократно в ходе трапезы, даже если гости отказываются. Отказ от первого предложения является нормой — хозяева предложат снова.',
      },
    },
  ],
};
