import type { LessonContent } from '@/content/types';

export const content: LessonContent = {
  introduction: `В този урок ще се научите да използвате различни услуги на български — хотел, такси, копирен център, банка, обменно бюро, фризьорски салон и комунални плащания. Ще научите как да изразявате желание, способност и задължение с глаголите „искам да", „мога да" и „трябва да".

Ще се запознаете с пълните форми на личните местоимения след предлог (с мен, за него, до нея…) и ще четете текстове за реалния живот в България.`,

  sections: [],

  dialogues: [],

  vocabulary: [
    { id: 'l05-abonatен-nomer',   bulgarian: 'абонатен номер' },
    { id: 'l05-bankomat',         bulgarian: 'банкомат' },
    { id: 'l05-boyadisvane',      bulgarian: 'боядисване' },
    { id: 'l05-valuta',           bulgarian: 'валута' },
    { id: 'l05-vdyasno',          bulgarian: 'вдясно' },
    { id: 'l05-vlizam',           bulgarian: 'влизам' },
    { id: 'l05-vlyavo',           bulgarian: 'вляво' },
    { id: 'l05-vnasyam',          bulgarian: 'внасям' },
    { id: 'l05-vnimavam',         bulgarian: 'внимавам' },
    { id: 'l05-dvoyna-staya',     bulgarian: 'двойна стая' },
    { id: 'l05-dogovor',          bulgarian: 'договор' },
    { id: 'l05-dokument',         bulgarian: 'документ' },
    { id: 'l05-evro',             bulgarian: 'евро' },
    { id: 'l05-edinichna-staya',  bulgarian: 'единична стая' },
    { id: 'l05-zhilishte',        bulgarian: 'жилище' },
    { id: 'l05-izkam-da',         bulgarian: 'искам да' },
    { id: 'l05-izprashtam',       bulgarian: 'изпращам' },
    { id: 'l05-izchakajte',       bulgarian: 'Изчакайте!' },
    { id: 'l05-kabina',           bulgarian: 'кабина' },
    { id: 'l05-kazhete',          bulgarian: 'Кажете!' },
    { id: 'l05-kartichka',        bulgarian: 'картичка' },
    { id: 'l05-komisiona',        bulgarian: 'комисионна', ttsModel: 'pro' },
    { id: 'l05-kopie',            bulgarian: 'копие' },
    { id: 'l05-kopiren-centar',   bulgarian: 'копирен център' },
    { id: 'l05-kurs',             bulgarian: 'курс' },
    { id: 'l05-kadрene',          bulgarian: 'къдрене' },
    { id: 'l05-lichен',           bulgarian: 'личен' },
    { id: 'l05-marka',            bulgarian: 'марка' },
    { id: 'l05-moga-da',          bulgarian: 'мога да' },
    { id: 'l05-motel',            bulgarian: 'мотел' },
    { id: 'l05-nyama-znachenie',  bulgarian: 'Няма значение!' },
    { id: 'l05-obmennо-byuro',    bulgarian: 'обменно бюро' },
    { id: 'l05-obmenяm',          bulgarian: 'обменям' },
    { id: 'l05-otkrivam',         bulgarian: 'откривам (сметка)' },
    { id: 'l05-parno',            bulgarian: 'парно' },
    { id: 'l05-pismo',            bulgarian: 'писмо' },
    { id: 'l05-plashtane',        bulgarian: 'плащане' },
    { id: 'l05-plik',             bulgarian: 'плик' },
    { id: 'l05-podstrigvam',      bulgarian: 'подстригване', ttsModel: 'pro' },
    { id: 'l05-porychka',         bulgarian: 'поръчка' },
    { id: 'l05-prevod',           bulgarian: 'превод', ttsModel: 'pro' },
    { id: 'l05-predplata',        bulgarian: 'предплата' },
    { id: 'l05-pricheska',        bulgarian: 'прическа', ttsModel: 'pro' },
    { id: 'l05-rezervaciya',      bulgarian: 'резервация' },
    { id: 'l05-smetka',           bulgarian: 'сметка' },
    { id: 'l05-seshоar',          bulgarian: 'сешоар' },
    { id: 'l05-taksa',            bulgarian: 'такса' },
    { id: 'l05-teglya',           bulgarian: 'тегля', ttsModel: 'pro' },
    { id: 'l05-tok',              bulgarian: 'ток' },
    { id: 'l05-tryabva-da',       bulgarian: 'трябва да' },
    { id: 'l05-frizьorski-salon', bulgarian: 'фризьорски салон' },
    { id: 'l05-hazyain',          bulgarian: 'хазяин' },
    { id: 'l05-hostel',           bulgarian: 'хостел' },
    { id: 'l05-chestito',         bulgarian: 'Честито!' },
  ],

  culturalNotes: [
    {
      id: 'l05-services-schedule',
      title: {
        bg: 'Работно време на услугите в България',
        en: 'Service opening hours in Bulgaria',
        fr: 'Horaires des services en Bulgarie',
        ar: 'أوقات عمل الخدمات في بلغاريا',
        fa: 'ساعات کاری خدمات در بلغارستان',
        uk: 'Графік роботи послуг у Болгарії',
        ru: 'Часы работы служб в Болгарии',
      },
      content: {
        bg: 'В по-големите градове има мини-маркети, кафета и аптеки, работещи денонощно (нон-стоп), 7 дни в седмицата. Държавните учреждения и банките са затворени в почивните дни, а много магазини не работят в неделя.',
        en: 'In larger cities, there are mini-markets, cafes, and pharmacies open 24 hours a day, 7 days a week (non-stop). Government offices and banks are closed on weekends, and many shops do not open on Sunday.',
        fr: 'Dans les grandes villes, il existe des supérettes, des cafés et des pharmacies ouverts 24 h/24, 7 j/7 (non-stop). Les bureaux gouvernementaux et les banques sont fermés le week-end, et beaucoup de magasins n\'ouvrent pas le dimanche.',
        ar: 'في المدن الكبرى توجد متاجر صغيرة ومقاهٍ وصيدليات مفتوحة على مدار الساعة طوال أيام الأسبوع (نون-ستوب). المكاتب الحكومية والبنوك مغلقة في عطلة نهاية الأسبوع، وكثير من المحلات لا تعمل يوم الأحد.',
        fa: 'در شهرهای بزرگ‌تر، سوپرمارکت‌های کوچک، کافه‌ها و داروخانه‌هایی وجود دارند که ۲۴ ساعته و ۷ روز هفته باز هستند (نان-استاپ). ادارات دولتی و بانک‌ها در آخر هفته تعطیل هستند و بسیاری از مغازه‌ها روز یکشنبه باز نیستند.',
        uk: 'У більших містах є міні-маркети, кафе та аптеки, що працюють цілодобово (нон-стоп) 7 днів на тиждень. Державні установи та банки зачинені у вихідні дні, а багато магазинів не працюють у неділю.',
        ru: 'В крупных городах есть мини-маркеты, кафе и аптеки, работающие круглосуточно (нон-стоп) 7 дней в неделю. Государственные учреждения и банки закрыты в выходные дни, а многие магазины не работают в воскресенье.',
      },
    },
    {
      id: 'l05-bill-payment',
      title: {
        bg: 'Плащане на сметки',
        en: 'Paying bills',
        fr: 'Paiement des factures',
        ar: 'دفع الفواتير',
        fa: 'پرداخت قبوض',
        uk: 'Оплата рахунків',
        ru: 'Оплата счетов',
      },
      content: {
        bg: 'Въпреки че онлайн плащанията стават все по-разпространени, много хора — особено в малките градове — все още плащат сметките за ток, вода и парно в брой всеки месец. Популярни места за плащане са пощенски станции, банкови офиси и каси EasyPay.',
        en: 'Although online payments are becoming more common, many people — especially in smaller communities — still pay their electricity, water, and heating bills in cash each month. Popular payment locations include post offices, bank branches, and EasyPay cash points.',
        fr: 'Bien que les paiements en ligne se généralisent, beaucoup de personnes — surtout dans les petites villes — règlent encore leurs factures d\'électricité, d\'eau et de chauffage en espèces chaque mois. Les bureaux de poste, les agences bancaires et les caisses EasyPay sont des lieux de paiement populaires.',
        ar: 'رغم انتشار المدفوعات الإلكترونية، لا يزال كثير من الناس — خاصةً في المجتمعات الصغيرة — يدفعون فواتير الكهرباء والماء والتدفئة نقداً كل شهر. ومن أبرز أماكن الدفع مكاتب البريد والفروع البنكية ونقاط دفع EasyPay.',
        fa: 'هرچند پرداخت‌های آنلاین رواج بیشتری پیدا کرده‌اند، بسیاری از مردم — به‌خصوص در جوامع کوچک‌تر — هنوز قبوض برق، آب و گرمایش را هر ماه به صورت نقدی پرداخت می‌کنند. دفاتر پست، شعبه‌های بانک و نقاط پرداخت EasyPay از محل‌های محبوب برای پرداخت هستند.',
        uk: 'Незважаючи на поширення онлайн-платежів, багато людей — особливо в менших містах — досі щомісяця платять за електроенергію, воду та опалення готівкою. Популярні місця для оплати: поштові відділення, банківські офіси та каси EasyPay.',
        ru: 'Несмотря на распространение онлайн-платежей, многие люди — особенно в небольших городах — по-прежнему ежемесячно платят за электричество, воду и отопление наличными. Популярные места для оплаты: почтовые отделения, банковские офисы и кассы EasyPay.',
      },
    },
    {
      id: 'l05-phone-booths',
      title: {
        bg: 'Телефонни кабини и пощи',
        en: 'Phone booths and post offices',
        fr: 'Cabines téléphoniques et bureaux de poste',
        ar: 'أكشاك الهاتف ومكاتب البريد',
        fa: 'کیوسک‌های تلفن عمومی و دفاتر پست',
        uk: 'Телефонні кабіни та поштові відділення',
        ru: 'Телефонные будки и почтовые отделения',
      },
      content: {
        bg: 'В повечето пощенски станции в страната има поне една телефонна кабина, от която може да се провеждат международни разговори. Пощата предлага и услуги за изпращане на писма, картички и препоръчана поща.',
        en: 'In most post offices across the country, there is at least one phone booth where you can make international calls. The post office also offers services for sending letters, postcards, and registered mail.',
        fr: 'Dans la plupart des bureaux de poste du pays, il y a au moins une cabine téléphonique permettant de passer des appels internationaux. La poste propose également des services d\'envoi de lettres, de cartes postales et de courrier recommandé.',
        ar: 'في معظم مكاتب البريد في البلاد توجد كابينة هاتفية واحدة على الأقل يمكن منها إجراء مكالمات دولية. كما تقدّم مكاتب البريد خدمات إرسال الرسائل والبطاقات البريدية والبريد المسجّل.',
        fa: 'در بیشتر دفاتر پست سراسر کشور حداقل یک کیوسک تلفن عمومی وجود دارد که می‌توان از آن تماس بین‌المللی برقرار کرد. دفتر پست همچنین خدمات ارسال نامه، کارت‌پستال و نامه سفارشی ارائه می‌دهد.',
        uk: 'У більшості поштових відділень країни є принаймні одна телефонна кабіна, з якої можна здійснювати міжнародні дзвінки. Пошта також надає послуги з відправлення листів, листівок та рекомендованої пошти.',
        ru: 'В большинстве почтовых отделений страны есть хотя бы одна телефонная будка, из которой можно совершать международные звонки. Почта также предоставляет услуги по отправке писем, открыток и заказной почты.',
      },
    },
  ],
};
