import type { LessonContent } from '@/content/types';

export const content: LessonContent = {
  introduction:
    'В шестия урок ще научите думи за членовете на семейството и роднините. Ще се запознаете с кратките притежателни местоимения, с глаголите имам/нямам, с бройните числителни за хора (двама, трима...) и с рода и числото на прилагателните. Ще научите и глаголите от И-група — работя, уча.',

  sections: [],

  dialogues: [
    {
      id: 'l06-dialozi-1-a',
      speakers: [
        { name: 'А', text: 'Как се казваш?' },
        { name: 'Б', text: 'Аз се казвам Али.' },
        { name: 'А', text: 'Имаш ли голямо семейство?' },
        { name: 'Б', text: 'Да, в Сирия имам голямо семейство.' },
      ],
    },
    {
      id: 'l06-dialozi-1-b',
      speakers: [
        { name: 'А', text: 'Женен ли си?' },
        { name: 'Б', text: 'Да, женен съм.' },
        { name: 'А', text: 'Имаш ли деца?' },
        { name: 'Б', text: 'Да, имам четири деца.' },
      ],
    },
    {
      id: 'l06-dialozi-1-v',
      speakers: [
        { name: 'А', text: 'Имаш ли брат?' },
        { name: 'Б', text: 'Да, имам.' },
        { name: 'А', text: 'Имаш ли сестра?' },
        { name: 'Б', text: 'Не, нямам.' },
      ],
    },
    {
      id: 'l06-dialozi-2-a',
      speakers: [
        { name: 'А', text: 'Колко души има в семейството ти?' },
        { name: 'Б', text: 'Имам майка, баща, двама братя и три сестри.' },
        { name: 'А', text: 'Къде са родителите ти?' },
        { name: 'Б', text: 'Те са в България.' },
        { name: 'А', text: 'Къде са братята ти и сестрите ти?' },
        { name: 'Б', text: 'Те са в Ирак.' },
      ],
    },
    {
      id: 'l06-dialozi-2-b',
      speakers: [
        { name: 'А', text: 'На колко години си?' },
        { name: 'Б', text: 'На 40.' },
        { name: 'А', text: 'На колко години е жена ти?' },
        { name: 'Б', text: 'Жена ми е на 37 години.' },
        { name: 'А', text: 'Къде е тя сега?' },
        { name: 'Б', text: 'Тя е вкъщи с децата.' },
      ],
    },
    {
      id: 'l06-dialozi-3-a',
      speakers: [
        { name: 'А', text: 'Аз работя в ресторант. А ти работиш ли?' },
        { name: 'Б', text: 'Не, не работя. Сега уча в университет.' },
      ],
    },
  ],

  vocabulary: [
    // Family members (basic)
    { id: 'baba', bulgarian: 'баба', translations: { en: 'grandmother', fr: 'grand-mère', ar: 'جدة', fa: 'مادربزرگ', ru: 'бабушка', uk: 'бабуся' } },
    { id: 'bashta', bulgarian: 'баща', translations: { en: 'father', fr: 'père', ar: 'أب', fa: 'پدر', ru: 'отец', uk: 'батько' } },
    { id: 'brat', bulgarian: 'брат, братя', translations: { en: 'brother, brothers', fr: 'frère, frères', ar: 'أخ، إخوة', fa: 'برادر، برادران', ru: 'брат, братья', uk: 'брат, брати' } },
    { id: 'dyashterya', bulgarian: 'дъщеря', translations: { en: 'daughter', fr: 'fille', ar: 'ابنة', fa: 'دختر', ru: 'дочь', uk: 'дочка' } },
    { id: 'dyado', bulgarian: 'дядо, дядовци', translations: { en: 'grandfather, grandfathers', fr: 'grand-père, grands-pères', ar: 'جد، أجداد', fa: 'پدربزرگ، پدربزرگ‌ها', ru: 'дедушка, дедушки', uk: 'дідусь, дідусі' } },
    { id: 'zhena', bulgarian: 'жена', translations: { en: 'woman; wife', fr: 'femme', ar: 'امرأة؛ زوجة', fa: 'زن؛ همسر', ru: 'женщина; жена', uk: 'жінка; дружина' } },
    { id: 'mayka', bulgarian: 'майка', translations: { en: 'mother', fr: 'mère', ar: 'أم', fa: 'مادر', ru: 'мать', uk: 'мати' } },
    { id: 'mazh', bulgarian: 'мъж, мъже', translations: { en: 'man, men; husband', fr: 'homme, hommes; mari', ar: 'رجل، رجال؛ زوج', fa: 'مرد، مردان؛ شوهر', ru: 'мужчина, мужчины; муж', uk: 'чоловік, чоловіки' } },
    { id: 'momche', bulgarian: 'момче', translations: { en: 'boy', fr: 'garçon', ar: 'ولد', fa: 'پسر', ru: 'мальчик', uk: 'хлопчик' } },
    { id: 'momiche', bulgarian: 'момиче', translations: { en: 'girl', fr: 'fille', ar: 'بنت', fa: 'دختر', ru: 'девочка', uk: 'дівчинка' } },
    { id: 'dete', bulgarian: 'дете, деца', translations: { en: 'child, children', fr: 'enfant, enfants', ar: 'طفل، أطفال', fa: 'بچه، بچه‌ها', ru: 'ребёнок, дети', uk: 'дитина, діти' } },
    { id: 'roditeli', bulgarian: 'родители', translations: { en: 'parents', fr: 'parents', ar: 'والدان', fa: 'والدین', ru: 'родители', uk: 'батьки' } },
    { id: 'sestra', bulgarian: 'сестра', translations: { en: 'sister', fr: 'sœur', ar: 'أخت', fa: 'خواهر', ru: 'сестра', uk: 'сестра' } },
    { id: 'sin', bulgarian: 'син', translations: { en: 'son', fr: 'fils', ar: 'ابن', fa: 'پسر', ru: 'сын', uk: 'син' } },
    // Extended family (НОВИ ДУМИ 2)
    { id: 'saprug', bulgarian: 'съпруг, съпрузи', translations: { en: 'husband, spouses', fr: 'mari, époux', ar: 'زوج، أزواج', fa: 'شوهر، همسران', ru: 'муж, супруги', uk: 'чоловік, подружжя' } },
    { id: 'sapruga', bulgarian: 'съпруга', translations: { en: 'wife', fr: 'épouse', ar: 'زوجة', fa: 'همسر', ru: 'жена', uk: 'дружина' } },
    { id: 'chicho', bulgarian: 'чичо, чичовци', translations: { en: 'uncle, uncles', fr: 'oncle, oncles', ar: 'عم، أعمام', fa: 'عمو، عموها', ru: 'дядя, дяди', uk: 'дядько, дядьки' } },
    { id: 'lelya', bulgarian: 'леля', translations: { en: 'aunt', fr: 'tante', ar: 'عمة', fa: 'عمه', ru: 'тётя', uk: 'тітка' } },
    { id: 'vnuk', bulgarian: 'внук, внуци', translations: { en: 'grandson, grandsons', fr: 'petit-fils, petits-fils', ar: 'حفيد، أحفاد', fa: 'نوه، نوه‌ها', ru: 'внук, внуки', uk: 'онук, онуки' } },
    { id: 'vnuchka', bulgarian: 'внучка', translations: { en: 'granddaughter', fr: 'petite-fille', ar: 'حفيدة', fa: 'نوه دختر', ru: 'внучка', uk: 'онука' } },
    { id: 'semeystvo', bulgarian: 'семейство', translations: { en: 'family', fr: 'famille', ar: 'عائلة', fa: 'خانواده', ru: 'семья', uk: "сім'я" } },
    // Adjectives — antonyms
    { id: 'golyam', bulgarian: 'голям, -а, -о, големи', translations: { en: 'big, large', fr: 'grand, grande', ar: 'كبير', fa: 'بزرگ', ru: 'большой', uk: 'великий' } },
    { id: 'malak', bulgarian: 'малък, малка, -о, -и', translations: { en: 'small, little', fr: 'petit, petite', ar: 'صغير', fa: 'کوچک', ru: 'маленький', uk: 'маленький' } },
    { id: 'mlad', bulgarian: 'млад, -а, -о, -и', translations: { en: 'young', fr: 'jeune', ar: 'شاب', fa: 'جوان', ru: 'молодой', uk: 'молодий' } },
    { id: 'star', bulgarian: 'стар, -а, -о, -и', translations: { en: 'old', fr: 'vieux, vieille', ar: 'عجوز', fa: 'پیر', ru: 'старый', uk: 'старий' } },
    { id: 'dobur', bulgarian: 'добър, добра, -о, -и', translations: { en: 'good, nice', fr: 'bon, bonne', ar: 'طيب', fa: 'خوب', ru: 'хороший', uk: 'добрий' } },
    { id: 'losh', bulgarian: 'лош, -а, -о, -и', translations: { en: 'bad', fr: 'mauvais, mauvaise', ar: 'سيئ', fa: 'بد', ru: 'плохой', uk: 'поганий' } },
    { id: 'visok', bulgarian: 'висок, висока, -о, -и', translations: { en: 'tall, high', fr: 'grand, grande (taille)', ar: 'طويل', fa: 'بلند', ru: 'высокий', uk: 'високий' } },
    { id: 'nisak', bulgarian: 'нисък, ниска, -о, -и', translations: { en: 'short, low', fr: 'petit, petite (taille)', ar: 'قصير', fa: 'کوتاه', ru: 'низкий', uk: 'низький' } },
    { id: 'slab', bulgarian: 'слаб, -а, -о, -и', translations: { en: 'thin, slim', fr: 'mince', ar: 'نحيف', fa: 'لاغر', ru: 'худой', uk: 'худий' } },
    { id: 'pulen', bulgarian: 'пълен, пълна, -о, -и', translations: { en: 'plump, full', fr: 'gros, grosse', ar: 'بدين', fa: 'چاق', ru: 'полный', uk: 'повний' } },
    { id: 'rabotliv', bulgarian: 'работлив, -а, -о, -и', translations: { en: 'hardworking', fr: 'travailleur, travailleuse', ar: 'مجتهد', fa: 'سخت‌کوش', ru: 'трудолюбивый', uk: 'працьовитий' } },
    { id: 'marzeliv', bulgarian: 'мързелив, -а, -о, -и', translations: { en: 'lazy', fr: 'paresseux, paresseuse', ar: 'كسول', fa: 'تنبل', ru: 'ленивый', uk: 'ледачий' } },
    { id: 'umen', bulgarian: 'умен, умна, -о, -и', translations: { en: 'clever, smart', fr: 'intelligent, intelligente', ar: 'ذكي', fa: 'باهوش', ru: 'умный', uk: 'розумний' } },
    { id: 'glupav', bulgarian: 'глупав, -а, -о, -и', translations: { en: 'stupid, foolish', fr: 'bête, stupide', ar: 'غبي', fa: 'نادان', ru: 'глупый', uk: 'дурний' } },
    { id: 'krasiv', bulgarian: 'красив, -а, -о, -и', translations: { en: 'beautiful, handsome', fr: 'beau, belle', ar: 'جميل', fa: 'زیبا', ru: 'красивый', uk: 'красивий' } },
    { id: 'grozen', bulgarian: 'грозен, грозна, -о, -и', translations: { en: 'ugly', fr: 'laid, laide', ar: 'قبيح', fa: 'زشت', ru: 'некрасивый', uk: 'негарний' } },
    { id: 'hubav', bulgarian: 'хубав, -а, -о, -и', translations: { en: 'nice, pretty', fr: 'joli, jolie', ar: 'لطيف', fa: 'قشنگ', ru: 'симпатичный', uk: 'гарний' } },
    // Verbs
    { id: 'imam', bulgarian: 'имам, -аш', translations: { en: 'to have', fr: 'avoir', ar: 'يملك', fa: 'داشتن', ru: 'иметь', uk: 'мати' } },
    { id: 'nyamam', bulgarian: 'нямам, -аш', translations: { en: 'to not have', fr: 'ne pas avoir', ar: 'لا يملك', fa: 'نداشتن', ru: 'не иметь', uk: 'не мати' } },
    { id: 'rabotya', bulgarian: 'работя, -иш', translations: { en: 'to work', fr: 'travailler', ar: 'يعمل', fa: 'کار کردن', ru: 'работать', uk: 'працювати' } },
    { id: 'ucha', bulgarian: 'уча, -иш', translations: { en: 'to study', fr: 'étudier', ar: 'يتعلم', fa: 'یاد گرفتن', ru: 'учиться', uk: 'вчитися' } },
    { id: 'hodya', bulgarian: 'ходя, -иш', translations: { en: 'to go, to walk', fr: 'aller, marcher', ar: 'يذهب', fa: 'رفتن', ru: 'ходить', uk: 'ходити' } },
    { id: 'praznuvam', bulgarian: 'празнувам, -аш', translations: { en: 'to celebrate', fr: 'célébrer, fêter', ar: 'يحتفل', fa: 'جشن گرفتن', ru: 'праздновать', uk: 'святкувати' } },
    { id: 'znam', bulgarian: 'знам, -еш', translations: { en: 'to know', fr: 'savoir, connaître', ar: 'يعرف', fa: 'دانستن', ru: 'знать', uk: 'знати' } },
    { id: 'davam', bulgarian: 'давам, -аш', translations: { en: 'to give', fr: 'donner', ar: 'يعطي', fa: 'دادن', ru: 'давать', uk: 'давати' } },
    // Other nouns & expressions
    { id: 'goden', bulgarian: 'годеник, годеница', translations: { en: 'fiancé, fiancée', fr: 'fiancé, fiancée', ar: 'خطيب، خطيبة', fa: 'نامزد', ru: 'жених, невеста', uk: 'наречений, наречена' } },
    { id: 'zhenem', bulgarian: 'женен, -и', translations: { en: 'married (male)', fr: 'marié', ar: 'متزوج', fa: 'متأهل (مرد)', ru: 'женатый', uk: 'одружений' } },
    { id: 'omazena', bulgarian: 'омъжена, -и', translations: { en: 'married (female)', fr: 'mariée', ar: 'متزوجة', fa: 'متأهل (زن)', ru: 'замужняя', uk: 'заміжня' } },
    { id: 'razlika', bulgarian: 'разлика', translations: { en: 'difference', fr: 'différence', ar: 'فرق', fa: 'تفاوت', ru: 'разница', uk: 'різниця' } },
    { id: 'svoboda', bulgarian: 'свобода', translations: { en: 'freedom', fr: 'liberté', ar: 'حرية', fa: 'آزادی', ru: 'свобода', uk: 'свобода' } },
    { id: 'prazdnik', bulgarian: 'празник, празници', translations: { en: 'holiday, holidays', fr: 'fête, fêtes', ar: 'عطلة، عطلات', fa: 'تعطیلات', ru: 'праздник, праздники', uk: 'свято, свята' } },
    { id: 'kurs', bulgarian: 'курс', translations: { en: 'course', fr: 'cours', ar: 'دورة', fa: 'دوره', ru: 'курс', uk: 'курс' } },
    { id: 'kvartira', bulgarian: 'квартира', translations: { en: 'lodgings, flat', fr: 'logement', ar: 'شقة', fa: 'آپارتمان', ru: 'квартира', uk: 'квартира' } },
    { id: 'furna', bulgarian: 'фурна', translations: { en: 'bakery; oven', fr: 'boulangerie; four', ar: 'مخبز', fa: 'نانوایی', ru: 'пекарня; духовка', uk: 'пекарня; піч' } },
    { id: 'student', bulgarian: 'студент, -ка', translations: { en: 'student (male/female)', fr: 'étudiant, étudiante', ar: 'طالب، طالبة', fa: 'دانشجو', ru: 'студент, студентка', uk: 'студент, студентка' } },
    { id: 'ikonomika', bulgarian: 'икономика', translations: { en: 'economics', fr: 'économie', ar: 'اقتصاد', fa: 'اقتصاد', ru: 'экономика', uk: 'економіка' } },
    { id: 'priatel', bulgarian: 'приятел', translations: { en: 'friend', fr: 'ami, amie', ar: 'صديق', fa: 'دوست', ru: 'друг', uk: 'друг' } },
    { id: 'samo', bulgarian: 'само', translations: { en: 'only', fr: 'seulement', ar: 'فقط', fa: 'فقط', ru: 'только', uk: 'тільки' } },
    { id: 'zashtoto', bulgarian: 'защото', translations: { en: 'because', fr: 'parce que', ar: 'لأن', fa: 'چون', ru: 'потому что', uk: 'тому що' } },
    { id: 'ot-do', bulgarian: 'от … до …', translations: { en: 'from … to …', fr: 'de … à …', ar: 'من … إلى …', fa: 'از … تا …', ru: 'от … до …', uk: 'від … до …' } },
    { id: 'ot-2-godini', bulgarian: 'от 2 години', translations: { en: 'for 2 years', fr: 'depuis 2 ans', ar: 'منذ سنتين', fa: 'از ۲ سال پیش', ru: 'в течение 2 лет', uk: 'вже 2 роки' } },
    { id: 'ot-2012', bulgarian: 'от 2012 година', translations: { en: 'since 2012', fr: 'depuis 2012', ar: 'منذ عام 2012', fa: 'از سال ۲۰۱۲', ru: 'с 2012 года', uk: 'з 2012 року' } },
    { id: 'prez-lyatoto', bulgarian: 'през лятото', translations: { en: 'in summer', fr: 'en été', ar: 'في الصيف', fa: 'در تابستان', ru: 'летом', uk: 'влітку' } },
    { id: 'na-kolko-godini', bulgarian: 'На колко години?', translations: { en: 'How old?', fr: 'Quel âge ?', ar: 'كم عمره؟', fa: 'چند سالته؟', ru: 'Сколько лет?', uk: 'Скільки років?' } },
    { id: 'lipsvat-mi', bulgarian: 'Липсват ми.', translations: { en: 'I miss them.', fr: 'Ils me manquent.', ar: 'أشتاق إليهم.', fa: 'دلم برایشان تنگ شده.', ru: 'Я скучаю по ним.', uk: 'Я сумую за ними.' } },
    { id: 'tuk-ni-haresva', bulgarian: 'Тук ни харесва.', translations: { en: 'We like it here.', fr: 'Ici, ça nous plaît.', ar: 'يعجبنا هنا.', fa: 'اینجا را دوست داریم.', ru: 'Нам здесь нравится.', uk: 'Нам тут подобається.' } },
    { id: 'yordaniya', bulgarian: 'Йордания', translations: { en: 'Jordan', fr: 'Jordanie', ar: 'الأردن', fa: 'اردن', ru: 'Иордания', uk: 'Йорданія' } },
    { id: 'koleda', bulgarian: 'Коледа', translations: { en: 'Christmas', fr: 'Noël', ar: 'عيد الميلاد', fa: 'کریسمس', ru: 'Рождество', uk: 'Різдво' } },
    { id: 'ramazan-bayram', bulgarian: 'Рамазан Байрам', translations: { en: 'Ramadan Bairam', fr: 'Aïd el-Fitr', ar: 'عيد الفطر', fa: 'عید فطر', ru: 'Рамадан Байрам', uk: 'Рамадан Байрам' } },
    { id: 'kurban-bayram', bulgarian: 'Курбан Байрам', translations: { en: 'Kurban Bairam', fr: 'Aïd el-Adha', ar: 'عيد الأضحى', fa: 'عید قربان', ru: 'Курбан Байрам', uk: 'Курбан Байрам' } },
    { id: 'roditel', bulgarian: 'родител, -и', translations: { en: 'parent, -s', fr: 'parent, -s', ar: 'والد، والدان', fa: 'والد، والدین', ru: 'родитель, -и', uk: 'батько, батьки' } },
  ],

  culturalNotes: [
    {
      id: 'l06-culture-01',
      title: {
        bg: 'Имена в България',
        en: 'Names in Bulgaria',
        fr: 'Les prénoms en Bulgarie',
        ar: 'الأسماء في بلغاريا',
        fa: 'نام‌ها در بلغارستان',
        ru: 'Имена в Болгарии',
        uk: 'Імена в Болгарії',
      },
      content: {
        bg: 'В България хората имат три имена: лично ime (първо), презиме (бащино — от бащата) и фамилия (фамилно). Мъжките имена в фамилията обикновено завършват на -в, женските — на -ва, а семейното фамилно в мн.ч. — на -ви. Например: Иван Петров, Мария Петрова, семейство Петрови. Презимето не се ползва много в ежедневното общуване.',
        en: 'In Bulgaria, people have three names: a first name (ime), a middle name (prezime — derived from the father\'s name), and a surname (familiya). Male surnames usually end in -v, female surnames in -va, and the family name in plural ends in -vi. For example: Ivan Petrov, Maria Petrova, the Petrovi family. The middle name is not used much in everyday conversation.',
        fr: 'En Bulgarie, les gens ont trois noms : un prénom (ime), un deuxième prénom (prezime — dérivé du prénom du père) et un nom de famille (familiya). Les noms de famille masculins se terminent généralement en -v, les féminins en -va, et le nom de famille au pluriel en -vi. Par exemple : Ivan Petrov, Maria Petrova, la famille Petrovi. Le deuxième prénom est peu utilisé dans la vie quotidienne.',
        ar: 'في بلغاريا، يحمل الناس ثلاثة أسماء: الاسم الشخصي (إيمه)، والاسم الأوسط (بريزيمه — مشتق من اسم الأب)، واسم العائلة (فاميليا). تنتهي أسماء العائلة الذكورية عادةً بـ -в، والأنثوية بـ -ва، وتنتهي أسماء الأسرة بصيغة الجمع بـ -ви. مثلاً: إيفان بيتروف، ماريا بيتروفا، عائلة بيتروفي. لا يُستخدم الاسم الأوسط كثيراً في الحياة اليومية.',
        fa: 'در بلغارستان، مردم سه نام دارند: نام شخصی (ایمه)، نام میانی (پریزیمه — برگرفته از نام پدر) و نام خانوادگی (فامیلیا). نام‌های خانوادگی مردانه معمولاً به -в ختم می‌شوند، زنانه به -ва، و نام خانوادگی جمع به -ви. مثلاً: ایوان پتروف، ماریا پتروفا، خانواده پتروی. نام میانی در گفتگوی روزمره چندان استفاده نمی‌شود.',
        ru: 'В Болгарии у людей три имени: имя (личное), презиме (отчество — от имени отца) и фамилия. Мужские фамилии обычно заканчиваются на -в, женские на -ва, а семейное имя во множественном числе — на -ви. Например: Иван Петров, Мария Петрова, семья Петрови. Отчество в повседневном общении используется редко.',
        uk: 'У Болгарії людина має три імені: особисте ім\'я (іме), по батькові (презіме — від імені батька) та прізвище (фамілія). Чоловічі прізвища зазвичай закінчуються на -в, жіночі на -ва, а родинне прізвище у множині — на -ви. Наприклад: Іван Петров, Марія Петрова, сім\'я Петрові. По батькові в повсякденному спілкуванні майже не вживається.',
      },
    },
    {
      id: 'l06-culture-02',
      title: {
        bg: 'Семейство и брак в България',
        en: 'Family and marriage in Bulgaria',
        fr: 'Famille et mariage en Bulgarie',
        ar: 'الأسرة والزواج في بلغاريا',
        fa: 'خانواده و ازدواج در بلغارستان',
        ru: 'Семья и брак в Болгарии',
        uk: 'Сім\'я і шлюб у Болгарії',
      },
      content: {
        bg: 'В България е обичайно да питате дали някой е женен или омъжен. Разширеното семейство от три поколения е все още разпространено в селата. Самотните младежи обикновено живеят с родителите си до брака. Много млади двойки живеят при родителите на единия партньор, докато спестят за свой дом. Възрастните родители често се грижат от децата си. В градовете е разпространено нуклеарното семейство (само родители и деца). Градските семейства обикновено имат не повече от две деца.',
        en: 'In Bulgaria, it is not unusual to be asked if you are married. The three-generation extended family is still common in rural areas. Single adults are expected to live with their parents until they marry. Many young married couples live with one set of parents until they can afford their own home. Elderly parents are often cared for by their children. In cities, the nuclear family (just parents and their children) is usual. Families in the cities usually have no more than two children.',
        fr: 'En Bulgarie, il n\'est pas inhabituel de se faire demander si on est marié. La famille élargie à trois générations est encore fréquente dans les zones rurales. Les jeunes adultes célibataires vivent généralement chez leurs parents jusqu\'au mariage. De nombreux jeunes couples mariés vivent chez les parents de l\'un d\'eux jusqu\'à ce qu\'ils puissent acheter leur propre logement. Les parents âgés sont souvent pris en charge par leurs enfants. Dans les villes, la famille nucléaire (parents et enfants) est la norme. Les familles urbaines n\'ont généralement pas plus de deux enfants.',
        ar: 'في بلغاريا، من المعتاد أن يُسأل الشخص عما إذا كان متزوجاً. لا تزال الأسرة الممتدة من ثلاثة أجيال شائعة في المناطق الريفية. من المتوقع أن يعيش البالغون العزاب مع والديهم حتى الزواج. كثير من الأزواج الشباب يعيشون مع والدي أحدهم حتى يتمكنوا من تحمّل تكاليف منزلهم. كثيراً ما يرعى الأبناء والديهم المسنين. في المدن، الأسرة النووية (الآباء والأبناء فقط) هي السائدة. عادةً ما لا يتجاوز عدد أطفال الأسر الحضرية طفلين.',
        fa: 'در بلغارستان، پرسیدن از وضعیت تأهل فرد امری عادی است. خانواده گسترده سه‌نسلی هنوز در مناطق روستایی رایج است. انتظار می‌رود بزرگسالان مجرد تا زمان ازدواج با والدین زندگی کنند. بسیاری از زوج‌های جوان تا زمانی که بتوانند خانه خود را تهیه کنند، با والدین یکی از همسران زندگی می‌کنند. والدین مسن اغلب توسط فرزندانشان مراقبت می‌شوند. در شهرها، خانواده هسته‌ای (فقط پدر، مادر و فرزندان) رایج است. خانواده‌های شهری معمولاً بیش از دو فرزند ندارند.',
        ru: 'В Болгарии вполне принято спрашивать, женат ли человек или замужем. Расширенная трёхпоколенная семья по-прежнему распространена в сельской местности. Одинокие взрослые, как правило, живут с родителями до вступления в брак. Многие молодые пары живут с родителями одного из супругов, пока не смогут позволить себе собственное жильё. Пожилых родителей нередко опекают их дети. В городах распространена нуклеарная семья (только родители и дети). Городские семьи, как правило, имеют не более двух детей.',
        uk: 'У Болгарії цілком звичайно запитувати, чи одружена людина. Розширена трипоколінна сім\'я досі поширена в сільській місцевості. Від дорослих самотніх людей очікується, що вони житимуть з батьками до шлюбу. Багато молодих пар живуть з батьками когось із подружжя, поки не зможуть придбати власне житло. Літніх батьків нерідко доглядають діти. У містах поширена нуклеарна сім\'я (лише батьки та діти). Міські сім\'ї зазвичай мають не більше двох дітей.',
      },
    },
  ],

  grammarReference: [],
};
