import type { LessonContent } from '@/content/types';

export const content: LessonContent = {
  introduction: `В този урок ще научите как да разговаряте за професии и образование на български. Ще се запознаете с минало свършено — ИХ група (работих, купих, пих), с неопределителните и отрицателните местоимения (някой/никой, някъде/никъде, някога/никога), и с глаголи, от които се образуват съществителни (разхождам се → разходка, срещам се → среща). Ще прочетете автобиографиите на Васил и Мустафа.`,

  sections: [],

  dialogues: [],

  vocabulary: [
    { id: 'a2-l07-avtobiografiya',  bulgarian: 'автобиография (CV)' },
    { id: 'a2-l07-agentsiya',       bulgarian: 'агенция' },
    { id: 'a2-l07-advokat',         bulgarian: 'адвокат' },
    { id: 'a2-l07-angliya',         bulgarian: 'Англия' },
    { id: 'a2-l07-arhitekt',        bulgarian: 'архитект' },
    { id: 'a2-l07-arhitektura',     bulgarian: 'архитектура' },
    { id: 'a2-l07-bakalaVar',       bulgarian: 'бакалавър' },
    { id: 'a2-l07-biznesdama',      bulgarian: 'бизнесдама' },
    { id: 'a2-l07-visshe',          bulgarian: 'висше образование' },
    { id: 'a2-l07-gotvach',         bulgarian: 'готвач' },
    { id: 'a2-l07-data-razhdane',   bulgarian: 'дата на раждане' },
    { id: 'a2-l07-direktor',        bulgarian: 'директор' },
    { id: 'a2-l07-doktor',          bulgarian: 'доктор' },
    { id: 'a2-l07-ezikova-gimnazia',bulgarian: 'езикова гимназия' },
    { id: 'a2-l07-igra',            bulgarian: 'игра' },
    { id: 'a2-l07-izvestyen',       bulgarian: 'известен' },
    { id: 'a2-l07-izrechenie',      bulgarian: 'изречение' },
    { id: 'a2-l07-inzhener',        bulgarian: 'инженер' },
    { id: 'a2-l07-informatika',     bulgarian: 'информатика' },
    { id: 'a2-l07-ispanski',        bulgarian: 'испански' },
    { id: 'a2-l07-istorik',         bulgarian: 'историк' },
    { id: 'a2-l07-istoriya',        bulgarian: 'история' },
    { id: 'a2-l07-kompyutarni-umeniya', bulgarian: 'компютърни умения' },
    { id: 'a2-l07-legalizatsiya',   bulgarian: 'легализация' },
    { id: 'a2-l07-leka-rabota',     bulgarian: 'Лека работа!' },
    { id: 'a2-l07-lichni-umeniya',  bulgarian: 'лични умения и компетенции' },
    { id: 'a2-l07-magistar',        bulgarian: 'магистър' },
    { id: 'a2-l07-maychin-ezik',    bulgarian: 'майчин език' },
    { id: 'a2-l07-mat-gimnazia',    bulgarian: 'математическа гимназия' },
    { id: 'a2-l07-meditsina',       bulgarian: 'медицина' },
    { id: 'a2-l07-nachalno',        bulgarian: 'начално образование' },
    { id: 'a2-l07-nivo',            bulgarian: 'ниво' },
    { id: 'a2-l07-obrazovanie',     bulgarian: 'образование' },
    { id: 'a2-l07-osnovno',         bulgarian: 'основно образование' },
    { id: 'a2-l07-otlichno',        bulgarian: 'отлично' },
    { id: 'a2-l07-pedagogika',      bulgarian: 'педагогика' },
    { id: 'a2-l07-pera',            bulgarian: 'пера (да перем)' },
    { id: 'a2-l07-pokana',          bulgarian: 'покана' },
    { id: 'a2-l07-poluchavам',      bulgarian: 'получавам' },
    { id: 'a2-l07-pomoshch',        bulgarian: 'помощ' },
    { id: 'a2-l07-pravo',           bulgarian: 'право' },
    { id: 'a2-l07-prevezhdаm',      bulgarian: 'превеждам' },
    { id: 'a2-l07-prevod',          bulgarian: 'превод' },
    { id: 'a2-l07-prevodach',       bulgarian: 'преводач' },
    { id: 'a2-l07-prepodavane',     bulgarian: 'преподаване' },
    { id: 'a2-l07-prodavach',       bulgarian: 'продавач' },
    { id: 'a2-l07-prof-gimnazia',   bulgarian: 'професионална гимназия' },
    { id: 'a2-l07-profilirana-gimnazia', bulgarian: 'профилирана гимназия' },
    { id: 'a2-l07-psiholog',        bulgarian: 'психолог' },
    { id: 'a2-l07-psihologiya',     bulgarian: 'психология' },
    { id: 'a2-l07-pusha',           bulgarian: 'пуша' },
    { id: 'a2-l07-pushach',         bulgarian: 'пушач' },
    { id: 'a2-l07-rabotnik',        bulgarian: 'работник' },
    { id: 'a2-l07-razhodka',        bulgarian: 'разходка' },
    { id: 'a2-l07-spetsializatsiya',bulgarian: 'специализация' },
    { id: 'a2-l07-spetsialnost',    bulgarian: 'специалност' },
    { id: 'a2-l07-sredno',          bulgarian: 'средно образование' },
    { id: 'a2-l07-sou',             bulgarian: 'средно общообразователно училище (СОУ)' },
    { id: 'a2-l07-tants',           bulgarian: 'танц' },
    { id: 'a2-l07-telefonen-nomer', bulgarian: 'телефонен номер' },
    { id: 'a2-l07-tehnikum',        bulgarian: 'техникум' },
    { id: 'a2-l07-trudov-stazh',    bulgarian: 'трудов стаж' },
    { id: 'a2-l07-fizik',           bulgarian: 'физик' },
    { id: 'a2-l07-fizika',          bulgarian: 'физика' },
    { id: 'a2-l07-filologiya',      bulgarian: 'филология' },
    { id: 'a2-l07-frizyor',         bulgarian: 'фризьор' },
    { id: 'a2-l07-tselyuvka',       bulgarian: 'целувка' },
    { id: 'a2-l07-chasten',         bulgarian: 'частен' },
    { id: 'a2-l07-chuzhd-ezik',     bulgarian: 'чужд език' },
    { id: 'a2-l07-shivach',         bulgarian: 'шивач' },
    { id: 'a2-l07-shofyor',         bulgarian: 'шофьор' },
    { id: 'a2-l07-sekretarka',      bulgarian: 'секретарка' },
  ],

  culturalNotes: [
    {
      id: 'a2-l07-visshe-obrazovanie',
      title: {
        bg: 'Висшето образование в България',
        en: 'Higher Education in Bulgaria',
        fr: 'L\'enseignement supérieur en Bulgarie',
        ar: 'التعليم العالي في بلغاريا',
        fa: 'آموزش عالی در بلغارستان',
        uk: 'Вища освіта в Болгарії',
        ru: 'Высшее образование в Болгарии',
      },
      content: {
        bg: 'Висшето образование в България се цени много и родителите правят всичко възможно, за да дадат на децата си университетска степен. Затова страната има много студенти и хора с висше образование. В България работят редица държавни и частни висши учебни заведения, лицензирани от Министерството на образованието и науката. Те предлагат голямо разнообразие от специалности — от медицина, право и педагогика до информатика, архитектура и изкуство.',
        en: 'Higher education in Bulgaria is highly valued and parents do their best to give their children a university degree. As a result, the country has many students and university graduates. A number of state and private higher education institutions operate in Bulgaria, licensed by the Ministry of Education and Science. They offer a wide variety of fields of study — from medicine, law and pedagogy to computer science, architecture and arts.',
        fr: 'L\'enseignement supérieur est très valorisé en Bulgarie, et les parents font tout leur possible pour offrir à leurs enfants un diplôme universitaire. Le pays compte ainsi de nombreux étudiants et diplômés. Des établissements d\'enseignement supérieur publics et privés, agréés par le ministère de l\'Éducation et des Sciences, proposent un large éventail de spécialités — de la médecine, du droit et de la pédagogie à l\'informatique, l\'architecture et les arts.',
        ar: 'يحظى التعليم العالي في بلغاريا بمكانة رفيعة، ويبذل الآباء قصارى جهدهم لتوفير شهادة جامعية لأبنائهم. لهذا السبب تضم البلاد عدداً كبيراً من الطلاب وحاملي شهادات جامعية. يعمل في بلغاريا عدد من مؤسسات التعليم العالي الحكومية والخاصة المرخصة من وزارة التعليم والعلوم، وتقدم تخصصات متنوعة — من الطب والقانون والتربية إلى المعلوماتية والعمارة والفنون.',
        fa: 'آموزش عالی در بلغارستان بسیار ارزشمند است و والدین هر کاری می‌کنند تا مدرک دانشگاهی به فرزندانشان بدهند. به همین دلیل این کشور دانشجویان و فارغ‌التحصیلان دانشگاهی زیادی دارد. تعدادی از مؤسسات آموزش عالی دولتی و خصوصی در بلغارستان فعال هستند که توسط وزارت آموزش و علوم مجوز دارند و طیف گسترده‌ای از رشته‌ها — از پزشکی، حقوق و آموزش تا فناوری اطلاعات، معماری و هنر — ارائه می‌دهند.',
        uk: 'Вища освіта в Болгарії дуже цінується, і батьки роблять все можливе, щоб дати дітям університетський ступінь. Тому в країні багато студентів і людей з вищою освітою. В Болгарії діє ряд державних і приватних вищих навчальних закладів, ліцензованих Міністерством освіти і науки. Вони пропонують широкий спектр спеціальностей — від медицини, права та педагогіки до інформатики, архітектури та мистецтва.',
        ru: 'Высшее образование в Болгарии высоко ценится, и родители делают всё возможное, чтобы дать детям университетский диплом. Поэтому в стране много студентов и людей с высшим образованием. В Болгарии работает ряд государственных и частных высших учебных заведений, лицензированных Министерством образования и науки. Они предлагают широкий выбор специальностей — от медицины, права и педагогики до информатики, архитектуры и искусства.',
      },
    },
    {
      id: 'a2-l07-cv-bg',
      title: {
        bg: 'Автобиографията (CV) в България',
        en: 'The CV in Bulgaria',
        fr: 'Le CV en Bulgarie',
        ar: 'السيرة الذاتية في بلغاريا',
        fa: 'رزومه در بلغارستان',
        uk: 'Резюме (CV) в Болгарії',
        ru: 'Резюме (CV) в Болгарии',
      },
      content: {
        bg: 'Когато кандидатствате за работа в България, обикновено трябва да изпратите автобиография (CV) и мотивационно писмо. В автобиографията се включват: лични данни (три имена, адрес, телефон, имейл, дата на раждане), трудов стаж (в обратен хронологичен ред), образование, езикови умения и компютърни умения. Европейският формат Europass е широко разпространен и се предпочита от много работодатели.',
        en: 'When applying for a job in Bulgaria, you usually need to send a CV (автобиография) and a cover letter. A CV includes: personal information (full name, address, phone, email, date of birth), work experience (in reverse chronological order), education, language skills and computer skills. The Europass format is widely used and preferred by many employers.',
        fr: 'Pour postuler à un emploi en Bulgarie, il faut généralement envoyer un CV (автобиография) et une lettre de motivation. Un CV comprend : les données personnelles (nom complet, adresse, téléphone, e-mail, date de naissance), l\'expérience professionnelle (en ordre chronologique inverse), la formation, les compétences linguistiques et informatiques. Le format Europass est largement répandu et apprécié des employeurs.',
        ar: 'عند التقدم لوظيفة في بلغاريا، يُطلب عادةً إرسال سيرة ذاتية (автобиография) ورسالة تحفيزية. تتضمن السيرة الذاتية: البيانات الشخصية (الاسم الكامل والعنوان والهاتف والبريد الإلكتروني وتاريخ الميلاد)، والخبرة العملية (بترتيب زمني عكسي)، والتعليم، والمهارات اللغوية والحاسوبية. تنسيق Europass منتشر على نطاق واسع ويُفضله كثير من أصحاب العمل.',
        fa: 'هنگام درخواست شغل در بلغارستان، معمولاً باید رزومه (автобиография) و نامه انگیزشی ارسال کنید. رزومه شامل: اطلاعات شخصی (نام کامل، آدرس، تلفن، ایمیل، تاریخ تولد)، سابقه کاری (به ترتیب زمانی معکوس)، تحصیلات، مهارت‌های زبانی و کامپیوتری است. فرمت Europass به طور گسترده استفاده می‌شود و توسط بسیاری از کارفرمایان ترجیح داده می‌شود.',
        uk: 'Коли ви подаєте заявку на роботу в Болгарії, зазвичай потрібно надіслати резюме (автобиография) та супровідний лист. Резюме включає: особисті дані (повне ім\'я, адреса, телефон, електронна пошта, дата народження), досвід роботи (у зворотному хронологічному порядку), освіту, мовні та комп\'ютерні навички. Формат Europass широко розповсюджений і переважно надається перевага роботодавцями.',
        ru: 'При устройстве на работу в Болгарии обычно нужно прислать резюме (автобиография) и сопроводительное письмо. В резюме указываются: личные данные (полное имя, адрес, телефон, электронная почта, дата рождения), опыт работы (в обратном хронологическом порядке), образование, языковые и компьютерные навыки. Формат Europass широко распространён и предпочитается многими работодателями.',
      },
    },
  ],
};
