import type { LessonContent } from '@/content/types';

export const content: LessonContent = {
  introduction: `В този урок ще говорите за мечти и планове на български. Ще научите разликата между несъвършен и свършен вид на глаголите и бъдеще време на глаголите от свършен вид (ще отида, ще дойда, ще дам…).

Ще слушате и четете текстове за бъдещи планове, пътувания и мечти. Ще практикувате бъдеще време в положителна, отрицателна и въпросителна форма.`,

  sections: [],

  dialogues: [],

  vocabulary: [
    { id: 'ako',                    bulgarian: 'ако' },
    { id: 'vzemam',                 bulgarian: 'вземам' },
    { id: 'vizhdam',                bulgarian: 'виждам' },
    { id: 'vino',                   bulgarian: 'вино' },
    { id: 'vrashtam-se',            bulgarian: 'връщам се' },
    { id: 'vsichko-shte-e-nared',   bulgarian: 'Всичко ще е наред!' },
    { id: 'davam',                  bulgarian: 'давам' },
    { id: 'idvam',                  bulgarian: 'идвам' },
    { id: 'zabavlyavam-se',         bulgarian: 'забавлявам се' },
    { id: 'zabravam',               bulgarian: 'забравям' },
    { id: 'zavarshvam',             bulgarian: 'завършвам' },
    { id: 'zakasnyavam',            bulgarian: 'закъснявам' },
    { id: 'zaminavam',              bulgarian: 'заминавам' },
    { id: 'zapovqdaj-vkyshti',      bulgarian: 'Заповядай вкъщи!' },
    { id: 'zapochvam',              bulgarian: 'започвам' },
    { id: 'zatvaryam',              bulgarian: 'затварям' },
    { id: 'izlizam',                bulgarian: 'излизам' },
    { id: 'italianski',             bulgarian: 'италиански' },
    { id: 'kazvam',                 bulgarian: 'казвам' },
    { id: 'kanyam',                 bulgarian: 'каня' },
    { id: 'kupuvam',                bulgarian: 'купувам' },
    { id: 'lyagam-si',              bulgarian: 'лягам си' },
    { id: 'mezhduchasie',           bulgarian: 'междучасие' },
    { id: 'mechta',                 bulgarian: 'мечта' },
    { id: 'mechtaya',               bulgarian: 'мечтая' },
    { id: 'motor',                  bulgarian: 'мотор' },
    { id: 'navreme',                bulgarian: 'навреме' },
    { id: 'nadyavam-se',            bulgarian: 'надявам се' },
    { id: 'namiram',                bulgarian: 'намирам' },
    { id: 'nachalo',                bulgarian: 'начало' },
    { id: 'nerven',                 bulgarian: 'нервен' },
    { id: 'obazhdam-se',            bulgarian: 'обаждам се' },
    { id: 'otvaryam',               bulgarian: 'отварям' },
    { id: 'otivam',                 bulgarian: 'отивам' },
    { id: 'plan',                   bulgarian: 'план' },
    { id: 'plashtam',               bulgarian: 'плащам' },
    { id: 'pomagam',                bulgarian: 'помагам' },
    { id: 'pristigam',              bulgarian: 'пристигам' },
    { id: 'razbiram',               bulgarian: 'разбирам' },
    { id: 'romantichno',            bulgarian: 'романтично' },
    { id: 'svarshvam',              bulgarian: 'свършвам' },
    { id: 'sreshtam-se',            bulgarian: 'срещам се' },
    { id: 'stavam',                 bulgarian: 'ставам' },
    { id: 'suvenir',                bulgarian: 'сувенир' },
    { id: 'trugvam',                bulgarian: 'тръгвам' },
  ],

  culturalNotes: [
    {
      id: 'migration-after-1989',
      title: {
        bg: 'Мечти и планове — миграция след 1989 г.',
        en: 'Dreams and plans — migration after 1989',
        fr: 'Rêves et projets — migration après 1989',
        ar: 'الأحلام والخطط — الهجرة بعد عام 1989',
        fa: 'رویاها و برنامه‌ها — مهاجرت پس از ۱۹۸۹',
        uk: 'Мрії та плани — міграція після 1989 р.',
        ru: 'Мечты и планы — миграция после 1989 г.',
      },
      content: {
        bg: 'След 1989 г. много българи емигрират в Западна Европа и САЩ в търсене на по-добра работа и по-висок жизнен стандарт. Емигрантите са от различни възрасти и професии, но много от тях са млади и добре образовани.',
        en: 'After 1989, many Bulgarians migrated to Western Europe and the USA looking for better jobs and a higher standard of living. The demographics of emigrants is varied, but many of them are young and well educated.',
        fr: 'Après 1989, de nombreux Bulgares ont émigré en Europe occidentale et aux États-Unis à la recherche de meilleurs emplois et d\'un niveau de vie plus élevé. Les profils des émigrants sont variés, mais beaucoup d\'entre eux sont jeunes et bien formés.',
        ar: 'بعد عام 1989، هاجر كثير من البلغاريين إلى أوروبا الغربية والولايات المتحدة بحثاً عن وظائف أفضل ومستوى معيشة أعلى. تختلف فئات المهاجرين، لكن كثيراً منهم شباب ومتعلمون.',
        fa: 'پس از ۱۹۸۹، بسیاری از بلغاری‌ها برای یافتن شغل بهتر و سطح زندگی بالاتر به اروپای غربی و ایالات متحده مهاجرت کردند. مهاجران از گروه‌های سنی و حرفه‌ای مختلف هستند، اما بسیاری از آن‌ها جوان و تحصیل‌کرده‌اند.',
        uk: 'Після 1989 р. багато болгар емігрували до Західної Європи та США в пошуках кращої роботи та вищого рівня життя. Емігранти різного віку та професій, але багато з них — молоді та добре освічені.',
        ru: 'После 1989 года многие болгары эмигрировали в Западную Европу и США в поисках лучшей работы и более высокого уровня жизни. Эмигранты разного возраста и профессий, но многие из них молоды и хорошо образованы.',
      },
    },
    {
      id: 'seasonal-migration',
      title: {
        bg: 'Сезонна и постоянна миграция',
        en: 'Seasonal and permanent migration',
        fr: 'Migration saisonnière et permanente',
        ar: 'الهجرة الموسمية والدائمة',
        fa: 'مهاجرت فصلی و دائمی',
        uk: 'Сезонна та постійна міграція',
        ru: 'Сезонная и постоянная миграция',
      },
      content: {
        bg: 'Някои мигранти намират сезонна работа и пътуват до и от България, докато други се преместват завинаги със семействата си.',
        en: 'Some migrants find seasonal jobs and travel to and from Bulgaria, while many have moved permanently with their families.',
        fr: 'Certains migrants trouvent un emploi saisonnier et voyagent entre la Bulgarie et l\'étranger, tandis que d\'autres se sont installés définitivement avec leur famille.',
        ar: 'يجد بعض المهاجرين عملاً موسمياً ويسافرون ذهاباً وإياباً إلى بلغاريا، بينما انتقل كثيرون بشكل دائم مع عائلاتهم.',
        fa: 'برخی مهاجران کار فصلی پیدا می‌کنند و بین بلغارستان و خارج رفت‌وآمد دارند، در حالی که بسیاری برای همیشه با خانواده‌هایشان مهاجرت کرده‌اند.',
        uk: 'Деякі мігранти знаходять сезонну роботу та подорожують до Болгарії та назад, тоді як багато хто переїхав назавжди зі своїми сім\'ями.',
        ru: 'Некоторые мигранты находят сезонную работу и ездят в Болгарию и обратно, тогда как многие переехали навсегда со своими семьями.',
      },
    },
    {
      id: 'study-abroad',
      title: {
        bg: 'Висше образование в чужбина',
        en: 'Higher education abroad',
        fr: 'Études supérieures à l\'étranger',
        ar: 'التعليم العالي في الخارج',
        fa: 'تحصیلات عالی در خارج',
        uk: 'Вища освіта за кордоном',
        ru: 'Высшее образование за границей',
      },
      content: {
        bg: 'Много популярно е завършилите гимназия да продължат висшето си образование в университети в чужбина. Много от тях намират работа и остават там след дипломиране.',
        en: 'It is very popular for high-school graduates to continue their higher education at universities abroad, and many of them find jobs and stay there after graduation.',
        fr: 'Il est très courant que les bacheliers poursuivent leurs études supérieures dans des universités à l\'étranger, et beaucoup d\'entre eux trouvent un emploi et y restent après l\'obtention de leur diplôme.',
        ar: 'من الشائع جداً أن يكمل خريجو الثانوية تعليمهم العالي في جامعات بالخارج، وكثير منهم يجدون عملاً ويبقون هناك بعد التخرج.',
        fa: 'بسیار رایج است که فارغ‌التحصیلان دبیرستان تحصیلات عالی خود را در دانشگاه‌های خارج ادامه دهند و بسیاری از آن‌ها پس از فارغ‌التحصیلی شغل پیدا کرده و در همانجا می‌مانند.',
        uk: 'Дуже популярно, коли випускники школи продовжують вищу освіту в університетах за кордоном, і багато з них знаходять роботу та залишаються там після закінчення.',
        ru: 'Очень популярно, когда выпускники школы продолжают высшее образование в университетах за границей, и многие из них находят работу и остаются там после окончания.',
      },
    },
  ],
};
