import type { LessonContent } from '@/content/types';

export const content: LessonContent = {
  introduction: `В този урок ще се научите да говорите по телефона на български — как да се обаждате, как да отговаряте и как да уговаряте срещи и покани. Ще видите типични телефонни диалози: обаждане до фирма, грешка в номера, покана за вечеря, разговор за работа и за апартамент под наем.

Граматиката в урока е за винителните (кратки) форми на личните местоимения — ме, те, го, я, ни, ви, ги — и как заместваме предмета в изречението с тях (Обичам Мария → Обичам я). Накрая ще прочетете текст за това как Мария използва телефона си.`,

  sections: [],

  dialogues: [],

  vocabulary: [
    { id: 'sim-karta',          bulgarian: 'SIM карта' },
    { id: 'sms',                bulgarian: 'SMS' },
    { id: 'agentsiya',          bulgarian: 'агенция' },
    { id: 'angliyski',          bulgarian: 'английски' },
    { id: 'bebe',               bulgarian: 'бебе' },
    { id: 'bezplatno',          bulgarian: 'безплатно' },
    { id: 'vklyuchvam',         bulgarian: 'включвам' },
    { id: 'vrazka',             bulgarian: 'връзка' },
    { id: 'vav-vrazka-s',       bulgarian: 'във връзка с' },
    { id: 'do',                 bulgarian: 'до' },
    { id: 'dom',                bulgarian: 'дом' },
    { id: 'dalgo',              bulgarian: 'дълго' },
    { id: 'eto',                bulgarian: 'ето' },
    { id: 'zhivot',             bulgarian: 'живот' },
    { id: 'zabravyam',          bulgarian: 'забравям' },
    { id: 'zaklyuchvam',        bulgarian: 'заключвам' },
    { id: 'zaplata',            bulgarian: 'заплата' },
    { id: 'zatvaryam',          bulgarian: 'затварям' },
    { id: 'zatova',             bulgarian: 'затова' },
    { id: 'igrachka',           bulgarian: 'играчка' },
    { id: 'izklyuchvam',        bulgarian: 'изключвам' },
    { id: 'izpolzvam',          bulgarian: 'използвам' },
    { id: 'imate-greshka',      bulgarian: 'Имате грешка.' },
    { id: 'intervyu',           bulgarian: 'интервю' },
    { id: 'internet',           bulgarian: 'интернет' },
    { id: 'informatsiya',       bulgarian: 'информация' },
    { id: 'lek-den',            bulgarian: 'Лек ден!' },
    { id: 'lesno',              bulgarian: 'лесно' },
    { id: 'mobilen-telefon',    bulgarian: 'мобилен телефон' },
    { id: 'navsyakade',         bulgarian: 'навсякъде' },
    { id: 'namiram',            bulgarian: 'намирам' },
    { id: 'nov',                bulgarian: 'нов' },
    { id: 'novini',             bulgarian: 'новини' },
    { id: 'obadete-se',         bulgarian: 'Обадете се!' },
    { id: 'obazhdam-se',        bulgarian: 'обаждам се' },
    { id: 'obyava',             bulgarian: 'обява' },
    { id: 'ogled',              bulgarian: 'оглед' },
    { id: 'otvaryam',           bulgarian: 'отварям' },
    { id: 'otgovaryam',         bulgarian: 'отговарям' },
    { id: 'otklyuchvam',        bulgarian: 'отключвам' },
    { id: 'pitam',              bulgarian: 'питам' },
    { id: 'poznavam',           bulgarian: 'познавам' },
    { id: 'pomagam',            bulgarian: 'помагам' },
    { id: 'pomnya',             bulgarian: 'помня' },
    { id: 'pochivni-dni',       bulgarian: 'почивни дни' },
    { id: 'prashtam',           bulgarian: 'пращам' },
    { id: 'pregrashtam',        bulgarian: 'прегръщам' },
    { id: 'prez-tsyaloto-vreme', bulgarian: 'през цялото време' },
    { id: 'proveryavam',        bulgarian: 'проверявам' },
    { id: 'palen-raboten-den',  bulgarian: 'пълен работен ден' },
    { id: 'rabotno-vreme',      bulgarian: 'работно време' },
    { id: 'radio',              bulgarian: 'радио' },
    { id: 'razbiram',           bulgarian: 'разбирам' },
    { id: 'razlichen',          bulgarian: 'различен' },
    { id: 'svoboden',           bulgarian: 'свободен' },
    { id: 'sekretarka',         bulgarian: 'секретарка' },
    { id: 'skaype',             bulgarian: 'Скайп' },
    { id: 'skap',               bulgarian: 'скъп' },
    { id: 'skapi',              bulgarian: 'скъпи' },
    { id: 'smartfon',           bulgarian: 'смартфон' },
    { id: 'snimka',             bulgarian: 'снимка' },
    { id: 'strana',             bulgarian: 'страна' },
    { id: 'tarsya',             bulgarian: 'търся' },
    { id: 'udovolstvie',        bulgarian: 'удоволствие' },
    { id: 'feysbuk',            bulgarian: 'Фейсбук' },
    { id: 'film',               bulgarian: 'филм' },
    { id: 'firma',              bulgarian: 'фирма' },
    { id: 'tseluvam',           bulgarian: 'целувам' },
    { id: 'tsyal',              bulgarian: 'цял' },
    { id: 'chasovnik',          bulgarian: 'часовник' },
    { id: 'chuvam',             bulgarian: 'чувам' },
  ],

  culturalNotes: [
    {
      id: 'answering-phone',
      title: {
        bg: 'Как се отговаря на телефон',
        en: 'Answering the phone',
        fr: 'Répondre au téléphone',
        ar: 'الرد على الهاتف',
        fa: 'پاسخ دادن به تلفن',
        ru: 'Как отвечают по телефону',
        uk: 'Як відповідають по телефону',
      },
      content: {
        bg: 'В официална или служебна обстановка, когато вдигате телефона, обикновено казвате името си или името на фирмата. Вкъщи често казвате просто „Ало?". Много българи отговарят и с „Да, моля?" или „Да?" и изчакват обаждащият се да се представи или да каже с кого иска да говори.',
        en: 'In formal or business situations, when you answer the phone you usually give your name or the name of your company. At home, people often just say "Ало?" (Hello?). Many Bulgarians also answer with "Да, моля?" (Yes, please?) or "Да?" (Yes?) and wait for the caller to introduce themselves or say who they want to speak to.',
        fr: 'Dans un contexte formel ou professionnel, lorsque vous répondez au téléphone, vous donnez généralement votre nom ou celui de votre entreprise. À la maison, on dit souvent simplement « Ало ? » (Allô ?). Beaucoup de Bulgares répondent aussi par « Да, моля ? » (Oui, je vous prie ?) ou « Да ? » (Oui ?) et attendent que l’appelant se présente ou dise à qui il veut parler.',
        ar: 'في المواقف الرسمية أو المهنية، عند الرد على الهاتف عادةً ما تذكر اسمك أو اسم شركتك. أما في المنزل، فكثيرًا ما يقول الناس ببساطة «Ало?» (مرحبًا؟). ويرد كثير من البلغار أيضًا بـ «Да, моля?» (نعم، من فضلك؟) أو «Да?» (نعم؟) وينتظرون أن يعرّف المتصل بنفسه أو يقول مع من يريد التحدث.',
        fa: 'در موقعیت‌های رسمی یا کاری، هنگام پاسخ دادن به تلفن معمولاً نام خود یا نام شرکت‌تان را می‌گویید. در خانه مردم اغلب فقط می‌گویند «Ало?» (الو؟). بسیاری از بلغارها هم با «Да, моля?» (بله، بفرمایید؟) یا «Да?» (بله؟) پاسخ می‌دهند و منتظر می‌مانند تا تماس‌گیرنده خود را معرفی کند یا بگوید با چه کسی می‌خواهد صحبت کند.',
        ru: 'В официальной или деловой обстановке, отвечая на звонок, вы обычно называете своё имя или название фирмы. Дома часто говорят просто «Ало?» (Алло?). Многие болгары отвечают также «Да, моля?» (Да, пожалуйста?) или «Да?» и ждут, пока звонящий представится или скажет, с кем хочет поговорить.',
        uk: 'В офіційній або діловій обстановці, відповідаючи на дзвінок, ви зазвичай називаєте своє ім’я або назву фірми. Удома часто кажуть просто «Ало?» (Алло?). Багато болгар відповідають також «Да, моля?» (Так, будь ласка?) або «Да?» і чекають, поки той, хто телефонує, відрекомендується або скаже, з ким хоче говорити.',
      },
    },
    {
      id: 'phone-numbers',
      title: {
        bg: 'Произношение на телефонните номера',
        en: 'How phone numbers are read',
        fr: 'Comment on lit les numéros de téléphone',
        ar: 'كيف تُقرأ أرقام الهاتف',
        fa: 'چگونه شماره‌های تلفن خوانده می‌شوند',
        ru: 'Как произносят телефонные номера',
        uk: 'Як вимовляють телефонні номери',
      },
      content: {
        bg: 'Телефонните номера в България се произнасят по няколко начина: цифра по цифра (8 1 8 2 1 0 0 — осем, едно, осем, две, едно, нула, нула); като двуцифрени числа (22-53-78 — двайсет и две, петдесет и три, седемдесет и осем); като трицифрени числа (375-549 — триста седемдесет и пет, петстотин четиридесет и девет); или като комбинация от трите.',
        en: 'Phone numbers in Bulgaria are read in several ways: digit by digit (8 1 8 2 1 0 0); as two-digit numbers (22-53-78 — twenty-two, fifty-three, seventy-eight); as three-digit numbers (375-549 — three hundred seventy-five, five hundred forty-nine); or as a combination of all three.',
        fr: 'En Bulgarie, les numéros de téléphone se lisent de plusieurs façons : chiffre par chiffre (8 1 8 2 1 0 0) ; en nombres à deux chiffres (22-53-78 — vingt-deux, cinquante-trois, soixante-dix-huit) ; en nombres à trois chiffres (375-549 — trois cent soixante-quinze, cinq cent quarante-neuf) ; ou en combinant les trois.',
        ar: 'تُقرأ أرقام الهاتف في بلغاريا بعدة طرق: رقمًا رقمًا (8 1 8 2 1 0 0)؛ كأعداد من رقمين (22-53-78 — اثنان وعشرون، ثلاثة وخمسون، ثمانية وسبعون)؛ كأعداد من ثلاثة أرقام (375-549 — ثلاثمائة وخمسة وسبعون، خمسمائة وتسعة وأربعون)؛ أو بمزيج من الطرق الثلاث.',
        fa: 'شماره‌های تلفن در بلغارستان به چند روش خوانده می‌شوند: رقم به رقم (8 1 8 2 1 0 0)؛ به‌صورت اعداد دو رقمی (22-53-78 — بیست‌ودو، پنجاه‌وسه، هفتادوهشت)؛ به‌صورت اعداد سه رقمی (375-549 — سیصدوهفتادوپنج، پانصدوچهل‌ونه)؛ یا ترکیبی از این سه.',
        ru: 'Телефонные номера в Болгарии произносят по-разному: цифра за цифрой (8 1 8 2 1 0 0); как двузначные числа (22-53-78 — двадцать два, пятьдесят три, семьдесят восемь); как трёхзначные числа (375-549 — триста семьдесят пять, пятьсот сорок девять); или комбинируя все три способа.',
        uk: 'Телефонні номери в Болгарії вимовляють по-різному: цифра за цифрою (8 1 8 2 1 0 0); як двозначні числа (22-53-78 — двадцять два, п’ятдесят три, сімдесят вісім); як тризначні числа (375-549 — триста сімдесят п’ять, п’ятсот сорок дев’ять); або поєднуючи всі три способи.',
      },
    },
    {
      id: 'mobile-operators',
      title: {
        bg: 'Мобилни оператори в България',
        en: 'Mobile operators in Bulgaria',
        fr: 'Opérateurs mobiles en Bulgarie',
        ar: 'مشغّلو الهاتف المحمول في بلغاريا',
        fa: 'اپراتورهای موبایل در بلغارستان',
        ru: 'Мобильные операторы в Болгарии',
        uk: 'Мобільні оператори в Болгарії',
      },
      content: {
        bg: 'Мобилните телефони в България се наричат GSM-и. Има трима основни оператора: А1, Yettel и Vivacom. Има два основни вида услуги: абонаментни програми (планове) и предплатени услуги. За предплатените услуги си купувате предплатена карта (ваучер) с код, за да заредите сметката си с определена сума.',
        en: 'Mobile phones in Bulgaria are called GSMs. There are three main operators: A1, Yettel and Vivacom. There are two main types of service: subscription plans and pre-paid services. For pre-paid, you buy a pre-paid card (voucher) with a code to top up your account with a fixed amount.',
        fr: 'En Bulgarie, les téléphones portables sont appelés des GSM. Il y a trois opérateurs principaux : A1, Yettel et Vivacom. Il existe deux types de services : les forfaits avec abonnement et les services prépayés. Pour le prépayé, vous achetez une carte prépayée (un bon) avec un code afin de recharger votre compte d’un montant fixe.',
        ar: 'تُسمّى الهواتف المحمولة في بلغاريا GSM. هناك ثلاثة مشغّلين رئيسيين: A1 وYettel وVivacom. وهناك نوعان رئيسيان من الخدمات: باقات الاشتراك والخدمات المدفوعة مسبقًا. بالنسبة للمدفوعة مسبقًا، تشتري بطاقة مدفوعة مسبقًا (قسيمة) تحمل رمزًا لشحن حسابك بمبلغ محدد.',
        fa: 'تلفن‌های همراه در بلغارستان GSM نامیده می‌شوند. سه اپراتور اصلی وجود دارد: A1، Yettel و Vivacom. دو نوع اصلی سرویس هست: طرح‌های اشتراکی و سرویس‌های پیش‌پرداخت. برای پیش‌پرداخت، یک کارت پیش‌پرداخت (واچر) با یک کد می‌خرید تا حساب خود را با مبلغ مشخصی شارژ کنید.',
        ru: 'Мобильные телефоны в Болгарии называют GSM. Есть три основных оператора: A1, Yettel и Vivacom. Существуют два основных вида услуг: абонентские программы (планы) и предоплаченные услуги. Для предоплаты вы покупаете предоплаченную карту (ваучер) с кодом, чтобы пополнить счёт на определённую сумму.',
        uk: 'Мобільні телефони в Болгарії називають GSM. Є три основні оператори: A1, Yettel і Vivacom. Існують два основні види послуг: абонентські програми (плани) та передплачені послуги. Для передплати ви купуєте передплачену картку (ваучер) із кодом, щоб поповнити рахунок на певну суму.',
      },
    },
    {
      id: 'sms-and-calling',
      title: {
        bg: 'SMS и обажданията',
        en: 'Text messages and calls',
        fr: 'SMS et appels',
        ar: 'الرسائل النصية والمكالمات',
        fa: 'پیامک و تماس‌ها',
        ru: 'SMS и звонки',
        uk: 'SMS і дзвінки',
      },
      content: {
        bg: 'В България само обаждащият се плаща за изходящото обаждане по GSM. Затова понякога хората само „звънват" — обаждат се и веднага затварят, за да не плащат. Това може да е уговорен знак или да означава „моля, обади ми се". SMS-ите са много популярни — често се пишат на български с латински букви и специални знаци (4 = ч, 6 = ш, q = я).',
        en: 'In Bulgaria, only the caller pays for an outgoing GSM call. That is why people sometimes just "click" — they call and hang up immediately to avoid being charged. This can be an agreed signal or mean "please, call me back". Text messages are very popular — they are often written in Bulgarian using Latin letters and special symbols (4 = ч, 6 = ш, q = я).',
        fr: 'En Bulgarie, seul l’appelant paie l’appel sortant sur un GSM. C’est pourquoi les gens font parfois juste un « bip » — ils appellent et raccrochent aussitôt pour ne pas être facturés. Cela peut être un signal convenu ou signifier « rappelle-moi, s’il te plaît ». Les SMS sont très populaires — ils s’écrivent souvent en bulgare avec des lettres latines et des symboles spéciaux (4 = ч, 6 = ш, q = я).',
        ar: 'في بلغاريا، يدفع المتصل وحده ثمن المكالمة الصادرة عبر GSM. لذلك يقوم الناس أحيانًا بمجرد «رنّة» — يتصلون ثم يغلقون فورًا لتجنّب الدفع. وقد يكون ذلك إشارة متفقًا عليها أو يعني «من فضلك، عاود الاتصال بي». الرسائل النصية شائعة جدًا — وغالبًا ما تُكتب بالبلغارية بحروف لاتينية ورموز خاصة (4 = ч، 6 = ш، q = я).',
        fa: 'در بلغارستان فقط تماس‌گیرنده هزینه تماس خروجی GSM را می‌پردازد. به همین دلیل گاهی مردم فقط یک «تک‌زنگ» می‌زنند — تماس می‌گیرند و فوراً قطع می‌کنند تا هزینه‌ای پرداخت نکنند. این می‌تواند علامتی از پیش توافق‌شده باشد یا به معنای «لطفاً به من زنگ بزن» باشد. پیامک‌ها بسیار رایج‌اند — اغلب به بلغاری با حروف لاتین و نمادهای خاص نوشته می‌شوند (4 = ч، 6 = ш، q = я).',
        ru: 'В Болгарии за исходящий звонок по GSM платит только звонящий. Поэтому иногда люди просто «звякают» — звонят и сразу кладут трубку, чтобы не платить. Это может быть условный сигнал или означать «перезвони мне, пожалуйста». SMS очень популярны — их часто пишут по-болгарски латинскими буквами и со специальными символами (4 = ч, 6 = ш, q = я).',
        uk: 'У Болгарії за вихідний дзвінок по GSM платить лише той, хто телефонує. Тому іноді люди просто «дзенькають» — телефонують і одразу кладуть слухавку, щоб не платити. Це може бути умовний сигнал або означати «передзвони мені, будь ласка». SMS дуже популярні — їх часто пишуть болгарською латинськими літерами та спеціальними символами (4 = ч, 6 = ш, q = я).',
      },
    },
  ],
};
