import type { LessonContent } from '@/content/types';

export const content: LessonContent = {
  introduction: `В този урок ще научите за природата и географията на България. Ще разберете защо България е известна с красивите си планини, реки и черноморски бряг — и ще можете да говорите за тях на български.`,

  sections: [],

  vocabulary: [
    {
      id: 'poluostrov',
      bulgarian: 'полуостров, -и',
      ttsText: 'полуостров, полуострови',
      ttsModel: 'pro',
      translations: {
        en: 'peninsula, -s',
        fr: 'péninsule, -s',
        ar: 'شبه جزيرة',
        fa: 'شبه‌جزیره',
        ru: 'полуостров',
        uk: 'півострів',
      },
    },
    {
      id: 'vrah',
      bulgarian: 'връх, върхове',
      ttsText: 'връх, върхове',
      ttsModel: 'pro',
      translations: {
        en: 'peak, peaks',
        fr: 'sommet, -s',
        ar: 'قمة',
        fa: 'قله',
        ru: 'вершина',
        uk: 'вершина',
      },
    },
    {
      id: 'ravnina',
      bulgarian: 'равнина, -и',
      ttsText: 'равнина, равнини',
      ttsModel: 'pro',
      translations: {
        en: 'plain, plains',
        fr: 'plaine, -s',
        ar: 'سهل',
        fa: 'دشت',
        ru: 'равнина',
        uk: 'рівнина',
      },
    },
    {
      id: 'dolina',
      bulgarian: 'долина, -и',
      ttsText: 'долина, долини',
      ttsModel: 'pro',
      translations: {
        en: 'valley, valleys',
        fr: 'vallée, -s',
        ar: 'وادي',
        fa: 'دره',
        ru: 'долина',
        uk: 'долина',
      },
    },
    {
      id: 'bryag',
      bulgarian: 'бряг, брегове',
      ttsText: 'бряг, брегове',
      ttsModel: 'pro',
      translations: {
        en: 'shore, coast',
        fr: 'rive, côte',
        ar: 'شاطئ',
        fa: 'ساحل',
        ru: 'берег',
        uk: 'берег',
      },
    },
    {
      id: 'vodopad',
      bulgarian: 'водопад, -и',
      ttsText: 'водопад, водопади',
      ttsModel: 'pro',
      translations: {
        en: 'waterfall, -s',
        fr: 'cascade, -s',
        ar: 'شلال',
        fa: 'آبشار',
        ru: 'водопад',
        uk: 'водоспад',
      },
    },
    {
      id: 'klimat',
      bulgarian: 'климат',
      ttsText: 'климат',
      ttsModel: 'pro',
      translations: {
        en: 'climate',
        fr: 'climat',
        ar: 'مناخ',
        fa: 'آب‌وهوا',
        ru: 'климат',
        uk: 'клімат',
      },
    },
    {
      id: 'priroden_park',
      bulgarian: 'природен парк',
      ttsText: 'природен парк',
      ttsModel: 'pro',
      translations: {
        en: 'nature reserve / national park',
        fr: 'parc naturel',
        ar: 'محمية طبيعية',
        fa: 'پارک طبیعی',
        ru: 'природный парк',
        uk: 'природний парк',
      },
    },
    {
      id: 'mechka',
      bulgarian: 'мечка, -и',
      ttsText: 'мечка, мечки',
      ttsModel: 'pro',
      translations: {
        en: 'bear, -s',
        fr: 'ours, ourses',
        ar: 'دب',
        fa: 'خرس',
        ru: 'медведь',
        uk: 'ведмідь',
      },
    },
    {
      id: 'vylk',
      bulgarian: 'вълк, вълци',
      ttsText: 'вълк, вълци',
      ttsModel: 'pro',
      translations: {
        en: 'wolf, wolves',
        fr: 'loup, loups',
        ar: 'ذئب',
        fa: 'گرگ',
        ru: 'волк',
        uk: 'вовк',
      },
    },
    {
      id: 'elen',
      bulgarian: 'елен, -и',
      ttsText: 'елен, елени',
      ttsModel: 'pro',
      translations: {
        en: 'deer',
        fr: 'cerf, cerfs',
        ar: 'غزال / أيل',
        fa: 'گوزن',
        ru: 'олень',
        uk: 'олень',
      },
    },
    {
      id: 'syarna',
      bulgarian: 'сърна, -и',
      ttsText: 'сърна, сърни',
      ttsModel: 'pro',
      translations: {
        en: 'roe deer',
        fr: 'chevreuil',
        ar: 'ظبية',
        fa: 'آهو',
        ru: 'косуля',
        uk: 'козуля',
      },
    },
    {
      id: 'lisitsa',
      bulgarian: 'лисица, -и',
      ttsText: 'лисица, лисици',
      ttsModel: 'pro',
      translations: {
        en: 'fox, foxes',
        fr: 'renard, -s',
        ar: 'ثعلب',
        fa: 'روباه',
        ru: 'лиса',
        uk: 'лисиця',
      },
    },
    {
      id: 'roza',
      bulgarian: 'роза, -и',
      ttsText: 'роза, рози',
      ttsModel: 'pro',
      translations: {
        en: 'rose, -s',
        fr: 'rose, -s',
        ar: 'وردة',
        fa: 'گل رز',
        ru: 'роза',
        uk: 'троянда',
      },
    },
    {
      id: 'lavandula',
      bulgarian: 'лавандула',
      ttsText: 'лавандула',
      ttsModel: 'pro',
      translations: {
        en: 'lavender',
        fr: 'lavande',
        ar: 'خزامى',
        fa: 'اسطوخودوس',
        ru: 'лаванда',
        uk: 'лаванда',
      },
    },
  ],

  grammarReference: [
    {
      id: 'b1-l11-gr-superlatives',
      title: {
        bg: 'Превъзходна степен на прилагателните',
        en: 'Superlative degree of adjectives',
        fr: 'Superlatif des adjectifs',
        ar: 'صيغة التفضيل للصفات',
        fa: 'صفت عالی',
        ru: 'Превосходная степень прилагательных',
        uk: 'Найвища ступінь прикметників',
      },
      content: {
        bg: `В български превъзходната степен се образува с частицата **най-** пред прилагателното. Тя се пише с тире.\n\nПримери:\n• висок → **най-висок** (например: Мусала е най-високият връх.)\n• дълъг → **най-дълъг** (например: Стара Планина е най-дългата планинска верига.)\n• голям → **най-голям** (например: Рила е най-големият планински масив.)\n\nПревъзходната степен се съгласува по род и число с управляемото съществително:\n• най-висок**ият** връх (м.р., членувано)\n• най-висок**ата** планина (ж.р.)\n• най-висок**ото** езеро (ср.р.)\n• най-висок**ите** върхове (мн.ч.)`,
        en: `In Bulgarian, the superlative is formed with the particle **най-** before the adjective. It is written with a hyphen.\n\nExamples:\n• висок (tall/high) → **най-висок** (e.g. Musala is the highest peak.)\n• дълъг (long) → **най-дълъг** (e.g. Stara Planina is the longest mountain range.)\n• голям (large) → **най-голям** (e.g. Rila is the largest massif.)\n\nThe superlative agrees in gender and number with the noun: най-висок**ият** (m., definite), най-висок**ата** (f.), най-висок**ото** (n.), най-висок**ите** (pl.).`,
        fr: `En bulgare, le superlatif se forme avec la particule **най-** devant l'adjectif. Elle s'écrit avec un tiret.\n\nExemples :\n• висок → **най-висок** (ex. : Moussala est le sommet le plus haut.)\n• дълъг → **най-дълъг** (ex. : le Balkan est la chaîne la plus longue.)\n• голям → **най-голям** (ex. : Rila est le plus grand massif.)\n\nLe superlatif s'accorde en genre et en nombre avec le nom : най-висок**ият** (m.), най-висок**ата** (f.), най-висок**ото** (n.), най-висок**ите** (pl.).`,
        ar: `في اللغة البلغارية، تُصاغ الصفة العُليا بإضافة المقطع **най-** قبل الصفة وتُكتب بشرطة.\n\nأمثلة:\n• висок (عالٍ) ← **най-висок** (مثال: موسالا هي أعلى قمة.)\n• дълъг (طويل) ← **най-дълъг** (مثال: ستارا بلانينا هي أطول سلسلة جبلية.)\n• голям (كبير) ← **най-голям** (مثال: ريلا هي أكبر كتلة جبلية.)\n\nتتوافق الصفة العُليا مع الاسم في الجنس والعدد: най-висок**ият** (م.)، най-висок**ата** (م. مؤنث)، най-висок**ото** (م. محايد)، най-висок**ите** (جمع).`,
        fa: `در زبان بلغاری، صفت عالی با پیشوند **най-** قبل از صفت ساخته می‌شود و با خط تیره نوشته می‌شود.\n\nمثال‌ها:\n• висок (بلند) ← **най-висок** (مثال: موسالا بلندترین قله است.)\n• дълъг (طولانی) ← **най-дълъг** (مثال: استارا پلانینا طولانی‌ترین رشته کوه است.)\n• голям (بزرگ) ← **най-голям** (مثال: ریلا بزرگترین کوه‌پایه است.)\n\nصفت عالی با اسم در جنس و عدد مطابقت دارد: най-висок**ият** (م.)، най-висок**ата** (م. مؤنث)، най-висок**ото** (خنثی)، най-висок**ите** (جمع).`,
        ru: `В болгарском языке превосходная степень образуется с частицей **най-** перед прилагательным. Пишется через дефис.\n\nПримеры:\n• висок (высокий) → **най-висок** (например: Мусала — самая высокая вершина.)\n• дълъг (длинный) → **най-дълъг** (например: Стара Планина — самая длинная горная цепь.)\n• голям (большой) → **най-голям** (например: Рила — самый большой массив.)\n\nПревосходная степень согласуется с существительным по роду и числу: най-висок**ият** (м.р., с артиклем), най-висок**ата** (ж.р.), най-висок**ото** (ср.р.), най-висок**ите** (мн.ч.).`,
        uk: `У болгарській мові найвищий ступінь прикметника утворюється за допомогою частки **най-** перед прикметником. Пишеться через дефіс.\n\nПриклади:\n• висок (високий) → **най-висок** (напр.: Мусала — найвища вершина.)\n• дълъг (довгий) → **най-дълъг** (напр.: Стара Планіна — найдовший гірський хребет.)\n• голям (великий) → **най-голям** (напр.: Ріла — найбільший масив.)\n\nНайвищий ступінь узгоджується з іменником за родом і числом: най-висок**ият** (ч.р.), най-висок**ата** (ж.р.), най-висок**ото** (с.р.), най-висок**ите** (мн.).`,
      },
    },
  ],
};
